### ISSUE TITLE
BSRN program; Deadline 9.5.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#100]
The BSRN program is currently under GOS in OSCAR/Surface:
![image](https://user-images.githubusercontent.com/43061805/55780042-4ed30000-5aa7-11e9-93a1-58ec13353e8d.png)

Is this correct? I found [this document](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwivqJuwtcLhAhWDJFAKHSSCB2AQFjAAegQIBhAC&url=https%3A%2F%2Flibrary.wmo.int%2Fpmb_ged%2Fgcos_174_en.pdf&usg=AOvVaw0DYiQH_mWJ6lNrfPUImh14) on the Internet, which rather implies, that BSRN would belong to GCOS or GAW.
<<BSRN is a project of the Radiation Panel (now the Data and Assessment Panel) from the Global Energy and Water Cycle Experiment (GEWEX) under the umbrella of the World Climate Research Programme (WCRP). It is the global baseline network for surface radiation for the Global Climate Observing System (GCOS), contributing to the Global Atmospheric Watch (GAW), and forming a cooperative network with the Network for the Detection of Atmospheric Composition Change (NDACC).>>

Here, BSRN is listed as a Program related to GAW https://www.wmo.int/pages/prog/arep/gaw/interprog.html.

**Comment by joergklausen** [comment]
This is indeed a bit strange … I would have put it at GAW > GAW Other Elements > BSRN. Change in OSCAR/Surface is very easy, but what about the code table?

**Comment by HoratN** [comment]
We have not yet submitted the Release1 of the code tables to the fast track, and since Release 2 will be a sort of Patch Release, we can include this change there. 
The main question is, where is the correct place for BSRN? How do the Task Team member feel about that and who can help as with expert knowledge?

**Comment by HoratN** [comment]
I think that Dr. Christian Lanconelli, the Project manager of BRSN should know, where to put BSRN. I will ask him.

**Comment by HoratN** [comment]
Dr. Lanconelly from BSRN replied as follows:

as far as I can imagine, being BSRN was established in early 90's, a proper section would be "Co-sponsored>GCOS>" along with baseline reference networks such as GRUAN, for the Upper Air observations. But let me copy Tim/Caterina/Chuck on this, and they  may advise us on the correct position within OSCAR frame. I'm less aware of the fact "BSRN contribute to GAW" as stated in our web page but actually I'm not yet involved in any discussion or list about GAW. And I would avoid to frame BSRN under GAW for now.

Unfortunately, the people he copied in his e-mail did not reply so far.

**Comment by HoratN** [comment]
17.4.2019 TT-WMD
Etienne and Oksana should give feedback

**Comment by LuisaIckes** [comment]
We got feedback from some GCOS colleges at WMO now: BSRN should be under GCOS - in terms of the Codetables: it is only the path in Codetable 2-02 which has to be changed according to the issue?
So it should be:
\Co-sponsored\GCOS\BSRN
instead of (old version):
\WIGOS\GOS\GOS Surface networks\BSRN
?
Is the change then done analogous in OSCAR as soon as the release is out?

**Comment by nuneslf** [comment]
I support this change to the path in Code table 2-02, which should be then reflected in OSCAR/Surface.
On the other hand, I just realize that in the tree of "program/network affiliation" WIGOS is at the same level of Co-sponsored; According to the Tech.Regulations: "The WIGOS shall be a framework for all WMO observing systems and for WMO contributions to co-sponsored observing systems";
So, WIGOS should be at the top-level, and the level currently named "WIGOS" should be renamed, perhaps as "WMO Observing Systems"?

**Comment by joergklausen** [comment]
I have moved BSRN to \Co-sponsored\GCOS\BSRN. As to the overall organization of the tree, this has been reviewed and agreed by WMO, in particular Etienne, 2 years ago.

**Comment by LuisaIckes** [comment]
Changes in the following branch: [issue100](https://github.com/wmo-im/wmds/tree/issue100).
