### ISSUE TITLE
Definition of date established; Deadline 15.5.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#102]
Argentina requested a clear definition for what is meant by the field "date established". Should this be part of the WMDS and what would be the best definition? 
This field is already part of the WMDR.

The same questions apply to "date closed".

**Comment by HoratN** [comment]
There are several options on how to define the date established
- the day when the Station measured its first data
- Station was entered into a WMO observation program
- Station was entered into a WMO program(operational,partly-operational,stand-by) and measured its first data.
- any combination of these.

**Comment by joergklausen** [comment]
I think it would be most useful if the date established referred to the date when a station started to produce data.

**Comment by HoratN** [comment]
17.4.2019 TT-WMD

this should link to 1-03 Temporal Extent

clearify tooltip in OSCAR for date established according to Jörg's suggestion
--> date when station starts to measure

**Comment by LuisaIckes** [comment]
I think the issue should stay open until the deadline is over?
The tooltip should rather be (it is not the station that measures): date when the first measurement is done ?

**Comment by HoratN** [comment]
> 
> 
> I think the issue should stay open until the deadline is over?
> The tooltip should rather be (it is not the station that measures): date when the first measurement is done ?

**Comment by HoratN** [comment]
will be updated soon in OSCAR.
