### ISSUE TITLE
Nilreason; Deadline 16.5.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#103]
This tables are the only ones without the entries unknown/inapplicable:
- 1-02 units: inapplicable  is missing
- 8-3-01 quality flag
- 8-03-02 quality flag (Water ML2)

8-03-01 and 8-03-02 belong to 8-02 which has entries unknown and inapplicable, thus these 2 tables don't need unknown/inapplicable.

But for 1-02 "units", the entry inapplicable could be helpful, since this table probably never will contain all units. Moreover, the code tables would benefit from a more uniform appearance if we add inapplicable to this table. 

The following tables use the internal IDs from OSCAR/Surface as Notation:
- 1-01 variables
- 5-02 methods

Could we use the notation unknown for the entry unknown instead of the number 800?
The Notation unknown makes more sense from the user perspective, and this way OSCAR doesn't have to reserve internal IDs for these entries.
The same applies for inapplicable.

This issue follows up on the discussion in [issue 29](https://github.com/wmo-im/wmds/issues/29).

**Comment by joergklausen** [comment]
8-03-01 and -02 relate to 8-04, not 8-02. 8-02 relates to 8-01. These code tables (8-03-01 and -02) have been adopted. Both contain 'unchecked' (=unknown). Inapplicable is a meaningless entry in these tables.

1-02 should include unknown (unit could be unknown, even if that makes the value of an observation almost useless) and inapplicable (for categorical data). This requires communication with IPET-CM.

I am against entries unknown an inapplicable for code table 1-01.

I am in favor of including the term 'unknown' in code table 5-02, but I am against including 'inapplicable' in this table, because I cannot see the rationale. There is no observation that does not use a method.

**Comment by HoratN** [comment]
1-02  add inapplicable
1-01 no reason for unknown and inapplicable, remove both entries
5-02 keep what we have

inapplicable: None of the codes in this table is applicable in this context...

**Comment by LuisaIckes** [comment]
In one of the earlier TT-Meetings before the last release it was decided that 1-02 should not be changed because it is an "external" table- so this decission has been revised?

**Comment by HoratN** [comment]
> 
> 
> In one of the earlier TT-Meetings before the last release it was decided that 1-02 should not be changed because it is an "external" table- so this decission has been revised?

Yes, this decision has been revised and it has been decided to add the entry inapplicable, since it makes sense to have such an entry. Moreover we already changed that table by adding ca 10 new entries, so we can by now claim that this table is owned somehow by the task team.

**Comment by HoratN** [comment]
This part was not discussed at the last telecon:

The following tables use the internal IDs from OSCAR/Surface as Notation:

    1-01 variables
    5-02 methods

Could we use the notation unknown for the entry unknown instead of the number 800?
The Notation unknown makes more sense from the user perspective, and this way OSCAR doesn't have to reserve internal IDs for these entries.
The same applies for inapplicable.

**Comment by joergklausen** [comment]
I support this. Since there has been no input to the contrary for almost 2 months, I consider this accepted. We will update / extend the OSCAR/Surface ref tables accordingly.

**Comment by LuisaIckes** [comment]
Changes in the following branch: [issue103](https://github.com/wmo-im/wmds/tree/issue103).
