### ISSUE TITLE
3-02, New country: Andorra ?; Deadline 22.5.2019

### ISSUE THREAD

**Issue by fabricethebault** [wmo-im/wmds#106]
Andorra small country became the 192nd member of the WMO but is not present in the table 3-02. 

https://public.wmo.int/en/media/news/andorra-joins-wmo

**Comment by joergklausen** [comment]
Hi Nina
Can you add this to table 3-02, please? ISO code AND.
Thanks and kind regards
Jörg

Sent from my iPhone

On 22 Apr 2019, at 17:22, fabricethebault <notifications@github.com<mailto:notifications@github.com>> wrote:


Andorra small country became the 192nd member of the WMO but is not present in the table 3-02.

https://public.wmo.int/en/media/news/andorra-joins-wmo

**Comment by HoratN** [comment]
added this entry in commit 29c6353965a5b60b7c18665d6609395637d2d6d2 on branch [issue106](https://github.com/wmo-im/wmds/tree/issue106)

**Comment by fabricethebault** [comment]
Thank you!

**Comment by LuisaIckes** [comment]
Merged into development branch
