### ISSUE TITLE
Table 1-01-01

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#109]
The entries in the table should be ordered alphabetically according to path. As it stands, there are at least 2 groups of entries for /Atmosphere/Radiation, which is very confusing ...

**Comment by joergklausen** [comment]
Further, the path of 

273,\Atmosphere\Radiation\UV-B radiation,UV-B radiation,

needs to be corrected to

273,\Atmosphere\Radiation\**UV\**UV-B radiation,UV-B radiation,

(NB: This change has already been made in OSCAR/Surface)

**Comment by LuisaIckes** [comment]
Ok!
@joergklausen : is it ** in the path or is that supposed to be \ ?

**Comment by joergklausen** [comment]
> 
> 
> Ok!
> @joergklausen : is it ** in the path or is that supposed to be \ ?

The ** was supposed to print this in bold ... the corrected path is

273,\Atmosphere\Radiation\UV\UV-B radiation,UV-B radiation,

**Comment by LuisaIckes** [comment]
Corrected in branch [issue109](https://github.com/wmo-im/wmds/tree/issue109/).
