### ISSUE TITLE
Check first release of tables

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#11]
We need to check the first release of the tables as approved by CBS-16/EC-69. The tables are available on a test codes registry http://test.wmocodes.info/scratch-testing/jb1/wmds  . They are not meant for operational use or to be shared with external users. They are only meant to be accessed by the members of TT-WMD for checking purposes.
As soon as the tables are checked we will publish them on the codes.wmo.int registry and will be available for use of the general public.

**Comment by efucile** [comment]
@HoratN can you please have a look at the tables in the test registry and eventually share them with someone else? We are waiting that checks are completed to publish in the codes.wmo.int.

**Comment by HoratN** [comment]
What do I need to check? 
1. If they are consistent with what was approved by EC69?
2. If they are correct?
3. If they are up to date compared to OSCAR?
4. If they reflect the latest discussions in TT-WMD?

Regarding 2: There are two mistakes: the WMO306_CD of Romania should be ROU instead of ROM and Swaziland changed its name to Eswatini.
Regarding 3: many discrepancies

And I guess, that 2., 3. and 4. are sometimes overlapping. So my question is, which updates should be packed in this release and which should be done separately e.g. in #7 .

**Comment by HoratN** [comment]
@jenniferbest  , @efucile 
I found the following bugs on http://test.wmocodes.info/scratch-testing/jb1/wmds: 
- 4-04: entry 13 'Equipment maintenance' is missing
- 5-15: grammatical issue: In my opinion we should replace the definition for Class 2 by 'Exposure of instrument has small or **infrequent** influence on measurement'
- 9-02 entries 2 & 3: last half of the sentence is missing: ' – which may necessitate dialogue with the data publisher for confirmation of terms and conditions.'

**Comment by jenniferbest** [comment]
@HoratN
Before providing us with any more amendments, can you please confirm with your Team which source will be the authoritative document. WMO uses a combination of CBS/EC and in some cases a fast-track procedure.  Please let us know how you wish to proceed.

Once the Team has agreed on this, I think it would be easier if you download a copy and edit the tables form GitHub (https://github.com/wmo-im/wmds/tree/master/tables_en) and let us know when finalised.

Let me know your thoughts on this??

**Comment by efucile** [comment]
@HoratN we need first of all to be sure that what has been published in the CBS/EC reports is in this first release. Then we open another issue and we address the problems of the release.
We can annotate now the fact that some of the entries are missing in the codes registry while they are present in the csv. This is because the python script converting to ttl format is also doing a minimum quality control on the entries. For example entries with a "?" are considered suspect because we should not have a question in the description of a term. These problems should be addressed in another issue.
This is only to check that we have a release consistent with EC69. We will tag it as consistent with EC69. 
I would like to see another issue and another branch where we make all the changes on top of the baseline EC69. All the changes in these branch will have to be reviewed and approved by the team before the merge with master and before being published on codes.wmo.int. I would wait the completion of this last issue before the final publication.
I think that now we should only focus on building the EC69 baseline.

**Comment by HoratN** [comment]
@efucile, @jenniferbest Thanks for this clarification=) 
I think for the EC 69 baseline only one small correction is necessary:
In table 9-02 in the entries 2 & 3: the last half of the sentence is missing: ' – which may necessitate dialogue with the data publisher for confirmation of terms and conditions.'
I think this part was lost somewhere on the way into GitHub... It was still there in the EC69 version on Alfresco.

**Comment by HoratN** [comment]
@efucile ,@jenniferbest 
I fixed the issues caused by the transfer into GitHub. I also removed the "?" mentioned above. 
Moreover I transformed all tab separated tables into comma separated ones, removed the first column(the numbering) and sorted the table entries by Name_e. 
I think this branch is now the EC69 baseline.

**Comment by HoratN** [comment]
@efucile , @jenniferbest 
According to Notepad++ the master branch is encoded in UTF-8-BOM. Why do we use BOM? Would UTF-8 not be enough? I assume that it is easier to maintain UTF-8 than UTF-8-BOM while editing the tables, but I am not an expert in this field. What do you think about this? Do you rely on BOM for the processing of the tables?
