### ISSUE TITLE
Table 1-01-01 Radiation, Deadline: 19.07.2019

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#110]
TT-WMD needs to discuss and improve the list of radiation variables. Specifically, the origin of 575 (Reflected solar radiation) and the difference between 574 (Global solar radiation (upwelling)) and 575 (Reflected solar radiation) is unclear. One could argue that 

Global solar radiation (upwelling) = Reflected solar radiation + upward scattered radiation

So, we need to improve the definitions, possibly making more explicit reference to the atmospheric layer we refer to, e.g., near ground, TOA, etc. 

For reference:
574,\Atmosphere\Radiation\Solar\Global solar radiation (upwelling),Global solar radiation (upwelling),
575,\Atmosphere\Radiation\Solar\Reflected solar radiation,Reflected solar radiation,

**Comment by joergklausen** [comment]
I talked to Reto Stöckli and Laurent Vuilleumier, both radiation experts. Reto suggests to remove 575 because it is the same as 574. I agree with this suggestion, and I think we can do this at this stage - this code list has not been published. Since both have been used already in OSCAR/Surface, we will consult with the stations concerned (only 9 in total) and suggest to assign 574 in all cases. This term (574) is correct at all altitudes and does not imply a specific distance from ground, while 575 implies ground elevation.

**Comment by LuisaIckes** [comment]
@joergklausen @nuneslf : We did not discuss this in the teleconference now- should I shift the deadline behind summer and we leave it out of the release?

**Comment by joergklausen** [comment]
@LuisaIckes I have made my recommendation (remove 575 and assign 574 where 575 is used presently). After that, I wouldn't be opposed to including table 1-01-01 in the release. Notwithstanding, there will be changes to this particular code table, I am sure. 
If I need to decide now, this would be my decision. At the same time, and based on the outcome of TT-WMD-4 telco, Luis is supposed to consult with all of TT-WMD and seek approval for all the tables first.

**Comment by nuneslf** [comment]
I concur with Jörg. Now that one two TT-WMD members plus one invited expert still have pending invites to join the Github/TT-WMD group, I encourage all @wmo-im/tt-wmd to provide feedback, hoping that they will receive this notification.

**Comment by tonyboston-au** [comment]
I would be happy to support this recommendation.

**Comment by toakley76** [comment]
I agree to the proposal. I would have suggested asking a radiation expert to comment from the Baseline Surface Radiation Network (BSRN) but Joerg has talked with Swiss experts who represent this community.  So happy to go with this change.

**Comment by LuisaIckes** [comment]
Changes can be found in the branch [issue 110](https://github.com/wmo-im/wmds/tree/issue110).
