### ISSUE TITLE
1-01-03 Review of ocean variables, Deadline 31.01.2020

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#113]
In OSCAR/Codelist 1-01-03 the whole (sub)tree under Ocean should be reviewed with contributions from representatives of the marine community.

@nuneslf : Who should be contacted in terms of marine community?

**Comment by efucile** [comment]
We need to ask Champika who can be involved from JCOMM. I have few names, but we need to ask.

**Comment by LuisaIckes** [comment]
@nuneslf : Is there a JCOMM representative found now who can comment that?

**Comment by IgorZahumensky** [comment]
I have contacted Champika on this issue.

**Comment by LuisaIckes** [comment]
@efucile : Is there a reason why you opened a new issue for that? Can we join both (keep the new one and I delete this one)?

**Comment by efucile** [comment]
Please edit the table https://github.com/wmo-im/wmds/blob/issue113/tables_en/1-01-03.csv
with the github web editor or using a local editor able to handle properly unicode files.
Excel is not always god at that!

**Comment by RickLumpkin** [comment]
Line 7: add ", typically in upper 30 m of the ocean" at end.
Line 19: it isn't clear why "Total Alkalinity" is abbreviated "AT" unless this is the abbreviation from French.
Line 28: it's not clear why "requested in upper and deep ocean" is here
Line 29: missing quote before "Salinity of sea water in the surface layer"
Line 29: remove "In the open ocean the correct term should be "halinity" with reference of the diversity of salts involved."  This is technically true but very pedantic and not followed by oceanographers.
Line 35: should be highest 33 out of 100, not 30.

**Comment by joergklausen** [comment]
All these requests make sense, I have made the changes to the code table and committed to branch.

**Comment by champikagallage** [comment]
Existing content in 1-01-03 has already been reviewed by an ocean expert and provided comments. Broader consultation with Ocean community resulted identification of issues with subcategories and missing parameters (looking at ocean ECVs EOVs). These will be worked out with the assistance from Ocean experts and submit necessary changes soon.

**Comment by amilan17** [comment]
This is the branch: https://github.com/wmo-im/wmds/blob/issue113/tables_en/1-01-03.csv

**Comment by amilan17** [comment]
@champikagallage  - Is this still waiting for more reviews and comments from the broader community?

**Comment by joergklausen** [comment]
I would argue this definitely needs review. In particular, it would make sense to align the paths leading up to a variable with the approach taken for the terrestrial variables, cf. Ocean\Snow-Ice-Glacier\… should probably be changed.

**Comment by amilan17** [comment]
#165 addresses the path.

**Comment by amilan17** [comment]
Ready to merge with master for FT

**Comment by joergklausen** [comment]
@amilan17 This branch supports a number of improvements on wording in the code table. It is okay from my point of view.
Make sure you merge this before you merge the other branch dealing with the path. This branch shows incorrect paths for variables 401-407.
