### ISSUE TITLE
2-02 Programs/networks: addition of GOOS/DBCP entries, deadline 24.08.2019

### ISSUE THREAD

**Issue by anthoninlize** [wmo-im/wmds#115]
**Branch**
https://github.com/wmo-im/wmds/tree/issue115

**proposal**
Dear all,

We would need the following new entries:
* \Co-sponsored\GOOS\DBCP\GDP-ESURFMAR
* \Co-sponsored\GOOS\DBCP\GDP-MF
* \Co-sponsored\GOOS\DBCP\COPERNICUS-HRSST-FRM
* \Co-sponsored\GOOS\DBCP\IPAB-US
* \Co-sponsored\GOOS\DBCP\SAILDRONE
* \Co-sponsored\GOOS\DBCP\JAMSTEC-DB
* \Co-sponsored\GOOS\DBCP\PORTUGAL-MB
* \Co-sponsored\GOOS\DBCP\SPAIN-IEO-MB

Thank you,
Best

**Comment by joergklausen** [comment]
Bearing in mind that @anthoninlize is the designated JCOMMOPS rep in TT-WMD and our best available expert on this, I only checked if these entries do not yet exist (they do not) and are syntactically correct (they are).

We also need the WMO306_CD for these entries. After reviewing what existis already in the table, I propose the following:
    \Co-sponsored\GOOS\DBCP\GDP-ESURFMAR: eSurfmarGDP
    \Co-sponsored\GOOS\DBCP\GDP-MF: GDPMF
    \Co-sponsored\GOOS\DBCP\COPERNICUS-HRSST-FRM: copernicusHRSSTFRM
    \Co-sponsored\GOOS\DBCP\IPAB-US: IPABUS
    \Co-sponsored\GOOS\DBCP\SAILDRONE: saildrone
    \Co-sponsored\GOOS\DBCP\JAMSTEC-DB: JAMSTECDB
    \Co-sponsored\GOOS\DBCP\PORTUGAL-MB: PortugalMB
    \Co-sponsored\GOOS\DBCP\SPAIN-IEO-MB: SpainIEOMB

There is no consistency for what is written in caps vs small-caps, but the above is in line with what we have now.

I suggest there is no need for a 4-week deadline, this is purely technical.

**Comment by LuisaIckes** [comment]
From what I understood did we say "technical" are only typo fixes etc., everything that really changes the codelists should not be technical?, but we can adapt the procedure here of course. So I can change the label and deadline. However, it does not really make a difference if we leave 1 or 4 weeks of deadline now - the new release is already out. If this should be part of the release going on the code registry and to the fast track we need another release.

**Comment by joergklausen** [comment]
Hi Luisa
the difference is that, if we can agree amongst the team members, we can safely include this in OSCAR/Surface, which can be done quickly and which is a prerequisite for the M2M upload of DBCP metadata by JCOMMOPS. The release on the codes registry and official approval through the fast-Track is not so urgent in this case, it would seem.
Cheers
Jörg

Sent from my iPhone

On 24 Jul 2019, at 15:34, LuisaIckes <notifications@github.com<mailto:notifications@github.com>> wrote:


From what I understood did we say "technical" are only typo fixes etc., everything that really changes the codelists should not be technical?, but we can adapt the procedure here of course. So I can change the label and deadline. However, it does not really make a difference if we leave 1 or 4 weeks of deadline now - the new release is already out. If this should be part of the release going on the code registry and to the fast track we need another release.

**Comment by LuisaIckes** [comment]
@anthoninlize : Is there a description to be added for these entries as well?

**Comment by anthoninlize** [comment]
Yes, for some of them :
\Co-sponsored\GOOS\DBCP\GDP-ESURFMAR: eSurfmarGDP
Global Drifter Program drifters with E-SURFMAR barometer upgrades

\Co-sponsored\GOOS\DBCP\GDP-MF: GDPMF
Global Drifter Program drifters with Meteo-France barometer upgrades

\Co-sponsored\GOOS\DBCP\IPAB-US: IPABUS
International Programme for Antarctic Buoys - US

\Co-sponsored\GOOS\DBCP\JAMSTEC-DB: JAMSTECDB
Japan Agency for Marine-Earth Science and Technology Drifting Buoy

\Co-sponsored\GOOS\DBCP\PORTUGAL-MB: PortugalMB
Portugal - Instituto Hidrografico (IH)

**Comment by LuisaIckes** [comment]
@anthoninlize : Thank you! I will add N/A for the remaining.

**Comment by joergklausen** [comment]
This all makes sense and consists of non-controversial additions to an existing table.
@LuisaIckes Please update the files accordingly.
We will implement this in OSCAR/Surface asap.

**Comment by LuisaIckes** [comment]
The changes are done in [issue 115](https://github.com/wmo-im/wmds/tree/issue115).

**Comment by amilan17** [comment]
Reopening issue because it was not included in the previous FT cycle.

**Comment by joergklausen** [comment]
@fstuerzl Verify consistency of branch and follow through

**Comment by fstuerzl** [comment]
@amilan17, I checked the branch and can confirm that the new entries are consistent with OSCAR.

**Comment by joergklausen** [comment]
@anthoninlize Please verify entries in branch  issue 115 (https://github.com/wmo-im/wmds/blob/issue115/tables_en/2-02.csv) are correct and add definitions where still missing. Deadline: 10 January 2021.

**Comment by anthoninlize** [comment]
@joergklausen I would need a more extended deadline because of the holidays season, and I can't get all the missing descriptions by myself, I need inputs from the team who is on holidays and I won't be able to chat with them before 10 January 2021

I'll add the ones I have already today

**Comment by anthoninlize** [comment]
Attached a copy of the file with new descriptions, when available. I'll provide more later when I can meet the team.
[2-02.zip](https://github.com/wmo-im/wmds/files/5724877/2-02.zip)

**Comment by fstuerzl** [comment]
Thanks, @anthoninlize, the branch is up to date now. The only descriptions still missing are the ones for "saildrone" and "SpainIEOMB".

**Comment by anthoninlize** [comment]
Great! I've seen other entries with missing descriptions from our side... More than those two ones. We'll update this as soon as possible.

Thanks!

**Comment by amilan17** [comment]
fixed conflicts and merged with FT-2021-1-validation branch

**Comment by champikagallage** [comment]
(352) \Co-sponsored\GOOS\DBCP\SAILDRONE
SAILDRONE description:  Autonomous Surface Vehicles deployed by NOAA as pilot
(364)  \Co-sponsored\GOOS\DBCP\SPAIN-IEO-MB
SPAIN-IEO-MB description: Moored Buoys Managed by Spanish Institute of Oceanography of the Ministry of Science and Technology

**Comment by amilan17** [comment]
@fstuerzl - please update branch with new descriptions and tag anna when done

**Comment by fstuerzl** [comment]
@amilan17 , @champikagallage branch updated: https://github.com/wmo-im/wmds/commit/7a65dfb6e6ab4d652184269e5d75193d6d0c48c8
