### ISSUE TITLE
2-02 Programs/networks: addition of GCW entries, deadline 31.08.2019

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#116]
The GCW community (request from the GCW Project Office) would like to have the following additions/change of entries in Table 2-02:

_**notation, path, name, description**_

**GCWCryoNet**, \WIGOS\GCW\GCW CryoNet station, GCW CryoNet station, "A GCW station measuring at least one variable of one cryosphere component, and meeting a set of defined requirements."

**GCWcontributing**, \WIGOS\GCW\GCW Contributing station, GCW Contributing station, A GCW station which provides useful measurements of the cryosphere but does not meet all requirements for a CryoNet Station.

**GCWaffiliated**, \WIGOS\GCW\GCW affiliated station, GCW affiliated station, "A station of an GCW affiliated network measuring at least one cryospheric variable, contributing to GCW in addition to CryoNet and GCW contributing stations."

The first entry here (GCWCryoNet) should replace the entry CryoNet (CryoNet, \WIGOS\GCW\CryoNet, CryoNet, NA).

**Comment by joergklausen** [comment]
This all makes sense and consists of non-controversial additions to an existing table.
@LuisaIckes Please update the files accordingly.
We will implement this in OSCAR/Surface asap.

**Comment by amilan17** [comment]
Re-opening, because this change is not merged to master, nor approved through Fast Track.

**Comment by amilan17** [comment]
add a superseded table for CryoNET

**Comment by IgorZahumensky** [comment]
if "Ready for fast-track or TC", the label of FT is missing

**Comment by amilan17** [comment]
Approved by FT 2020-2
