### ISSUE TITLE
2-02 Spelling Convention for notation

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#118]
The present table contains upper/lower-case spelling that is not entirely consistent. Notations must be unique within a table regardless of capitalization. Even though an application (such as OSCAR/Surface) using these terms should not consider the capitalization of the notation, for human-readability, there should be consistent spelling. It is therefore proposed to apply the following rules:
1. Abbreviations use upper-case letters, also in the case where several abbreviations are concatenated. 
2. Names that are recognized as English words are spelled in lower-case.
3. Upper/lower-case spelling that is in common use or a community term is preserved.
4. Country names or other geographical names are spelled in title case (first letter capitalized, all others small-caps)
Examples: 
- GAW (not gaw), an accronym
- GAWcontributing (not gawContributing), an accronym concatenated with a word
- GAWABOS (not GAWabos), both are accronyms
- GCWCryoNet, GCW is an accronym, CryoNet a community term
- ARGORussia (not argoRussia)
- ARGOMEXCOUS (not argoMexCoUS), concatenation of accronyms
- TAOPirata (not taoPirata), accronym concatenated with geographical name

**Comment by LuisaIckes** [comment]
Is MexCoUS an acronym? Not relating to geographical name?

**Comment by nuneslf** [comment]
The rules look good to me, so I suggest we approve and close this issue, i.e. just the rules;
On the other hand, another issue could be raised for applying the rules, which will need some more time for the various representatives of different communities to review and implement them.
So, I suggest TT-WMD-8 as a deadline for the new issue on implementing the rules.

**Comment by LuisaIckes** [comment]
I think we can extend the deadline of this issue to TT-WMD8 and change it to a real issue (discussion required) since it requires input from all communities instead of opening a new issue (to keep the number of new issue/total issues low). How do we make sure to get input on all affiliations until then?

**Comment by nuneslf** [comment]
I agree with @LuisaIckes, and to engage the representatives of the various communities I suggest to start by mentioning the @wmo-im/tt-wmd so the members of the Task Team can be notified of this issue and start reviewing the names listed in table 2-02 "Programme/Network Affiliation", according to these rules.

**Comment by LuisaIckes** [comment]
Great! I am waiting for the feedback then- do we have the whole table covered with all TT-WMD members?

**Comment by LuisaIckes** [comment]
Decision on the teleconference on 23.09.2019:
The rules are good to go/be implemented.
Luisa will give it a first try and shares the programs/networks where she is not sure in which category they follow.

**Comment by KarlBureau** [comment]
I support the use of a consistent standard. 
This principle: "Upper/lower-case spelling that is in common use or a community term is preserved" is important where common usage is contrary to the other rules, as with CryoNet.

**Comment by joergklausen** [comment]
@IgorZahumensky Please create a wiki page in the spirit of a 'Guidance for spelling of notation' for new elements

**Comment by IgorZahumensky** [comment]
Guidance for spelling of notation (https://github.com/wmo-im/wmds/wiki/Guidance-for-spelling-of-notation) ready for further editing
