### ISSUE TITLE
tables from OSCAR

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#12]
Before doing anything with the tables from OSCAR we need to have a consolidated baseline of tables from EC69. This work should not start until we are happy with EC69 tables. This is extremely important.

**Comment by nuneslf** [comment]
@efucile I suggest to close this issue, or do you see the need for it yet?

**Comment by HoratN** [comment]
In my opinion we can close it.

**Comment by LuisaIckes** [comment]
@efucile can it be closed?
