### ISSUE TITLE
1-02 Problem with greek characters

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#121]
We have some problems with the greek characters when uploading the table to the code registry. 
I therefore suggest to replace the greek character mu the following (one example):
μmol_mol-1, micromoles per mole,
with
mumol_mol-1, micromoles per mole,
or
micromol_mol-1, micromoles per mole,

Which version is preferred?

The same would yield for the following units/entries in the table:
μmol_kg-1, micromoles per kilogram,	
μmol_l-1, micromoles per litre,	
μg_m-3_20C, micrograms per cubic metre at 20 degrees,	
μg_m-3_25C, micrograms per cubic metre at 25 degrees,
μg_N_m-3, microgram N per cubic metre,	
μg_C_m-3, microgram C per cubic metre,	
μg_S_m-3, microgram S per cubic metre,	
μg_Cl_m-3, microgram CI per cubic metre,

**Comment by nuneslf** [comment]
I support the proposal for using "micro" to replace "μ".

**Comment by joergklausen** [comment]
If we diverge from the WMO 306 code table for units (and it seems, we have decided to do that), then using UA-5 and spelling-out the names of greek prefixes and the like is the safer option. The CF Convention (unidata) have a very solid approach to this, and we could/should https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2.html#Database as a basis for scrutinizing our table and the names we use.

**Comment by LuisaIckes** [comment]
Outcomes of the teleconference on the 23.09.:
Replace μ-character with CF-convention: u.

**Comment by LuisaIckes** [comment]
Changes can be found [here](https://github.com/wmo-im/wmds/tree/issue121).
