### ISSUE TITLE
1-01 Glacier variables recommended by GCW, for inclusion in WMDS, Deadline: 30.09.2019

### ISSUE THREAD

**Issue by lijuan-ma** [wmo-im/wmds#123]
A list of glacier variables with short definitions, recommended by GCW Working Group on Observations, for inclusion in the WIGOS Metadata Standard, Table 1-01, was submitted to TT-WMD-7 (30/11/2018), but finally was not discussed at the meeting due to some reason. This outstanding issue surfaced due to registration of GCW stations in OSCAR/surface.

In brief, these variables are: 
•	Surface mass balance (point) – new variable
•	Surface mass balance (glacier wide) – new variable
•	Glacier area: revised name and definition
•	Surface accumulation (point) – new variable
•	Surface ablation (point) – new variable

Attached is the document submitted at that time, with details, for TT-WMD review and approval.
[Docs_4.2(6)_GCW_TT-WDM-7_Geneva_30Nov2018.docx](https://github.com/wmo-im/wmds/files/3634760/Docs_4.2.6._GCW_TT-WDM-7_Geneva_30Nov2018.docx)

**Comment by LuisaIckes** [comment]
Question to the GCW community:
Point surface mass balance or Surface mass balance (point)
Glacier wide surface mass balance or Surface mass balance (glacier wide)
?

**Comment by lijuan-ma** [comment]
GCW PO have consulted with the GCW experts regarding the naming of glacier variables, without parenthesis, for inclusion in the WMDS.

As a result, the following variable names, to the left on each row, have been agreed, for the final approval of TT-WMD:
- "Glacier mass balance at a point" instead of Surface mass balance (point)
- “Glacier-wide mass balance" instead of Surface mass balance (glacier wide)
- "Surface accumulation at a point" instead of Surface accumulation (point)
- "Surface ablation at a point" instead of Surface ablation (point)

**Comment by LuisaIckes** [comment]
Changes to Table 1-01 can be seen in this [branch](https://github.com/wmo-im/wmds/tree/issue123).

**Comment by LuisaIckes** [comment]
@luciacap : There are 4 new suggested variables, which (preliminary) numbers should be assigned to them for the notation?

**Comment by LuisaIckes** [comment]
I changed the definition of the first two variables (Glacier mass balance at a point and Glacier-wide mass balance) in accordance to the new name.

**Comment by lijuan-ma** [comment]
I'll seek agreement within relevant GCW group.

**Comment by luciacap** [comment]
> 
> 
> @luciacap : There are 4 new suggested variables, which (preliminary) numbers should be assigned to them for the notation?
12009
12010
12011
12012
You can decide which  ID to assign to each variable.

**Comment by LuisaIckes** [comment]
Thank you!

**Comment by lijuan-ma** [comment]
> I changed the definition of the first two variables (Glacier mass balance at a point and Glacier-wide mass balance) in accordance to the new name.

GCW experts have agreed to remove the repeated words in the beginning of each definition of the above-mentioned two variables, to avoid confusion.

As a result, please change the definition from

- **Glacier mass balance at a point**: _Surface mass balance is the result of all processes adding and removing mass from the glacier at a point on its surface, expressed over a stated period of time._ 
- **Glacier-wide mass balance**: _Surface mass balance (glacier wide) is the result of all processes adding and removing mass from the glacier at its surface, expressed over a stated period of time and integrated over the entire glacier area._

to 

- **Glacier mass balance at a point**: _the result of all processes adding and removing mass from the glacier at a point on its surface, expressed over a stated period of time._ 
- **Glacier-wide mass balance**: _the result of all processes adding and removing mass from the glacier at its surface, expressed over a stated period of time and integrated over the entire glacier area._

Please note the updated definitions are scientifically unchanged, which had been submitted by GCW and accepted by TT-WMD, and compliance in form with most definitions in the standard. 

I would recommend that the issue is closed after acknowledging the receipt of this notification, by 20 February. 

@joergklausen @KarlBureau @nuneslf @IgorZahumensky @kurt-hectic

**Comment by efucile** [comment]
Never implemented on a fast track. Needs to go in FT-2020-2

**Comment by efucile** [comment]
New branch needs to be created

**Comment by joergklausen** [comment]
Further discussion of this under #165.
