### ISSUE TITLE
3-09, meaning of entry "Stand-by" unclear; Deadline: 31.10.2019

### ISSUE THREAD

**Issue by luciacap** [wmo-im/wmds#124]
Missing definition for entry "Stand-by"

**Comment by LuisaIckes** [comment]
Click [here](https://github.com/wmo-im/wmds/blob/master/tables_en/3-09.csv) to see Table 3-09 for the context.

**Comment by joergklausen** [comment]
Stand-By := The station is ready for immediate use, but is not currently active. Mostly relevant for back-up stations, particularly satellites in orbit.

Sent from my iPhone

On 24 Sep 2019, at 14:37, luciacap <notifications@github.com> wrote:

﻿

Missing definition for entry "Stand-by"

**Comment by LuisaIckes** [comment]
should we add a comment to the difference of a non-reporting station?

**Comment by LuisaIckes** [comment]
05.11. teleconference:
The station is ready for immediate use, but is not currently operational. Mostly relevant for back-up stations, particularly satellites in orbit.

**Comment by gaubert** [comment]
This wording is fine for satellite platforms.
