### ISSUE TITLE
New units to code table 1-02; Deadline: 30.10.2019

### ISSUE THREAD

**Issue by richard-olav** [wmo-im/wmds#127]
Are the following units in the code table 1-02.csv: if not I propose:

'1/cm3' -> 'cm-3',
'H/m3' -> 'ne_H_m-2',
'ue H/l' -> 'ue_H_l-1',
'ng/m2day' -> 'ng_m-2_day-1',
'no unit' -> 'no_unit'

**Comment by LuisaIckes** [comment]
Except "no unit" they are not.

Please also provide a "written out" name and if necessary/helpful a description. The proposed notation is the writing on the right?

H/m3 is the same as ne_H_m-2?

no unit can be set as "dimensionless".

**Comment by richard-olav** [comment]
So for data without a unit, the notation is "1" (https://github.com/wmo-im/wmds/blob/master/tables_en/1-02.csv)?

**Below is the units as we have them in EBAS with a description.** Please add whatever notation you think is feasible.

**1/cm3:** Cubic centimetre
**ne H/m3:** nano equivalent hydrogen per cubic meter (concentration of the hydrogen ion in air)
**ue H/L:** microequivalents hydrogen per liter (concentration of the hydrogen ion in precipitation)
**ng/m2day:** nanogram per quadratmeter per day. (deposition rate)

**Comment by LuisaIckes** [comment]
Yes, no unit = 1 (dimensionless).

To put everything together the suggestion is to add (that suggestions is consistent with the existing table):
**notation, name, description**
cm-3, Cubic centimetre, 
ne_H_m-3, nano equivalent hydrogen per cubic meter, concentration of the hydrogen ion in air
ue_H_l-1, microequivalents hydrogen per liter, concentration of the hydrogen ion in precipitation
ng_m-2_day-1, nanogram per quadratmeter per day, deposition rate

@richard-olav : Is that suggestion ok or do you want to leave the description in brackets in the name column (that however would be inconsistent)?

**Comment by richard-olav** [comment]
You suggestion looks good to me.
Thanks!

**Comment by LuisaIckes** [comment]
notation, name, description
cm-3, Cubic centimetre,
ne_H_m-3, nano equivalent hydrogen per cubic meter,
ue_H_l-1, microequivalents hydrogen per liter,
ng_m-2_day-1, nanogram per square meter per day,

**Comment by tonyboston-au** [comment]
cm-3, cubic centimeter,

**Comment by LuisaIckes** [comment]
@tonyboston-au : Thx Tony!
