### ISSUE TITLE
3-02 new name for territory "Macedonia, the former Yugoslav Republic of"; Deadline: 01.11.2019

### ISSUE THREAD

**Issue by luciacap** [wmo-im/wmds#128]
New official name for "Macedonia, the former Yugoslav Republic of" is "North Macedonia, Republic of".

**Comment by joergklausen** [comment]
We do not maintain historical names of territories in the WMDS codelists, so this change should simply be applied. In my opinion, no discussion is needed, this is a purely technical/editorial change of the name, I am assuming that the ISO numerical code doesn't change. I will close the issue.

**Comment by LuisaIckes** [comment]
I agree, maybe we could agree (concerning the workflow) that everything related to table 3-02 is always a technical change and can be implemented promptly without further discussion?
