### ISSUE TITLE
Add new entry in Table 5-02-01; Deadline 22.11.2019

### ISSUE THREAD

**Issue by mustafaserttr** [wmo-im/wmds#133]
There is a new entry need in table 5-02-01 for the weather radars. 
There are two entries for the Radar transmitters, Klystron and Magnetron in the table. To me, "Solid State" should be add in this table like below;
\Atmosphere\Precipitation\Remote-sensing, active\Radio detection and ranging (Radar)\Solid State

**Comment by LuisaIckes** [comment]
So, the suggestion is:
**notation, path, name, description**
number-to-be-added, \Atmosphere\Precipitation\Remote-sensing, active\Radio detection and ranging (Radar)\Solid State, Solid State, 
No description so far?

**Comment by LuisaIckes** [comment]
05.11.2019 accepted in teleconference
