### ISSUE TITLE
New code list 5-03-01 Polarization; Deadline: 31.01.2020

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#134]
Code list already used in OSCAR/Surface. This one is used to describe the polarization of electromagnetic radiation to characterize instruments, e.g., radars.
[5-03-01.txt](https://github.com/wmo-im/wmds/files/3804224/5-03-01.txt)

**Comment by LuisaIckes** [comment]
You can see the suggested table [here](https://github.com/wmo-im/wmds/blob/issue134/tables_en/5-03-01.csv).

**Comment by IgorZahumensky** [comment]
Based on the instructions by Enrico it has to be reopen till Fast track

**Comment by amilan17** [comment]
(copied from branch)

**Decision** 

notation | name | description
-- | -- | --
  | lhcp | LHCP | left-hand circular polarization
  | rhcp | RHCP | right-hand circular polarization
  | linear | linear | linear polarization
  | lrhcp | LHCP & RHCP | left- and right-hand circular polarization
  | single | single | single polarization
  | dual | dual | dual polarization

**Comment by amilan17** [comment]
Branch: https://github.com/wmo-im/wmds/blob/issue134/tables_en/5-03-01.csv

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Will you please verify that the branch contains the correct information and the table name, description and URI are correct? 
https://github.com/wmo-im/wmds/blob/issue134/tables_en/wmdr-tables.csv

**Comment by joergklausen** [comment]
The table https://github.com/wmo-im/wmds/blob/issue134/tables_en/5-03-01.csv is correct.

The name of the table 5-03-01 should be 'Polarization of electromagnetic radiation'. This is not restricted to the characterization of instruments.

**Comment by amilan17** [comment]
I updated the table name.

**Comment by amilan17** [comment]
Approved by FT 2020-2
