### ISSUE TITLE
New code list 5-03-02 FrequencyUse; Deadline: 31.01.2020

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#135]
Code list already used in OSCAR/Surface. This one is used to describe the frequency use of electromagnetic radiation.
[5-03-02.txt](https://github.com/wmo-im/wmds/files/3804241/5-03-02.txt)

**Comment by LuisaIckes** [comment]
You can see the suggested table [here](https://github.com/wmo-im/wmds/blob/issue135/tables_en/5-03-02.csv).

**Comment by LuisaIckes** [comment]
Should it not be "Transmit Receive" instead of "TransmitReceive" in the name column?

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Can you verify that this is ready for Fast Track? In particular, please review table description and URI. 

5-03-02,Frequency use of electromagnetic radiation,http://codes.wmo.int/wmdr/FrequencyUse

**Comment by joergklausen** [comment]
The name 'Transmit Receive' in the branch should either be 'TransmitReceive' or 'Transmit and receive' (no preference for either one from my side)

**Comment by amilan17** [comment]
changed name to 'Transmit and Receive.

**Comment by amilan17** [comment]
This is ready for FT.

**Comment by amilan17** [comment]
Approved by FT 2020-2
