### ISSUE TITLE
New code list 5-03-03 PurposeOfFrequencyUse; Deadline: 31.01.2020

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#136]
Code list already used in OSCAR/Surface. This one is used to describe if electromagnetic radiation is used for observation or telecommunication. This is important to know because many frequencies used for observation are dictated by physics and cannot be changed (hence need to be protected).
[5-03-03.txt](https://github.com/wmo-im/wmds/files/3804243/5-03-03.txt)

**Comment by LuisaIckes** [comment]
You can see the suggested table [here](https://github.com/wmo-im/wmds/blob/issue136/tables_en/5-03-03.csv).

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Can you verify that this branch is ready for Fast Track? In particular, please review the new table name, description and URI. 
https://github.com/wmo-im/wmds/blob/issue136/tables_en/5-03-03.csv
https://github.com/wmo-im/wmds/blob/issue136/tables_en/wmdr-tables.csv

**Comment by joergklausen** [comment]
https://github.com/wmo-im/wmds/blob/issue136/tables_en/5-03-03.csv is correct.

In https://github.com/wmo-im/wmds/blob/issue136/tables_en/wmdr-tables.csv, the name of the table 5-03-03 should rather be 'Purpose of frequency use', I think.

**Comment by amilan17** [comment]
I changed the name of the table to Purpose of frequency use.

**Comment by amilan17** [comment]
Approved by FT 2020-2
