### ISSUE TITLE
New code list 5-03-04 TransmissionMode; Deadline: 31.01.2020

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#137]
Code list already used in OSCAR/Surface. This one is used to describe if electromagnetic radiation is transmitted continuously or as pulses. An important metadata element for remote sensing.
[5-03-04.txt](https://github.com/wmo-im/wmds/files/3804270/5-03-04.txt)

**Comment by LuisaIckes** [comment]
You can see the suggested table [here](https://github.com/wmo-im/wmds/blob/issue137/tables_en/5-03-04.csv).

**Comment by amilan17** [comment]
@joergklausen @KarlBureau -- Can you please verify that this branch is ready for Fast Track and review the new table description and URI
5-03-04,Electromagnetic radiation transmission,http://codes.wmo.int/wmdr/TransmissionMode

**Comment by joergklausen** [comment]
I think the table name is technically correct, if a bit clunky. I would probably choose 'Energy transmission', which would leave room for future expansion to non-electromagnetic energy, such as particle or radioactivity pulses (if ever there should be a need for that ...).

**Comment by amilan17** [comment]
I changed the name of table to 'Mode of energy transmission'. You can see the edits in this branch: 
https://github.com/wmo-im/wmds/blob/issue137/tables_en/wmdr-tables.csv.

**Comment by amilan17** [comment]
Approved by FT 2020-2
