### ISSUE TITLE
merge tables 4-01-x into 4-02

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#140]
table 4-02 http://codes.wmo.int/wmdr/SurfaceCoverClassification is the top level of 

4-01-01	Surface cover types (IGBP)	http://codes.wmo.int/wmdr/SurfaceCoverIGBP
4-01-02	Surface cover types (UMD)	http://codes.wmo.int/wmdr/SurfaceCoverUMD
4-01-03	Surface cover types (LAI/fPAR)	http://codes.wmo.int/wmdr/SurfaceCoverLAI
4-01-04	Surface cover types (NPP)	http://codes.wmo.int/wmdr/SurfaceCoverNPP
4-01-05	Surface cover types (PFT)	http://codes.wmo.int/wmdr/SurfaceCoverPFT
4-01-06	Surface cover types (LCCS)	http://codes.wmo.int/wmdr/SurfaceCoverLCCS
4-01-07	Surface cover types (Globcover2009) http://codes.wmo.int/wmdr/SurfaceCoverGlob2009
It has been decided durint TT-WMD meeting to have those tables directly under 4-02 this will provide the following URI

http://codes.wmo.int/wmdr/SurfaceCoverClassification same as current 4-02 
http://codes.wmo.int/wmdr/SurfaceCoverClassification/igbp points to table same as current  http://codes.wmo.int/wmdr/SurfaceCoverIGBP

@joergklausen please confirm that this is what we want to do

**Comment by LuisaIckes** [comment]
The problem is how to actually represent a "hierarchy" in our "flat" list of tables etc.. I think this needs a bit further thought and therefore should maybe be implemented for the next release (since the actualy one is already published on Codes anyway)?

**Comment by nuneslf** [comment]
@wmo-im/tt-wmd 
Jörg, Renaming 4-02 to 4-01 would create an inconsistency with the standard, because these are two different elements of the WMDS [Surface cover (4-01) and Surface cover classification scheme (4-02)].

**Comment by joergklausen** [comment]
Hi Luis
You are right, but if we discover we made a mistake, is it not better to correct it as early as possible, and to come clean, rather then to perpetuate it?
Kind regards
Jörg

Sent from my iPhone

On 5 Nov 2019, at 17:16, nuneslf <notifications@github.com> wrote:

﻿

@wmo-im/tt-wmd<https://github.com/orgs/wmo-im/teams/tt-wmd>
Jörg, Renaming 4-02 to 4-01 would create an inconsistency with the standard, because these are two different elements of the WMDS [Surface cover (4-01) and Surface cover classification scheme (4-02)].

**Comment by toakley76** [comment]
I agree with Jörg that we need to correct things that are wrong. In reality these are the same element and if we didn't have all the different classification scheme's there would only be the one element. I think at one of our meetings we decided to make the different classification a separate element of metadata, just to simplify the table. Cheers Tim

**Comment by toakley76** [comment]
Sorry not an expert here I should have just added a comment. Not selected Close and comment!!

**Comment by LuisaIckes** [comment]
No worries Tim, nothing gets permanently lost here/everything is reversible here :-)...

**Comment by LuisaIckes** [comment]
We will add a new folder with the WMDS itself in future, so that we can also change/correct things directly related to the standard (not the Codetables), such as numbers etc. I'll post the link here when it is done.

**Comment by nuneslf** [comment]
@wmo-im/tt-wmd 
Thanks @LuisaIckes, we really need that, because changes to metadata elements should be done first on the WMDS, and then propagated to the WMDR and OSCAR/Surface in a consistent way.
@joergklausen and @toakley76 So, I support the proposed changes to 4-01-x/4-02 (and also 8-03/8-04).

**Comment by IgorZahumensky** [comment]
I fully agree with Luis; only this order of steps is correct: the first is the WMDS; the both, WMDR and OSCAR/Surface have to follow the Standard and to be consistent with it; it is equally true for a new development as well as for changes (fixing problems discovered).

**Comment by efucile** [comment]
example
http://codes.wmo.int/wmdr/SurfaceCoverClassification/globCover2009/urbanBuiltup

**Comment by efucile** [comment]
mapping standard to codelist
4-02 http://codes.wmo.int/wmdr/SurfaceCoverClassification
4-01-07 http://codes.wmo.int/wmdr/SurfaceCoverClassification/globCover2009

**Comment by efucile** [comment]
branch implementing this change https://github.com/wmo-im/wmds/tree/issue140

**Comment by joergklausen** [comment]
> mapping standard to codelist
> 4-02 http://codes.wmo.int/wmdr/SurfaceCoverClassification
> 4-01-07 http://codes.wmo.int/wmdr/SurfaceCoverClassification/globCover2009
and similarly for the other tables.

This is what we agreed at WMO today, and if implemented, this issue can be closed.
