### ISSUE TITLE
New table 5-02-03: Measurement/observing method (ocean)

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#142]
The measurement/observing method for ocean observations are still missing at this point. It would be nice to collect suggestions from the community here.

Examples from other communities can be found here:
https://github.com/wmo-im/wmds/blob/master/tables_en/5-02-01.csv (atmosphere)
https://github.com/wmo-im/wmds/blob/master/tables_en/5-02-05.csv (terrestrial)

**Comment by nuneslf** [comment]
Perhaps it is also useful to refer to the current list of variables for ocean (code table 1-01-03):
https://github.com/wmo-im/wmds/blob/master/tables_en/1-01-03.csv

**Comment by joergklausen** [comment]
Hi @champikagallage can you please follow up on this? Thanks!

**Comment by joergklausen** [comment]
@champikagallage Any progress on this issue? To proceed, we need a proper proposal

**Comment by champikagallage** [comment]
Work is in progress but slow. We may need few more months to complete this.

**Comment by amilan17** [comment]
Champika presented the status and will be able to provide a ready version within a couple of weeks, however, the sea ice category may not be ready for FT2021-2.

**Comment by fstuerzl** [comment]
Issue forwarded to Ocean OPS team for suggestions.

**Comment by amilan17** [comment]
@fstuerzl did you forward THIS issue or the Issue that contains Champika's proposal? (#279)

**Comment by fstuerzl** [comment]
@amilan17, THIS issue.

Anthonin Lizé from OceanOPS responded as follows:
> We discussed this week with the team about this code table.
In short, this can be assimilated to what we call ‘sensor type’ in our system, which was not truly relevant until now. We have an embryo of what you could inspire the WIGOS code table from, available here: https://www.ocean-ops.org/api/preview/help/?param=sensortype. This includes both atmospheric and ocean values, we don’t split it.
If WIGOS defines a code table for it, we will study then the possibility to merge and adopt it.

**Comment by anthoninlize** [comment]
We initialized a starting list with @MKrieger29 , waiting from inputs from out colleagues to fill in the blanks and to give us contact points within the GOOS observing network communities (to list as stakeholders and to provide more inputs). We'll submit a proposal when we have something consolidated.

**Comment by amilan17** [comment]
@anthoninlize  @MKrieger29 -- do you have a status update for this issue? Or was a new issue submitted already?

**Comment by anthoninlize** [comment]
Hi @amilan17 ,
We've been working on this in the last few days, we have an initial list (not complete), based on what is done for other domains. We are still waiting inputs/feedback for other variables, not listed here. But that's a start, to discuss I guess.
The the sea surface temperature variable, some methods refer to the placement more so of the sensor, I don't know if it is appropriate in that list (if not, I'll remove them).


| notation     | path                                                                                   | name                                            | description                                                                                  |
|--------------|----------------------------------------------------------------------------------------|-------------------------------------------------|----------------------------------------------------------------------------------------------|
|              | \Ocean\Chlorophyll concentration\In situ\Fluorometer                                   | Fluorometer                                     | Fluorometer                                                                                  |
|              | \Ocean\Conductivity\In situ\XCTD                                                       | XCTD                                            | Expendable Conductivity Temperature Depth                                                    |
|              | \Ocean\Fluorescence (DOM)\In situ\Fluorometer                                          | Fluorometer                                     | Fluorometer                                                                                  |
|              | \Ocean\Fluorescence (DOM)\In situ\Fluorometer CDOM                                     | Fluorometer                                     | Fluorometer CDOM                                                                             |
|              | \Ocean\NO2- (nitrite)\In situ\Autoanalyzer NO2-                                        | Autoanalyzer NO2-                               | Autoanalyzer NO2-                                                                            |
|              | \Ocean\NO3- (nitrate)\In situ\Autoanalyzer NO3-                                        | Autoanalyzer NO3-                               | Autoanalyzer NO3-                                                                            |
|              | \Ocean\NO3- (nitrate)\In situ\Spectrophotometer                                        | Spectrophotometer                               | Spectrophotometer Nitrate Sensor                                                             |
|              | \Ocean\Ocean Current - Speed\In situ\ADCP                                              | ADCP                                            | Acoustic Doppler Current Profiler                                                            |
|              | \Ocean\Ocean Current - Speed\In situ\Current Profiler [general]                        | Current Profiler [general]                      | Profile of subsurface current (other than ADCP)                                              |
|              | \Ocean\Ocean Current - Speed\In situ\Electromagnetic Sensor                            | Electromagnetic Sensor                          | Electromagnetic Sensor                                                                       |
|              | \Ocean\Ocean salinity\In situ\CTD                                                      | CTD                                             | Conductivity Temperature Depth                                                               |
|              | \Ocean\Ocean salinity\In situ\Salinometer [general]                                    | Salinometer [general]                           | Salinometer [general]                                                                        |
|              | \Ocean\Ocean salinity\In situ\XCTD                                                     | XCTD                                            | Expendable Conductivity Temperature Depth                                                    |
|              | \Ocean\Ocean suspended sediments concentration\In situ\Sediment Trap                   | Sediment Trap                                   | Sediment Trap                                                                                |
|              | \Ocean\Ocean temperature\In situ\CTD                                                   | CTD                                             | Conductivity Temperature Depth                                                               |
|              | \Ocean\Ocean temperature\In situ\eXpendable BathyThermograph                           | eXpendable BathyThermograph                     | eXpendable BathyThermograph                                                                  |
|              | \Ocean\Ocean temperature\In situ\Thermometer [general]                                 | Thermometer [general]                           | Other sea water temperature sensor                                                           |
|              | \Ocean\Ocean temperature\In situ\XCTD                                                  | XCTD                                            | Expendable Conductivity Temperature Depth                                                    |
|              | \Ocean\Oxygen, dissolved\In situ\IDO                                                   | IDO                                             | Integrated Dissolved Oxygen Sensor, Clark-type electrode                                     |
|              | \Ocean\Oxygen, dissolved\In situ\Optode                                                | Optode                                          | Dissolved Oxygen Optode Sensor, optical sensor                                               |
|              | \Ocean\pH\In situ\pH sensor [general]                                                  | pH sensor [general]                             | pH Sensor                                                                                    |
|              | \Ocean\pH\In situ\Transistor pH sensor                                                 | Transistor pH sensor                            | Transistor pH sensor                                                                         |
|              | \Ocean\PO4= (phosphate)\In situ\Autoanalyzer PO4                                       | Autoanalyzer PO4                                | Autoanalyzer PO4                                                                             |
|              | \Ocean\Pressure\In situ\CTD                                                            | CTD                                             | Conductivity Temperature Depth                                                               |
|              | \Ocean\Pressure\In situ\XCTD                                                           | XCTD                                            | Expendable Conductivity Temperature Depth                                                    |
|              | \Ocean\Sea surface salinity\In situ\Salinometer [general]                              | Salinometer [general]                           | Salinometer [general]                                                                        |
|              | \Ocean\Sea surface temperature\In situ\Bait tanks thermometer                          | Bait tanks thermometer                          | Bait tanks thermometer                                                                       |
|              | \Ocean\Sea surface temperature\In situ\Bucket thermometer                              | Bucket thermometer                              | Bucket thermometer                                                                           |
|              | \Ocean\Sea surface temperature\In situ\Condenser intake or engine cooling system inlet | Condenser intake or engine cooling system inlet | Condenser intake on steam ships, or engine cooling system inlet on motor ships               |
|              | \Ocean\Sea surface temperature\In situ\Hull contact sensor                             | Hull contact sensor                             | Hull contact sensor                                                                          |
|              | \Ocean\Sea surface temperature\In situ\Immersed sea surface thermometer                | Immersed sea surface thermometer                | Immersed sea surface thermometer                                                             |
|              | \Ocean\Sea surface temperature\In situ\Radiation thermometer                           | Radiation thermometer                           | Radiation thermometer                                                                        |
|              | \Ocean\Sea surface temperature\In situ\Sea thermograph                                 | Sea thermograph                                 | Sea thermograph                                                                              |
|              | \Ocean\Sea surface temperature\In situ\Thermometer [general]                           | Thermometer [general]                           | Other SST                                                                                    |
|              | \Ocean\Sea surface temperature\In situ\Through hull sensor                             | Through hull sensor                             | Through hull sensor                                                                          |
|              | \Ocean\Sea surface temperature\In situ\Trailing thermistor                             | Trailing thermistor                             | Trailing thermistor                                                                          |
|              | \Ocean\SiO3= (metasilicate)\In situ\Autoanalyzer SiO3                                  | Autoanalyzer SiO3                               | Autoanalyzer SiO3                                                                            |
| inapplicable |                                                                                        | inapplicable                                    | None of the codes in the table are applicable in the context of this particular observation. |
| unknown      |                                                                                        | unknown                                         | The measurement/observing method is unknown.                                                 |

**Comment by amilan17** [comment]
@anthoninlize Thank you for the update. Please note that the descriptions should differ from the name such that they provide a basic definition.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22](https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22) notes: no discussion

**Comment by anthoninlize** [comment]
@amilan17 We will provide better description as soon as we can. 
Please note we did not receive today's call invitation, which anyway was clashing with another meeting for us.

**Comment by joergklausen** [comment]
I made a similar comment under #336: the path are not part of the code tables exposed through the codes registry. I have several issues with this issue:

1. There is no summary, no clear proposal, no stakeholders, etc. Please edit the first comment in this issue using the template for new issues. This helps the team to evaluate the issue.
2. Entries in this method table should not duplicate methods just because they can be used to observe several different quantities. It may the the right point in time now to abandon the path and use the tags, as has been done in other tables (but not in the registry itself, yet). 
3. If you want to specify instruments specifically, you can do that in OSCAR/Surface with the instrument catalogue. At this point, the instrument catalogue is not in scope of the WIGOS code tables.
4. The proposed entries are mostly just instrument types and do not name a 'method'. Example: 'Fluorometer' should be named 'Fluorometry' instead. The method is the principle of measurement realized in an instrument such as a fluorometer.
5. The description/definition needs to explain/define the name unambiguously, no repeat it. Example: 'Fluorometry' - 'measurement of emitted fluorescent light'.

**Comment by amilan17** [comment]
changing target milestone to FT2023-1

**Comment by anthoninlize** [comment]
Going back to this, preparing for tomorrow's call. This is still on-going, we had some delay (I'll detail tomorrow).

Here's a well formatted proposal template (content details still to be done). I can't edit the first comment, so here's the content:

# Initial request
The measurement/observing method for ocean observations are still missing at this point. It would be nice to collect suggestions from the community here.

# Amendment details
TBD, taking into account [Jörg's comments](https://github.com/wmo-im/wmds/issues/142#issuecomment-1132586522)

# Comments

# Requestor(s)
Should I put OceanOPS here? Since we need this to complete the output of marine-based measurements from our system to OSCAR/Surface

# Stakeholder(s)
OceanOPS (sync of metadata from GOOS to OSCAR/Surface)
GOOS networks: Argo, DBCP, SOT, OceanSITES, OceanGliders, etc.

# Publication(s)
Table 5-02-03

# Expected impact of change
MEDIUM

# Collaborators
OceanOPS technical coordinators
GOOS Observations Coordination Group

# References
Examples from other communities can be found here:
https://github.com/wmo-im/wmds/blob/master/tables_en/5-02-01.csv (atmosphere)
https://github.com/wmo-im/wmds/blob/master/tables_en/5-02-05.csv (terrestrial)

# Validation

**Comment by joergklausen** [comment]
I believe, this can be closed as the same is now moved forward in #422 (and a comment to this effect is part of that issue). Any additional methods, please open new issues.
