### ISSUE TITLE
Campbell Scientific SHM30 Snow Depth Sensor

### ISSUE THREAD

**Issue by stuartthompson1** [wmo-im/wmds#154]
The UK Met Office have these Snow Depth Sensors in the Network.

https://www.campbellsci.com.au/shm30

They use an eye safe laser light to determine the snow depth. But when I deploy one, the only option I can find for the Observing Method is ‘(Ultra)sonic ranger’.

Please can an Observing Method of 'visible eye-safe laser light' be added to this sensor.

Many thanks
Stuart

**Comment by rodicanitu** [comment]
Stuart et al: two comments:
1. the operationally used methods of observation for snow depth will be submitted for final review, for inclusion in the WIGOS Metadata Standard within the next 3-4 weeks, nad we should address these issues. action of GCW
2. on the specific entry: SHM30 (manufactured by Lufft/Jenoptiks) is a class 2 (eye-safe) laser emitting sensor acting as a distance meter. - this may not be in the tables today (thus, see #1).
the ultrasonic ranger sensor is model SR50 (and its many versions) manufactured by Campbell Scientific.

**Comment by stuartthompson1** [comment]
Thank you

Stuart

Stuart Thompson RMet
Land Networks Data Analyst
Skype: 03301352489 Mobile: 07900 160672
E-mail: stuart.thompson@metoffice.gov.uk<mailto:stuart.thompson@metoffice.gov.uk> http://www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

See our guide to climate change at www.metoffice.gov.uk/climate-change/guide.
Our magazine Barometer is now available online at www.metoffice.gov.uk/barometer.

[WeatherReady_email sig_winter]

Catch up with the latest #WeatherStory- http://www.metoffice.gov.uk/news/weatherstory

**Comment by joergklausen** [comment]
addressed in #155
