### ISSUE TITLE
Inconsistency in location of variables and observing methods for snow

### ISSUE THREAD

**Issue by luciacap** [wmo-im/wmds#155]
Observed variable "snow depth" (and similar) is listed under table "Observed variable - measurand (**terrestrial**)". 
[http://codes.wmo.int/wmdr/ObservedVariableTerrestrial](url)
The corresponding observing method "(Ultra)sonic ranger" or "gradiated pole" is listed under table "Measurement/observing method (**atmosphere**)"
http://codes.wmo.int/wmdr/ObservingMethodAtmosphere

**Comment by IgorZahumensky** [comment]
Not in under http://codes.wmo.int/wmdr/_ObservedVariableTerrestrial ?
The http://codes.wmo.int/wmdr/ObservedVariableTerrestrial seems to be broken (?)

**Comment by lijuan-ma** [comment]
GCW experts realized this inconsistency and had a discussion before Cg-18. As a new part of CIMO-GUIDE (WMO-No.8), Cg-18 endorsed the MEASUREMENT OF CRYOSPHERIC VARIABLES*, in which observing methods are recommended. GCW PO would follow up this issue and come back with an recommendation on snow measuring methods and directory to it.

**Comment by lijuan-ma** [comment]
As clarified by Luis and Rodica, this is a matter of table management. So, we left WIGOS PO/OSCAR team to deal with it.

**Comment by fierz** [comment]
I truly think methods and observations should follow the same tree structure. Snow on the ground was moved to terrestrial observations, so should the methods too. Be consistent!

**Comment by joergklausen** [comment]
As I read this, the specific request is as follows:
Move the following entries from table 5-02-01 to table 5-02-05:

260,\Atmosphere\Precipitation\In situ\Snow\(Ultra)sonic ranger,(Ultra)sonic ranger,
261,\Atmosphere\Precipitation\In situ\Snow\Gradiated pole,Gradiated pole,
262,\Atmosphere\Precipitation\In situ\Snow\Snow pillow,Snow pillow,

The resulting entries in table 5-02-02 will read:
260,\Terrestrial\Remote-sensing, active\Snow\(Ultra)sonic ranger,(Ultra)sonic ranger,
261,\Terrestrial\In situ\Snow\Gradiated pole,Gradiated pole,
262,\Terrestrial\In situ\Snow\Snow pillow,Snow pillow,

@lijuan-ma @fierz We need you to confirm that this is actually the request. If so, I do support it, and implementation in OSCAR/Surface would be straight-forward. If it is not, then please be more specific.

**Comment by fierz** [comment]
@joergklausen @lijuan-ma
Yes, this is the request 👍 
Just make sure the backslash between Snow and (Ultra)sonic ranger is not missing in entry 260

**Comment by joergklausen** [comment]
@fierz @steingod Would you be willing to write a validation report for this?

**Comment by fierz** [comment]
@joergklausen @godoy : OK, I can do it on Monday. Unfortunately, I will be unable to jin the next TT-WMD telecon (overlap with another meeting)

**Comment by fierz** [comment]
[wmds-20200518_validationReport-155-obsMethSnow-v0.1.docx](https://github.com/wmo-im/wmds/files/4645113/wmds-20200518_validationReport-155-obsMethSnow-v0.1.docx)
Review requested from @luciacap, @steingod, @joergklausen, @lijuan-ma, Rodica Nitu, Craig Smith (by e-mail)

**Comment by KarlBureau** [comment]
@fierz to check that these methods are not required in the atmospheric domain .

**Comment by rodicanitu** [comment]
1. SMH30 (using laser beam) is not a Campbell Scientific sensor. It might have been sold through them, but it was manufactured by Luft/Jenoptik, currently discontinued. i recommend that this entry is updated to eavoid confusion. 
Campbell products are either the SR50 range of products (ultrasonic rangers) or the newer SDMS40 (laser) 
2. The (ultra)sonic sensors are used for snow depth and the same technology could be used for water levels, as it's a distancemeter, in essence.  Not used for atmospheric variables.
i could help with the validation report.

**Comment by joergklausen** [comment]
Thank you @fierz for this validation report. To me, the changes proposed make sense. I have no strong feelings about the choice of term 'sonic instrument' vs '(ultra)sonic ranger', although the latter term appears to be more precise. Please conclude the report as v1.0 with the final term of choice once you decide.
@rodicanitu The specific instruments are not part of a WMDR code table, but of the OSCAR/Surface instrument catalogue. It would be much appreciated if you could go through this catalogue and add missing instruments in use.

**Comment by steingod** [comment]
@fierz sorry for the delay, looks good to me.

**Comment by fierz** [comment]
[wmds-20200528_validationReport-155-obsMethSnow-v1.0.docx](https://github.com/wmo-im/wmds/files/4694238/wmds-20200528_validationReport-155-obsMethSnow-v1.0.docx)
Amended report according to feedback from telecon Nr. 11 and received by email. 
Review requested from @luciacap, @steingod, @joergklausen

**Comment by amilan17** [comment]
(copied from wmds-20200528_validationReport-155-obsMethSnow-v1.0.docx)

**Conclusion and Recommendation**
It is recommended to move the existing entries from table 5-02-01 to table 5-02-05, rename them as needed, adapt the paths, add definitions, and add one new entry to table 5-02-05 (http://codes.wmo.int/wmdr/ObservingMethodTerrestrial) as follows:


Notation | Name | Path | Definition
-- | -- | -- | --
260 | Ultrasonic   ranging | \Terrestrial\Snow   depth\In situ\ | Transmission of   an ultrasonic pulse towards the target and listening for a return echo from   that target.
?? | Laser   ranging | \Terrestrial\Snow   depth\In situ\ | Emission of a   modulated beam of light in the visible spectrum to determine the distance to   a target by comparing the phase information from the reflected beam.
261 | Graduated[SCBD1]  device | \Terrestrial\Snow   depth\In situ\ | Manual   measurement or observation made with a graduated fixed stake, a sturdy ruler,   or an extendible graduated rod.
262 | Snow pillows and snow scales | \Terrestrial\Water   equivalent of snow cover\In situ\ | Weighing of snow-cover mass per unit area.

**Comment by efucile** [comment]
@steingod @fierz @joergklausen I notice here that you are asking to replace the following URI
https://codes.wmo.int/wmdr/ObservingMethodAtmosphere/262
with the following URI
https://codes.wmo.int/wmdr/ObservingMethodTerrestial/262

First of all, we cannot replace a URI with another URI, we can deprecate one and create the new one. However, we have to remember that a URI is supposed to be permanent and deprecation is to be used only in extreme situations to resolve problems or errors. I am not sure that this is the case.

I have to say that the validation report is not validating the required change as it is not clearly stating that there is a deprecation process to be performed and more important is not checking that the new URI does not exist already.

**Comment by joergklausen** [comment]
Hmm … how do you suppose we proceed? What I can say for sure is that the new URI does yet exist, because the number at the end (the notation) comes from just one large table that contains all the observed variables. If the path leading up to the variable (\Atmosphere\… vs \Terrestrial\…) is changed, this has no effect on OSCAR/Surface. We are in fact in a process of correcting errors here. At this stage, when these entries in the code lists have not yet been used (much), and the request comes from the community concerned, I think we can/need to be pragmatic.

**Comment by fierz** [comment]
@fucile 

> If the path leading up to the variable (\Atmosphere\… vs \Terrestrial\…) is changed, this has no effect on OSCAR/Surface.

Thus, if I interpret @joergklausen 's comment correctly, what we are doing here is making the paths for snow variables and methods consistent without prejudice for OSCAR/Surface. The snow variables were already moved from \Atmosphere\… vs \Terrestrial\… without deprecation process as far as iI know. Thus it makes no sense to me to keep the methods under \Atmosphere\… and confuse the users of the OSCAR/Surface GUI when entering data.

**Comment by efucile** [comment]
@fierz and @joergklausen 
I was not clear enough in my previous post. We are not discussing here the change, we are discussing its implementation. We cannot just replace 
https://codes.wmo.int/wmdr/ObservingMethodAtmosphere/262
with the following URI
https://codes.wmo.int/wmdr/ObservingMethodTerrestial/262
we can deprecate 
https://codes.wmo.int/wmdr/ObservingMethodAtmosphere/262
and define
https://codes.wmo.int/wmdr/ObservingMethodTerrestial/262

The deprecated URI will not be used by OSCAR/surface and it will never be assigned in the future to another variable. This is a basic principle of management of persistent identifiers. I would remind you that the FAIR principles that are frequently in the data and metadata domain state 
F1. (meta)data are assigned a globally unique and eternally persistent identifier. https://www.force11.org/group/fairgroup/fairprinciples

We cannot just delete a persistent identifier, this is not supported by the software supporting codes.wmo.int to prevent users to delete URI after releasing them.

**Comment by amilan17** [comment]
@joergklausen -- provide notation for laser ranging.

**Comment by joergklausen** [comment]
@amilan17 The notation for 'Laser ranging' will be 344.

There is actually a mistake in the validation report: the following methods are remote-sensing methods, not in situ methods:
260 | Ultrasonic   ranging | \Terrestrial\Snow depth\In situ\
?? | Laser   ranging | \Terrestrial\Snow depth\In situ\
The correct entries should read as follows:
260 | Ultrasonic ranging | \Terrestrial\Snow depth\Remote-sensing, active\
344 | Laser ranging | \Terrestrial\Snow depth\Remote-sensing, active\
@fierz Please confirm that you agree.

@amilan17 Please correct the branch accordingly.

**Comment by rodicanitu** [comment]
@joergklausen : I'm not sure why you are referring to these methods as remote sensing; 
both are in-situ, as noted in the validation report. @fierz is currently on leave. i recommend that @amilan17 does not change the branch and keeps it as per validation report.

**Comment by joergklausen** [comment]
@rodicanitu Both, ultrasonic ranging and laser ranging probe the distance from a sensor to the snow surface remotely. At least laser ranging can potentially also be used from aircraft. These are clearly remote-sensing methods. They are active methods because you emit either ultrasound or laser light to probe the surface and determine the time it takes for the pulse to return to the sensor. This is different from a passive method like an IR sounder, where the signal is emitted by some other source. These methods are different from an in situ observation where your ruler is buried in the snow and you read it.

**Comment by rodicanitu** [comment]
@joergklausen agree in principle, but disagree in the particular case. All in-situ snow depth automatic instruments are either ultrasonic or laser ranging, generally installed at about 2 m above the ground surface. some may be used for other in-situ distance measurements (e.g. water levels). The entries proposed refer to those instruments. these go beyond the old snow ruler.
 if the terms used appear confusing in a broader sense, perhaps this should be addressed, but the methods are valid and widely used, operationally.

**Comment by joergklausen** [comment]
@rodicanitu I am glad you agree in principle ;-). Well, here's the way out: we don't make a particular distinction in this case between in situ vs remote-sensing. The number of methods is anyway limited, and users will have no difficulty navigating to and finding the right one. The suggestion would then simply be:
260 | Ultrasonic ranging | \Terrestrial\Snow depth\
344 | Laser ranging | \Terrestrial\Snow depth\

**Comment by rodicanitu** [comment]
@joergklausen thank you for the suggestion; I'm in support of this approach.

**Comment by fierz** [comment]
@joergklausen @rodicanitu @steingod @efucile Perfect compromise and good, pragmatic solution. I concur.


> The deprecated URI will not be used by OSCAR/surface and it will never be assigned in the future to another variable.

I also agree with the proposed deprecation of the old URIs and GCW will carefully consider this issue in future.

**Comment by amilan17** [comment]
@joergklausen @rodicanitu @steingod -- Do you also want the term 'in situ' removed from the hierarchy in 261 and 262? 

- 260,\Terrestrial\Snow depth\Ultrasonic ranging,Ultrasonic ranging,Transmission of an ultrasonic pulse towards the target and listening for a return echo from that target.
- 261,\Terrestrial\Snow depth\In situ\Graduated[SCBD1] device,Graduated[SCBD1] device,"Manual measurement or observation made with a graduated fixed stake, a sturdy ruler, or an extendable graduated rod."
- 262,\Terrestrial\Water equivalent of snow cover\In situ\Snow pillows and snow scales,Snow pillows and snow scales,Weighing of snow-cover mass per unit area.
- 144,\Terrestrial\Snow depth\Laser ranging,Laser ranging,Emission of a modulated beam of light in the visible spectrum to determine the distance to a target by comparing the phase information from the reflected beam.

**Comment by joergklausen** [comment]
@amilan17 Please note, it is 344, not 144 for the Laser ranging.
@fierz I would suggest to drop the 'in situ' from all variables here for consistency. Please decide and let Anna know.

**Comment by fierz** [comment]
@amilan17 @rodicanitu Yes, for the sake of consistency, please drop the 'in situ' for all variables. Thanks!

**Comment by amilan17** [comment]
@fierz @joergklausen  --Will you please review the following branches to makes sure that requested changes are ready for Fast Track?

Note, in the Codes Registry, the terms removed from the ObservingMethodAtmosphere table will be treated as superseded by the terms in the ObservedMethodTerrestrial table. 

https://github.com/wmo-im/wmds/blob/issue-155/tables_en/5-02-05.csv
https://github.com/wmo-im/wmds/blob/issue-155/tables_en/5-02-01.csv

**Comment by joergklausen** [comment]
@amilan17 @fierz The only thing I note is the strange name 'Graduated[SCBD1] device'. If that is on purpose, I am okay with these changes.

**Comment by fierz** [comment]
@amilan17 please drop 'in situ' from annotation 262 too, otherwise fine with me
@joergklausen Yes, 'graduated device' is on purpose as it is the term we use in WMO-No. 8, Vol II, for stakes, rulers, and rods.

**Comment by joergklausen** [comment]
@fierz My concern is not with 'graduated device', which is fine, but with 'Graduated[SCBD1] device'. What is the [SCBD1]? Is that there on purpose?

**Comment by fierz** [comment]
@joergklausen Sorry for the misunderstanding and not noticing this [SCBD1] earlier on. It has no meaning and is a consequence of a cut and paste action out of the validation report (Word document). @amilan17 Thus it should be deleted.

**Comment by amilan17** [comment]
Thanks. Changes have been made to the branch: https://github.com/wmo-im/wmds/blob/issue-155/tables_en/5-02-05.csv

**Comment by amilan17** [comment]
Confirmed that it's ready for FT.

**Comment by amilan17** [comment]
Approved by FT 2020-2
