### ISSUE TITLE
5-02-05 on codes.wmo.int/wmdr

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#156]
http://codes.wmo.int/wmdr/_ObservingMethodTerrestrial
Name and Description has a typo: Measurement/observing method (terres*rial) that should be fixed

**Comment by IgorZahumensky** [comment]
terres*rial

**Comment by joergklausen** [comment]
Fixed

**Comment by KarlBureau** [comment]
I don't understand why this has been returned to "in validation"?

**Comment by joergklausen** [comment]
@IgorZahumensky This has already been fixed on http://codes.wmo.int/wmdr (cf. my comment above), so I also don't understand why the issue has been re-opened.

**Comment by IgorZahumensky** [comment]
@efucile: 
for your evidence of what ToBeDone/Solved, please close this issue and there is no need for Fast Track;
