### ISSUE TITLE
WMDS Workflow

### ISSUE THREAD

**Issue by IgorZahumensky** [wmo-im/wmds#160]
![wmds_github_workflow_v0 1](https://user-images.githubusercontent.com/54841299/79228344-8c5c2d00-7e61-11ea-8ea9-8bb7b46f1fe3.png)

**Comment by toakley76** [comment]
Makes sense to me. Might need to define what we mean by consensus? I think we agreed that no comment from a TT-WMD Member by default accepts the proposal. Assuming that there is a resolution proposed.

**Comment by KarlBureau** [comment]
The review/comment/propose resolution stage may need other experts to be consulted for feedback. But the process seems logical and clear, and I aligns with the stream lanes that are visible in the github project space.

**Comment by IgorZahumensky** [comment]
Is there any need to keep it under "Submitted" or it can be moved under "In progress" OR ...

**Comment by efucile** [comment]
@IgorZahumensky I don't think that this is part of the project board. We need to process it in a different way. The project board is only for updates to the codelists.

**Comment by efucile** [comment]
The workflow cannot be accepted at the moment as the teams ToRs are under review. It will be for the future team to discuss the process again. For the moment we need to focus on delivering for the next fast track and the project lanes are enough for the purpose. I would suggest to leave it open and we will rise it at the first meeting of the new team.

**Comment by joergklausen** [comment]
Archive contains diagram in .bpmn format 
[wmds_github_workflow.ZIP](https://github.com/wmo-im/wmds/files/4734777/wmds_github_workflow.ZIP)
