### ISSUE TITLE
2-02 Programs/networks: new additions to GOOS/DBCP

### ISSUE THREAD

**Issue by anthoninlize** [wmo-im/wmds#161]
Hello all,

A few additions to this code list:

* \Co-sponsored\GOOS\DBCP\NAVOCEANO DBCP

* \Co-sponsored\GOOS\DBCP\SAWS DB
South African Weather Service Drifting Buoys
thanks & best
anthonin

**Comment by joergklausen** [comment]
@anthoninlize Please include this in your report on #157 .

**Comment by anthoninlize** [comment]
Report added there : https://github.com/wmo-im/wmds/issues/157
