### ISSUE TITLE
1-01 Observed variable-measurand: introduce Cryosphere in path

### ISSUE THREAD

**Issue by fierz** [wmo-im/wmds#163]
In Code Table 1-01 all cryosphere variables are preceded by _**Snow / Ice / Glacier**_ (see attached). Replacing the above by _**Cryosphere**_ would not only make much sense but also facilitate the search for cryosphere variables when adding a new measurement program in OSCAR/surface (see attached).

This name change affects one path in 1-01-03 (ObservedVariableOcean), namely Ocean > Snow / Ice / Glacier > Ice as well as three paths in 1-01-05 (ObservedVariableTerrestrial), namely Lake > Snow / Ice / Glacier > Ice, Land surface > Snow / Ice / Glacier > Ice, and River > Snow / Ice / Glacier > Ice.

![03-Screenshot 2020-04-21 at 15 03CEST](https://user-images.githubusercontent.com/13619513/79874890-30f1e800-83e9-11ea-8fdd-a13f5c349e59.png)

**Comment by fierz** [comment]
Above issue is related to #164 and #163 
Furthermore, the changes do not imply any change in the tree/path structure but _**only**_ a renaming.

**Comment by joergklausen** [comment]
Further discussion of this under #165.
