### ISSUE TITLE
1-01-03 Observed variable - measurand (ocean): change Ice to Sea ice in path

### ISSUE THREAD

**Issue by fierz** [wmo-im/wmds#164]
In 1-01-03 the path leading to sea ice variables is _**Ocean > Snow  / Ice / Glacier > Ice**_ (see attached). However, ice is not a component of the cryosphere as such and I would suggest to replace it by _**Sea ice**_ (if possible without dash)
Note that Global Cryosphere Watch will also recommend variables for the cryosphere component _Ice shelves_, which makes the proposed change even more  meaningful.

Related to #163 

![03-Screenshot 2020-04-21 at 15 03CEST](https://user-images.githubusercontent.com/13619513/79876536-744d5600-83eb-11ea-9f1d-842566c2175e.png)

**Comment by fierz** [comment]
Note that the change above should also include the one proposed in issue #163

**Comment by joergklausen** [comment]
Further discussion of this under #165.
