### ISSUE TITLE
1-01-05 & 1-01-03 Observed variable - measurand (terrestrial): replace ice in path to cryo-variables

### ISSUE THREAD

**Issue by fierz** [wmo-im/wmds#165]
In 1-01-05 three paths contain _Ice_ (see attached). Ice not being a component of the cryosphere #164 , I would suggest to make the following replacements that allow to use the proper name of the corresponding component:
_Lake > Snow / Ice / Glacier > Ice_ to _Lake > Cryosphere > **Lake ice**_
_Land surface > Snow / Ice / Glacier > Ice_ to _Land surface > Cryosphere > **Ice sheet**_
_River > Snow / Ice / Glacier > Ice_ to _Lake > Cryosphere > **River ice**_

Note that the change above already includes the one proposed in issue #163 

![04-Screenshot 2020-04-21 at 15 05CEST](https://user-images.githubusercontent.com/13619513/79877690-d8244e80-83ec-11ea-9e6b-89a5cde9cdf2.png)
![05-Screenshot 2020-04-21 at 15 05CEST 1](https://user-images.githubusercontent.com/13619513/79877693-d9ee1200-83ec-11ea-98a6-38bf4de6112d.png)

**Comment by joergklausen** [comment]
Validation report prepared and sent to @fierz and o.godoy@met.no for approval; also attached here.
The report also addresses #123 , #163 , #164.
[WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.1.docx](https://github.com/wmo-im/wmds/files/4557798/WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.1.docx)

**Comment by lijuan-ma** [comment]
There were five glacier variables submitted by GCW and agreed by TT-WMD. The four you mentioned in the validation report are new to WMDR. The fifth was **_glacier area_**, which was recommended to replace **_glacier cover_** in WMDR.

**Comment by fierz** [comment]
@joergklausen @efucile @IgorZahumensky : Øystein and myself did look at the proposal regarding the hierarchy of observed variables and fully support it. The additional reversal of hierarchy, e.g. “Terrestrial > Cryosphere > Lake > Lake ice > …” not only further simplifies the structure but makes it also more logical and easier to use from a computer perspective.
I also support Lijuan's comment above and proposed a corresponding change to Jörg's proposal.

**Comment by joergklausen** [comment]
[WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.2.docx](https://github.com/wmo-im/wmds/files/4580319/WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.2.docx)

**Comment by joergklausen** [comment]
Final draft of validation report after TT-WMD Telco on 2020-05-05.
[WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.3.docx](https://github.com/wmo-im/wmds/files/4583037/WMDS_Validation_Report_123_163_164_165_Cryosphere_v0.3.docx)
Requesting formal approval from @fierz and @steingod.

**Comment by steingod** [comment]
I support this.

**Comment by fierz** [comment]
I approve the final draft of the validation report.

**Comment by amilan17** [comment]
Branch: https://github.com/wmo-im/wmds/blob/165/tables_en/1-01-05.csv

**Comment by amilan17** [comment]
@fierz -- I think so, please verify by reviewing these two tables in the branch: 

https://github.com/wmo-im/wmds/blob/issue-165/tables_en/1-01-03.csv
https://github.com/wmo-im/wmds/blob/issue-165/tables_en/1-01-05.csv

**Comment by fierz** [comment]
@amilan17 -- Thanks again Anna. Just perfect!

**Comment by efucile** [comment]
@joergklausen changing name of glacier cover to glacier area is not possible. This is a complete change of meaning and units for an element that is already defined here https://codes.wmo.int/wmdr/ObservedVariableTerrestrial/610 we can add another element glacier area, but we cannot completely change the meaning of something that is already defined.

**Comment by amilan17** [comment]
1. Added Glacier area to the table and assigned it the notation of 12013. Please let me know if there is a different notation preferred. 

12013 | \Terrestrial\Cryosphere\Glacier\Glacier area | Glacier area | Area enclosed by the projection of the glacier outline onto the surface of an ellipsoid approximating the surface of the Earth or onto a planar horizontal approximation to that ellipsoid. The glacier area excludes nunataks but includes debris-covered parts of the glacier. The glacier outline separates the glacier from unglacierized terrain and from contiguous glaciers. 

2. Modified 610 back to it's original form, almost. 

610 | \Terrestrial\Cryosphere\Glacier\Glacier cover | Glacier cover | Fraction of a land area covered by permanent ice.

**Comment by joergklausen** [comment]
@efucile I disagree that 

> @joergklausen and @fierz changing name of glacier cover to glacier area is not possible. This is a complete change of meaning and units for an element that is already defined here https://codes.wmo.int/wmdr/ObservedVariableTerrestrial/610 we can add another element glacier area, but we cannot completely change the meaning of something that is already defined.

@efucile I agree that the meaning of terms in code lists must not change. But this is not what is proposed in this case. The meaning doesn't change at all, the (new) name for this element in the code table corrects an incorrect name as indicated by the relevant domain experts (@fierz). Moreover, this (new) name is the one used in the operational OSCAR/Surface system already. Finally, there is only one station where this variable is used.  

@amilan17 You should not assign notations to variables if these are numbers. This risks a clash with OSCAR/Surface, I am afraid. These numbers correspond to the internal ids and are assigned automatically. Once created in OSCAR/Surface, the notation can be communicated very quickly.

**Comment by joergklausen** [comment]
> @fierz -- I think so, please verify by reviewing these two tables in the branch:
> https://github.com/wmo-im/wmds/blob/issue-165/tables_en/1-01-03.csv
> https://github.com/wmo-im/wmds/blob/issue-165/tables_en/1-01-05.csv

Careful, there is another branch https://github.com/wmo-im/wmds/blob/165/tables_en/1-01-05.csv where the changes have not been correctly made!!

**Comment by fierz** [comment]
@efucile  I fully agree with @joergklausen. 

> @efucile I agree that the meaning of terms in code lists must not change. But this is not what is proposed in this case. The meaning doesn't change at all, the (new) name for this element in the code table corrects an incorrect name as indicated by the relevant domain experts (@fierz). Moreover, this (new) name is the one used in the operational OSCAR/Surface system already. Finally, there is only one station where this variable is used.

That GCW can propose new names and definitions for variables to OSCAR/surface is the agreement we have (my understanding). In fact, this already happened for snow variables and makes sense. These changes have been proposed by experts in the field and I am personally not aware of 'glacier cover' be used anywhere for surface measurements. The change will help avoid confusion by having one correctly named and defined variable.

If this is no longer the way we should work we would need to discuss it again at the level of GCW and WIGOS.

**Comment by efucile** [comment]
Dear
@fierz and @joergklausen 
thank you for your answers I realise that I was not clear in my previous post. I want to clarify that we are not discussing the decision to replace gacier cover with gacier area. This is a decision that has been taken by the team on the basis that the team has the domain expertise to propose the correct term. However, we need to decide how to make a change in codes.wmo.int which is providing **permanent** identifiers to terms that are used in the WIGOS metadata representation.

I understand that we want to replace
\Terrestrial\Cryosphere\Glacier\Glacier cover | Glacier cover | Fraction of a land area covered by permanent ice

with

\Terrestrial\Cryosphere\Glacier\Glacier area | Glacier area | Area enclosed by the projection of the glacier outline onto the surface of an ellipsoid approximating the surface of the Earth or onto a planar horizontal approximation to that ellipsoid

The fact is that we are replacing a fraction of area with an area. The definition is different and the variable is different. In this case we have two options on how to implement the change
1. we deprecate glacier cover and define glacier area as a new entry in the registry
2. we leave glacier cover without any use in OSCAR/surface and we define glacier area to be used in OSCAR/surface

**Comment by amilan17** [comment]
Current solution in the branch implements option #2 proposed by Enrico. "we leave glacier cover without any use in OSCAR/surface and we define glacier area to be used in OSCAR/surface".

**Comment by amilan17** [comment]
Based on the conversation with @joergklausen, this is merely fixing a mistake and it should have been addressed back when the term was experimental.

**Comment by amilan17** [comment]
https://codes.wmo.int/wmdr/ObservedVariableTerrestrial/_610:1

**Comment by fierz** [comment]
> * we deprecate glacier cover and define glacier area as a new entry in the registry
> * we leave glacier cover without any use in OSCAR/surface and we define glacier area to be used in OSCAR/surface

Both approaches are OK with me as long as _glacier cover_ will no longer be used. If solution 2 is implemented, let's go with it.

**Comment by amilan17** [comment]
@fierz -- Thank you for the confirmation. @joergklausen -- Can you assign a new notation value for glacier area?

**Comment by joergklausen** [comment]
@fierz The notation remains the same (610), this is a correction of the term only.

**Comment by amilan17** [comment]
@joergklausen -- to provide clarification, we need to keep 'glacier cover' in the list with the notation of 610 and add add 'glacier area' with a new notation

**Comment by joergklausen** [comment]
@amilan17 I don't understand … why do you still want to keep glacier cover under 610? Didn't we agree that this is a fix of something that should have been fixed already before? OSCAR/Surface uses 610 for glacier area and doesn't have glacier cover anymore. If you insist, then we will have to change glacier area to glacier cover in OSCAR/Surface and introduce a new variable altogehter for glacier are. This is what we agreed not to do, or am I wrong?

**Comment by fierz** [comment]
@amilan17 I agree with @joergklausen that this should be a fix only, to be consistent with OSCAR/Surface, which reflects GCW's original proposal. Thus having 'glacier area' under 610 would be the best solution indeed.

**Comment by efucile** [comment]
@joergklausen and @fierz there are very important rules that need to be followed in the management of a metadata standard. One is that as you define one term you cannot change it. The codes registry is a repository of permanent identifiers to terms. The stewardship of the codes registry requires to be rigorous in this respect. We had already this problem several times of an application driving the standard and this has to stop at a given point. It is the reverse. You first define the metadata standard and then implement in the application (OSCAR) if a change is made in the standard the application shall follow and implement it. We never had in any of our data and metadata standard a term changed to something else. This would be the first time. I am worried that many other cases like this are coming in the future and we cannot afford bad management of the standard. Why OSCAR/surface cannot be changed and use another number in place of 610?

**Comment by amilan17** [comment]
@joergklausen - confirmed that we can assign a new notation for glacier area. It is 12013.

**Comment by fierz** [comment]
@efucile (@joergklausen @amilan17)  
> Why OSCAR/surface cannot be changed and use another number in place of 610?
Mira - if you want so. But then 610 needs to be deprecated as otherwise we don't follow the original GCW proposal to WMDS (please check with the GCW PO @rodicanitu @lijuan-ma)

**Comment by joergklausen** [comment]
@fierz Hi Charles, there may a misunderstanding. 610 will be superseded by 12013, any attempts to use 610 will be re-directed to 12013. So, effectively, 610 will be deprecated and can no longer be used. The only term that ought to be used in future is 12013 (glacier area).

**Comment by fierz** [comment]
@joergklausen Thanks for the valuable precision Jörg. This is even better than I sought indeed. Perfect!

**Comment by amilan17** [comment]
Accepted during FT2020-2.
