### ISSUE TITLE
5-02-01 Methods (atmosphere) - typo

### ISSUE THREAD

**Issue by fierz** [wmo-im/wmds#166]
In the registry [http://codes.wmo.int/wmdr/ObservingMethodAtmosphere
](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere) (table 5-02-01) there is a typo in entry notation 201, Thermocouple, thermophile:
'_thermophile_' should read '**thermopile**'

**Comment by joergklausen** [comment]
@efucile @amilan17 Can this typo please be corrected without the overhead of a validation report and branch?

**Comment by amilan17** [comment]
Fixed typo in this branch: 
https://github.com/wmo-im/wmds/blob/issue-166/tables_en/5-02-01.csv

**Comment by fierz** [comment]
I φιλέω it. Thanks.

**Comment by joergklausen** [comment]
Fine by me.

**Comment by amilan17** [comment]
Ready for FT.

**Comment by IgorZahumensky** [comment]
@amilan17: if ready for fast-track, then the label FT should be there if I am right

**Comment by amilan17** [comment]
@IgorZahumensky -- thanks!

**Comment by amilan17** [comment]
Approved by FT 2020-2
