### ISSUE TITLE
New variables for the codetable 1-01-01.csv

### ISSUE THREAD

**Issue by richard-olav** [wmo-im/wmds#169]
I am not able to find the representations for the variables below in the codetable 1-01-01.csv Observed variable - measurand (atmosphere):

EBAS variable name, cf_name,matrix
calcium,mass_concentration_of_calcium_in_pm10_minus_pm1_in_air,pm10_pm1
calcium,mass_concentration_of_calcium_in_pm10_minus_pm2p5_in_air,pm10_pm25

Could they be added?

**Comment by IgorZahumensky** [comment]
@joergklausen - ditto as 168

**Comment by joergklausen** [comment]
Franziska: needs a Proposal and Reason, and branch with new entries along the lines of what we already have. It is clear that we will review the structure of the table more holistically, but adding new variables is more achievable right now.

**Comment by fstuerzl** [comment]
**Summary and Purpose**
Addition of variables for calcium in code table 1-01-01 (Observed variable - atmosphere) 

**Proposal**
Include the following variables in code table 1-01-01.csv

Label | Description | Path
-- | -- | --
Calcium  (Ca++), PM10-PM1, in air | Mass concentration   of calcium in PM10-PM1 in air | \Atmosphere\Aerosol\Composition\Inorganic   cations\Calcium  (Ca++), PM10-PM1, in   air
Calcium  (Ca++), PM10-PM2.5, in air | Mass concentration   of calcium in PM10-PM2.5 in air | \Atmosphere\Aerosol\Composition\Inorganic   cations\Calcium  (Ca++), PM10-PM2.5, in   air

**Reason**
Missing entries in variable list, required by @richard-olav

**Comment by fstuerzl** [comment]
Branch: https://github.com/wmo-im/wmds/tree/Issue169
View differences: https://github.com/wmo-im/wmds/commit/a15a30cd003b8c14f8ca675229c6752c5c3c664b#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d
Notation to be added.

**Comment by fstuerzl** [comment]
Path structure and variable modifiers depend on #173 and #181.

**Comment by markusfiebig** [comment]
@fstuerzl, I'm a little confused about the proposed names. Just before Christmas, we had a telecon where we found ways to store modifiers like PM1, PM10, etc. in WMDS elements outside the variable name to prevent the list of variables from blowing up. We also agreed that the way forward would be to store these modifiers not in the variable names, but other places in the metadata record. If we now define names that include modifiers, we are locked in, or we need to change them again very soon. I would propose to leave these out.

**Comment by fstuerzl** [comment]
@markusfiebig, I agree that with the changes, we discussed, these variables will be obsolete. I am however not sure how long it will take until a new approach to store modifiers is approved and implemented. Therefore I think, it needs to be discussed, whether it makes sense to add the variables @richard-olav requested for now if they are needed urgently. 
The same applies to issue #168 and #169.

**Comment by richard-olav** [comment]
@fstuerzl, for me, there is no urgent need for these specific variables. So I agree with you and Markus that it could wait until the new approach related to storing modifiers is approved and implemented. This would then also be the case for issue #168 and #170. Thanks.

**Comment by gaochen-larc** [comment]
@fstuerzl @markusfiebig I agree with both of you.   Thanks!

**Comment by fstuerzl** [comment]
@richard-olav, @gaochen-larc, @markusfiebig, thanks for your reviews! In this case issues #168, #169, #170 can be closed.
