### ISSUE TITLE
amendments to 1-02

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#17]
Table 1-02 was taken from Manual on Codes (WMO No. 306 Vol I.2 Common Code-table C-6 List of units for TDCFs.) which can be found here: http://codes.wmo.int/common/unit.

There is a need to amend this table with some more derived units such as ppb, ppm etc. 
@efucile How can this be done?

**Comment by nuneslf** [comment]
@joergklausen @efucile I think we should add table 1-02 to the Github and submit it as is; The issue of adding the missing units now or later via discussion with IPET-CM(?) could stay open.

**Comment by joergklausen** [comment]
It would be good to include the derived units that EMEP is missing from this table.
@nina: please contact Markus for the list. @Markus: I am away from office w/o laptop, so I can’t dig out the previous mails on this, I am afraid. It is fairly urgent.
Kind regards
Jörg

Sent from my iPhone

On 18 Feb 2019, at 10:03, nuneslf <notifications@github.com<mailto:notifications@github.com>> wrote:


@joergklausen<https://github.com/joergklausen> @efucile<https://github.com/efucile> I think we should add table 1-02 to the Github and submit it as is; The issue of adding the missing units now or later via discussion with IPET-CM(?) could stay open.

**Comment by LuisaIckes** [comment]
I have a version of the codelist which I was about to make ready to add it to Github @HoratN should I pause this or go on?

**Comment by HoratN** [comment]
I will follow up on that after lunch. For now think it would be good to have an initial draft. So in my opinion please go ahead. Thanks.

**Comment by LuisaIckes** [comment]
Ok!

**Comment by HoratN** [comment]
Markus is on vacation this week. so I think there is nothing we can do about the units mentioned in this email conversation. 
Hopefully the variables from the emails are also covered by OSCAR.

**Comment by LuisaIckes** [comment]
@HoratN do you have the OSCAR unit table for comparison? 
I was also wondering what to do with the short name of the units - they are written with superscripts in the current table ( e.g. g kg⁻¹ s⁻¹) and that causes some problems when converting to cvs etc.. How should that be solved? g kg^(-1) s^(-1)?

**Comment by HoratN** [comment]
See the OSCAR version with some encoding bugs here: 
17073f8 

superscript numbers are ok, but the minus in the superscript causes problems.

**Comment by LuisaIckes** [comment]
yes and s-1 is also not really precise or not the same/as clear as s^(-1)- how should we proceed?

**Comment by HoratN** [comment]
I see 4 possibilities:
1. use the ugly s^(-1) everywhere
2. use the ugly notation only if a minus exists in the entry
3. use 1/s¹
4. get rid of the name column.

I would keep the name column and go for option 2 or 3. Even option 1 would be ok, since this is the scientific way to write it.
option 2 is not very consistent, but then at least a part of the names is readable.

I think my favorite is option 3.

**Comment by nuneslf** [comment]
First comment is that we are looking for is the "WMO306CD" (or notation in the codes registry) not the "Name": e.g. we are looking for a WMO306CD/Notation for the entry named: "metres per second", which could be "m_s-1" could be based on the currently published units on the codes registry.

So, I see two more options:
5. Create a short/abbreviation for the WMO306CD/Notation based on the Name, for ex: "metrespersec";
6. Use the current Notation for those entries already published in the codes registry: see the example above: "m_s-1" (from http://codes.wmo.int/common/_unit).

Option 6. is my favorite, even if there is a need to create new WMO306CD/notations for those entries that don't exist in the codes registry.

**Comment by HoratN** [comment]
Ah, now I see why you suggested to use the definition for the name.
I am in full support of 6. 
This means that we make this change to the table which I commited here 17073f8:
definition.text-->name

**Comment by LuisaIckes** [comment]
Ok, I can take care of that now!

**Comment by LuisaIckes** [comment]
Done!
I'll leave the issue open in case there are new units to be added later on?

**Comment by LuisaIckes** [comment]
@nuneslf Should I add the new units added by Lucia?

micromoles   per mole | μmol_mol-1
nanomoles   per mole | nmol_mol-1
picomoles   per mole | pmol_mol-1
millimoles   per mole | mmol_mol-1
millibecquerels   per cubic metre | mBq_m-3
micromoles   per kilogram | μmol_kg-1
micromoles   per litre | μmol_l-1
micrograms   per cubic metre at 20 degrees | μg_m-3_   -20C
micrograms   per cubic metre at 25 degrees | μg-m-3_-25C
milligrams   per cubic metre at 25 degrees | mg_m-3_-25C
nanograms   per cubic metre | ng_m-3
microgram   N per cubic metre | μg_N_m-3
microgram   C per cubic metre | μg_C_m-3
microgram   S per cubic metre | μg_S_m-3
microgram   CI per cubic metre | μg_Cl_m-3
miligram   N per litre | mg_N_l-1
miligram   S per litre | mg_S_l-1

**Comment by joergklausen** [comment]
You’re doing great ... and I am going offline again soon ;-)
Watch out: spelling mistakes, it should be ‘milli’ not ‘mili’
Cheers
Jörg

Sent from my iPhone

On 20 Feb 2019, at 18:19, LuisaIckes <notifications@github.com<mailto:notifications@github.com>> wrote:


@nuneslf<https://github.com/nuneslf> Should I add the new units added by Lucia?

micromoles per mole | μmol_mol-1
nanomoles per mole | nmol_mol-1
picomoles per mole | pmol_mol-1
millimoles per mole | mmol_mol-1
millibecquerels per cubic metre | mBq_m-3
micromoles per kilogram | μmol_kg-1
micromoles per litre | μmol_l-1
micrograms per cubic metre at 20 degrees | μg_m-3_ -20C
micrograms per cubic metre at 25 degrees | μg-m-3_-25C
milligrams per cubic metre at 25 degrees | mg_m-3_-25C
nanograms per cubic metre | ng_m-3
microgram N per cubic metre | μg_N_m-3
microgram C per cubic metre | μg_C_m-3
microgram S per cubic metre | μg_S_m-3
microgram CI per cubic metre | μg_Cl_m-3
miligram N per litre | mg_N_l-1
miligram S per litre | mg_S_l-1

**Comment by LuisaIckes** [comment]
Corrected it and added it to the table, there is one inconsistency I am not sure if this is correct:
micrograms per cubic metre at 20 degrees, μg_m-3_-20C
is it at 20 degrees or at -20 degrees? From the name it looks more like -20 degrees C?

**Comment by LuisaIckes** [comment]
Leave the issue open in case the missing/new units from Markus still appear at some point...

**Comment by HoratN** [comment]
I think it would be better to interchange the Name and the WMO306CD in the entries suggested by Lucia. 
![image](https://user-images.githubusercontent.com/43061805/53247586-048eee80-36b4-11e9-8ea0-fbe3f89f1523.png)
Should I do that?

**Comment by LuisaIckes** [comment]
Oh sorry, did not see that it was the wrong way around, I can correct it!

**Comment by HoratN** [comment]
Ok. Thank you. Could you please also remove the tabs?

**Comment by LuisaIckes** [comment]
Yes!

**Comment by HoratN** [comment]
> 
> 
> Corrected it and added it to the table, there is one inconsistency I am not sure if this is correct:
> micrograms per cubic metre at 20 degrees, μg_m-3_-20C
> is it at 20 degrees or at -20 degrees? From the name it looks more like -20 degrees C?

Jörg: should be +20C, +25C.

I will correct it and merge to the development branch.

**Comment by HoratN** [comment]
No more units have been found in the email conversation between Markus and Jörg.
I suggest to close this issue.

**Comment by LuisaIckes** [comment]
Good!
