### ISSUE TITLE
New variables for the codetable 1-01-01.csv

### ISSUE THREAD

**Issue by richard-olav** [wmo-im/wmds#170]
I am not able to find the representations for the variables below in the codetable 1-01-01.csv Observed variable - measurand (atmosphere):

EBAS variable name, cf_name,matrix
magnesium,mass_concentration_of_magnesium_in_pm1_in_air,pm1
magnesium,mass_concentration_of_magnesium_in_pm10_minus_pm1_in_air,pm10_pm1
magnesium,mass_concentration_of_magnesium_in_pm10_minus_pm2p5_in_air,pm10_pm25
magnesium,mass_concentration_of_magnesium_in_precipitation,precip

Could they be added?

**Comment by IgorZahumensky** [comment]
@joergklausen and the last one for 1-01-01.csv

**Comment by joergklausen** [comment]
Franziska: needs a Proposal and Reason, and branch with new entries along the lines of what we already have. It is clear that we will review the structure of the table more holistically, but adding new variables is more achievable right now.

**Comment by fstuerzl** [comment]
**Summary and Purpose**
Addition of variables for magnesium in code table 1-01-01 (Observed variable - atmosphere) 

**Proposal**
Include the following variables in code table 1-01-01.csv

Label | Description | Path
-- | -- | --
Magnesium (Mg++),   PM1, in air | Mass concentration   of magnesium in PM1 in air | \Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), PM1, in air
Magnesium (Mg++),   PM10-PM1, in air | Mass concentration   of magnesium in PM10-PM1 in air | \Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), PM10-PM1, in air
Magnesium (Mg++),   PM10-PM2.5, in air | Mass concentration   of magnesium in PM10-PM2.5 in air | \Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), PM10-PM2.5, in air
Magnesium (Mg++), in   precipitation | Mass concentration   of magnesium in precipitation | \Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++),  in precipitation

**Reason**
Missing entries in variable list, required by @richard-olav

**Comment by gaochen-larc** [comment]
Since these are absolute mass concentrations, they should be further defined as reported under STP or ambient conditions or some specific pressure and temperature.

**Comment by fstuerzl** [comment]
Branch: https://github.com/wmo-im/wmds/tree/Issue170
View differences: https://github.com/wmo-im/wmds/commit/3d9ea7b151ec64038e2f87f908a81fb81abde137#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d

Like issue #168 and #169, this depends on the reorganisation of the aerosol branch (#173, #181). Therefore the paths and the treatment of modifiers might change later. It needs to be discussed whether the variables should be included in FT-2021-1 nevertheless. @richard-olav, @gaochen-larc, @markusfiebig, could you please comment you opinion on this matter?

**Comment by markusfiebig** [comment]
@fstuerzl, I'm a little confused about the proposed names. Just before Christmas, we had a telecon where we found ways to store modifiers like PM1, PM10, etc. in WMDS elements outside the variable name to prevent the list of variables from blowing up. We also agreed that the way forward would be to store these modifiers not in the variable names, but other places in the metadata record. If we now define names that include modifiers, we are locked in, or we need to change them again very soon. I would propose to leave these out.

**Comment by gaochen-larc** [comment]
@fstuerzl I found the Magnesium (Mg++) in 1-01-01 table in the xlsx file you sent to me.  Does this mean it is already in the list?
Sorry, if the file I have is a newer version.

\Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), PM10
\Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), PM2.5
\Atmosphere\Aerosol\Composition\Inorganic   cations\Magnesium (Mg++), total aerosol

**Comment by fstuerzl** [comment]
@gaochen-larc, this is correct. The three variables you listed are already in the code list.

**Comment by fstuerzl** [comment]
Since there is no need to add these variables now (see #169), the issue can be closed.
