### ISSUE TITLE
merge development to master

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#175]
We need to verify that the changes in development are correct and document the originating issues.

**Comment by IgorZahumensky** [comment]
@efucile for clarification: 
do you mean that 
https://github.com/wmo-im/wmds/tree/Development/tables_en
to be merge to
https://github.com/wmo-im/wmds/tree/master/tables_en
?
Or 
I am lost one ...

**Comment by amilan17** [comment]
This is the only issue associated with the codes that was addressed in the development branch. It does not appear in Master
https://github.com/wmo-im/wmds/issues/116

The other updates are in the scripts/ directory and the readme. 

https://github.com/wmo-im/wmds/compare/Development#diff-3f87dac533339cfd0fb71fbe31c83803

**Comment by amilan17** [comment]
Timo merged.

**Comment by amilan17** [comment]
done (https://github.com/wmo-im/wmds/tree/02219354a95da6b83c8d4b2428a26457a7a3c3b3)
