### ISSUE TITLE
1-01-01: Use of term "aerosol" in observed variable table

### ISSUE THREAD

**Issue by markusfiebig** [wmo-im/wmds#181]
**Branch**
* https://github.com/wmo-im/wmds/tree/Issue181
* View differences: d93efd4

**Summary and Purpose**

**Proposal**

**Reason**

* **********************
**original comment**
This issue is of somewhat fundamental nature, and concerns the use of the term "aerosol" throughout table 1-01-01. The GAW aerosol SAG has pointed out that the use of "aerosol" in table 1-01-01 is misleading, and insists on this being corrected.

According to technical literature, "aerosol" is defined as "an assembly of liquid or solid particles suspended in a gaseous medium..." (Willeke & Baron, 1993), i.e. refers to the system of particles and carrier gas. The use of "aerosol" as referring to the suspended particles only is colloquial. Rather, terms as "aerosol particle" when referring to a single particle, or "particle phase" when referring to all suspended particles in an aerosol, should be used.

This has several implications for table 1-01-01, which should be possible to correct since the property is identified by the number, not the pertaining string. Several other consistency issues ar also addressed:

1. In the variable hierarchy, the term "aerosol" needs to be replaced by "particle phase", e.g. "\Atmosphere\Aerosol\..." replaced with "\Atmosphere\Particle Phase\..."
2. "Aerosol Absorption Optical Depth" to be replaced with "particle absorption optical depth"
3. "Aerosol Extinction Coefficient" to be replaced with "particle light extinction coefficient"
4. "Light absorption coefficient" to be replaced with "particle light absorption coefficient", for consistency
5. "Light backscattering coefficient" to be replaced with "particle light backscattering coefficient", for consistency
6. "Light scattering coefficient" to be replaced with "particle light scattering coefficient", for consistency
7. "Aerosol column burden (mass density)" to be replaced with "particle column burden (mass density)"
8. "Aerosol effective radius" to be replaced with "particle effective radius"
9. "Aerosol dust concentration (mass)" to be replaced with "dust particle concentration (mass)"
10. "Number concentration" to be replaced with "particle number concentration", for consistency
11. "Number size distribution" to be replaced with "particle number size distribution", for consistency
12. "Aerosol volcanic ash (mass concentration)" to be replaced with "volcanic ash particle concentration (mass)"
13. "CCN concentration at single supersaturation" and "CCN concentration spectra" aren't secondary variables, but primary, since they can be measured directly. 

In the aerosol variables, several modifiers are used: "total aerosol", PM1, PM2.5, PM10, "air and aerosol", TSP. "total aerosol" is often used to denote "particles + carrier gas" in cases where "aerosol" is used wrongly to denote the particle phase. In this table however, "total aerosol" is used in contrast to PM1, PM2.5, and PM10, which would indicate a meaning of "particle phase without size restriction". Thus, "total aerosol" is used ambigously in this table. If "aerosol" is used correctly ("particles + carrier gas"), the term "air and aerosol" doesn't make sense. Thus, the following changes are proposed:
14. In cases where "total aerosol" is used to denote "particles + carrier gas", it should be replaced by "gas + particle phase". This avoids issues around the term "aerosol" alltogether.
15. In cases where "total aerosol is used to denote "particle phase without size restriction", it should be replaced by TSP for "total suspended matter".
16. The term "air and aerosol" should be replaced by "gas + particle phase".

**Comment by IgorZahumensky** [comment]
How is it related to https://github.com/wmo-im/wmds/issues/173?
Not possible to merge them?

**Comment by markusfiebig** [comment]
> 
> 
> How is it related to #173?
> Not possible to merge them?

I wouldn't want to merge these issues. #173 is about a feature lacking in the WMDR structure, whether #181 is of semantic nature.

**Comment by IgorZahumensky** [comment]
OK; it was just my Q as not having expertise in this area

**Comment by ejwelton** [comment]
I would like to point out several related problems with the existing observed variable code list, some relate to aerosols and others clouds. They are closely related to this topic so I'd like to capture them in one place.
1. Several variables in the code list do not exist in the actual OSCAR requirements tables: all backscatter variables, the Vertical distribution of properties variable (the latter is also a meaningless quantity), optical depth within each layer, and cloud amount.
2. Some important variables related to aerosols are not in the code list, but are in the OSCAR requirements: aerosol layer height, and height of the top of the PBL. These should be added to the code list.
3. Aerosol related optical depth as currently defined in the code list "requires" multi-wavelength optical depth. However, the OSCAR requirements only recommend multi-wavelength. It is also difficult to capture multi-wavelength information in the WMDR for one variable. I suggest this be renamed to particle optical depth following this thread.
4. There is no wavelength specification within the WMDR, only frequency. This severely hampers the ability to capture visible-IR remote sensing observations as are typical for both aerosol and cloud. This is an ongoing discussion but I do not think it has been captured on GitHub yet for WMDR.

**Comment by gaochen-larc** [comment]
This is an important issue.  For clarification, I checked two textbooks: "modeling of atmospheric chemistry" by Guy Brasseur and Daniel Jacob and "Atmospheric Chemistry and Physics" by John Seinfeld and Spyros Pandis.  Both books recognize that the "common use" of the term "aerosol" deviates from the dictionary definition.   Particles and Particulate Matter are correct terms to refer the atmospheric particles.  The first book suggested use of "atmospheric particles" to remove ambiguities.  I think the "particle" or "particulate matter" are more concise terms.  At the same time, I believe the names matter less than the definitions.  It also comes down to the practical side, i.e.,  how much work will be involved to change "aerosol" to "particles"

**Comment by fstuerzl** [comment]
Branch created, according to @markusfiebig's proposal: https://github.com/wmo-im/wmds/tree/Issue181
View differences: https://github.com/wmo-im/wmds/commit/d93efd4e0913d94280dd9d6bc33360e107c622eb#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d

**Comment by gaochen-larc** [comment]
Propose to use "PM" to replace "aerosol"

**Comment by ejwelton** [comment]
I must admit I had been focused more on correcting terms here than on the issue of the definition of an aerosol and removing that word. There are many valid corrections listed above that should be fixed. Let me preface my following comments by saying I’ve been doing atmospheric aerosol research since 1994. I’ve worked with just about every major group in this research area. No one I know has been concerned about the use of the term aerosol vs it’s dictionary definition, it’s certainly not something argued about at a level that we redefine project names etc... We all know what we are talking about here. To me there is a major difference between dictionary definition of an aerosol and atmospheric aerosol. But Let’s not focus on such semantics. If we did, I’d ask if the SAG is going to change their name to particulate matter SAG. The terms needed many changes and standardizing them is desirable. If particle is used vs aerosol its ok. But there are some issues to consider since “particle” itself is vague. Will all these terms in the code lists now also apply to cloud “particles” as well? Water, ice and mixed phase. What about pollen, which has historically had a weird position separate from aerosol measurements (despite many aerosol observations probably involving them). Many air quality measurements separately identify pollen due to health impacts like allergies. Also, I’d love to know who within GAW is reporting “aerosol” measurements that include some carrier gas signal in addition to that from particulate matter?

**Comment by amilan17** [comment]
Some things to consider if the team decides to proceed with proposal: 

*   Add definitions to all revised terms
*   Is the fundamental meaning of a term changed by these revisions? If so, then we need to keep original term, add new one and potentially supersede original term with new term

**Comment by sebvi** [comment]
I like "Particulate Matter (PM)" to replace "aerosol" and stop using "aerosol" completely to avoid confusion

**Comment by charlesabrock** [comment]
I am fine with using "particulate" or "particle phase" as an adjective, and "particle" (NOT "particulate"!) as a noun.

**Comment by jbnowak-larc** [comment]
I agree with using particulate or particle phase as an adjective and particle as a noun.

**Comment by markusfiebig** [comment]
Judging from the comments received, there seems to be a consensus to remove the ambiguity of the term aerosol, and replace it by a univocal term. I would also propose to finally go with 

"particle phase as an adjective and particle as a noun"

**Comment by markusfiebig** [comment]
This would also reflect the clearly expressed wish of the SAG aerosol to remove the ambigeous use of "aerosol".

**Comment by joergklausen** [comment]
Issue has been resolved with the new approach involving a combination of domain ("atmosphere") and matrix ("particle phase"), where "particle phase" supersedes "aerosol". The term "aerosol" remains as a matrix but is reserved for use in case an observation refers to gas + particle phase.

**Comment by amilan17** [comment]
@joergklausen Can you confirm that you did not want these changes included in the FT-2021-2 release? https://github.com/wmo-im/wmds/compare/FT21-2...Issue181

**Comment by fstuerzl** [comment]
@amilan17 the branch https://github.com/wmo-im/wmds/tree/Issue181 is irrelevant for the new release, because the proposed changes are already dealt with in other issues.
