### ISSUE TITLE
1-01-01: distinction between primary and secondary physical particle properties

### ISSUE THREAD

**Issue by markusfiebig** [wmo-im/wmds#182]
**Branch**
*https://github.com/wmo-im/wmds/tree/Issue182  
*View differences: a816202#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d  

**Summary and Purpose**  
In the aerosol branch the distiction between primary and secondary physical properties is inconsistent and hard to define and should therefore be removed.  
Also, in the  GAW implementation plan there is no indication that a distiction between physical particle properties is needed.

**Stakeholder(s)**  
@markusfiebig

**Proposal**  
Combine the two categories "\\Atmosphere\\Aerosol\\Physical properties - primary" and "\\Atmosphere\\Aerosol\\Physical properties - secondary" in one: "\\Atmosphere\\Aerosol\\Physical properties"  

****************************
**original issue comment**
The distinction between primary and secondary physical particle properties refers to the way the information was obtained, either by direct measurement (primary) or inferred indirectly (secondary). This distinction should be removed because:

1.  the table for variable names isn't the correct place to store information on the method how data was obtained
2.  the physical particle variables are the only variable group making this distinction, which is inconsistent with other variables.
3.  the distinction between primary and secondary properties is rather diffuse to define.

**Comment by gaochen-larc** [comment]
I agree.  Most of the particle property measurements are secondary, other than particle number density.

**Comment by fstuerzl** [comment]
**Summary and Purpose**
In the aerosol branch the distiction between primary and secondary physical properties is inconsistent and hard to define and should therefore be removed.
Also, in the  GAW implementation plan there is no indication that a distiction between physical particle properties is needed.

**Stakeholder(s)**
@markusfiebig 

**Proposal**
Combine the two categories "\Atmosphere\Aerosol\Physical properties - primary" and "\Atmosphere\Aerosol\Physical properties - secondary" in one: "\Atmosphere\Aerosol\Physical properties"
Branch: https://github.com/wmo-im/wmds/tree/Issue182
View differences: https://github.com/wmo-im/wmds/commit/a8162028c8b6bf5499cf28b3a1d62245e32e2596#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d

**Comment by markusfiebig** [comment]
This issue is related to the discussion of the subdomain structure, in fact the discussion on hierarchy and tags, and should be taken there.

**Comment by joergklausen** [comment]
Team recommendation to drop notion of primary and secondary.

**Comment by amilan17** [comment]
@joergklausen - this issue was closed and branch was never merged into FT branch. Was it decided to NOT include these changes in the FT? It doesn't change the FT amendments because only a part of the path changed, but at this moment, these changes will not be merged into FT and subsequently master.... 
https://github.com/wmo-im/wmds/compare/FT21-2...Issue182
