### ISSUE TITLE
1-02 Additional entry required

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#184]
**Branch**
https://github.com/wmo-im/wmds/tree/Issue184

**Summary and Purpose**
Addition of unit entry for "nanometer"

**Proposal**
Include the following unit in code table 1-02.csv
Notation | Label | Description
-- | -- | --
nm | nanometer | one billionth of a   meter (1e-9 m)

**Reason**
Missing unit, required by @joergklausen 

_original issue_
----------------
We need an entry for 'nm', 'nanometer'.  
notation: nm  
label: nanometer  
description: one billionth of a meter, 1e-9 m

**Comment by fstuerzl** [comment]
**Summary and Purpose**
Addition of unit entry for "nanometer"

**Proposal**
Include the following unit in code table 1-02.csv
Notation | Label | Description
-- | -- | --
nm | nanometer | one billionth of a   meter, 1e-9 m

**Reason**
Missing unit, required by @joergklausen

**Comment by joergklausen** [comment]
@fstuerzl Please create branch
@RMaerz Please confirm branch

**Comment by fstuerzl** [comment]
Branch: https://github.com/wmo-im/wmds/blob/Issue184/tables_en/1-02.csv

**Comment by joergklausen** [comment]
Confirm that branch is correct.

**Comment by RMaerz** [comment]
confirmation from me (even if joergklausen meanwhile moved it to validated )  .... btw: might adding micrometer (um) be necessary?  - maybe for far infrared wavelenghts measurements  ????

**Comment by amilan17** [comment]
@RMaerz  -- Please open a new issue if you want to add micrometer to the codes.
