### ISSUE TITLE
New code list 1-04-02 'ObservedLayer'

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#185]
**Summary and Purpose**
Addition of a new code list for the vertical extent of observation

**Proposal**
Create a new code table based on the existing OSCAR/Requirements list of levels (Draft: VerticalExtentOfObservation.txt)

**Reason**
OSCAR/Requirements list requested as WMDR code list. Information on vertical level are relevant for observations in the atmosphere, terrestrial observations, observations in the ocean, and outer space and complement the attribute 'geometry of observation'.

**Branch**
New Branch: https://github.com/wmo-im/wmds/tree/issue185-FT

_original issue comment_
Review the existing code list from OSCAR/Requirements and establish one for WMDR. The vertical levels of observations is a complement to the attribute 'geometry of observation' and should be used to describe the vertical levels to which the observation applies. This is equally relevant for observations in the atmosphere, terrestrial observations, observations in the ocean, and outer space.

**Comment by joergklausen** [comment]
Attached is a first draft of the proposed code list, building on the existing OSCAR/Requirements list of levels. The MS Excel version ([VerticalExtentOfObservation.xlsx](https://github.com/wmo-im/wmds/files/5040823/VerticalExtentOfObservation.xlsx)) contains the mapping, the CSV file ([VerticalExtentOfObservation.txt](https://github.com/wmo-im/wmds/files/5040826/VerticalExtentOfObservation.txt)) the code list itself.

**Comment by ejwelton** [comment]
I am happy to see the OSCAR layer requirements be considered as a new code list, it is critical for profiling observations such as lidar or ballon. The proposal looks good to me. However, I recommend removing altitude range suggestions in the descriptions of vertical extent. The location of the UTLS and height of the troposphere (ie, tropopause) are heavily dependent upon latitude and season. PBL height varies with latitude, season, and surface features (can be ~5 km over desert), thus also the bottom of the free troposphere varies. I think its best to remove explicit altitude range in description, and let the user determine layer choice based on their site location and instrument capabilities. In my opinion, that is the strength of the OSCAR layer requirements approach, that it does not define layers by altitude but by name. We should not change that fluidity when translating the requirements to a code list.

**Comment by toakley76** [comment]
From the atmospheric perspective this code list looks OK to me. As it had been taken from the OSCAR requirements database we have already changed this terminology to reflect how we specify the requirements in the different parts of the atmosphere. If we have missed something, this can be added when a user requests it. I am not so concerned about the height examples given in the description (ca does mean more or less) and it might help those completing their metadata to choose the most appropriate.

**Comment by joergklausen** [comment]
Franziska: this needs a consolidated Proposal and Reason, new branch, then review by ejwelton and toakley76, also RMaerz.

**Comment by fstuerzl** [comment]
**Summary and Purpose**
Addition of a new code list for the vertical extent of observation

**Proposal**
Create a new code table based on the existing OSCAR/Requirements list of levels (Draft: [VerticalExtentOfObservation.txt](https://github.com/wmo-im/wmds/files/5402885/VerticalExtentOfObservation.txt))

**Reason**
OSCAR/Requirements list requested as WMDR code list. Information on vertical level are relevant for observations in the atmosphere, terrestrial observations, observations in the ocean, and outer space and complement the attribute 'geometry of observation'.

**Comment by ejwelton** [comment]
It seems that the issue of including specific altitude ranges in the descriptions is still open? If not, what was the decision? As mentioned earlier I recommend removing them. I have no other comments or issues.

**Comment by toakley76** [comment]
The new code table looks OK to me. I don't have an issue with the approximate (ca) ranges in the description.

**Comment by joergklausen** [comment]
Branch created at https://github.com/wmo-im/wmds/tree/Issue%23185.

**Comment by gaochen-larc** [comment]
I agree with Judd.  The tropopause height are latitude dependent.  The altitude range can be misleading.  The free troposphere can get to 16 km.   It is more reasonable to define the free troposphere between 1 and 16 km.  I have seen the marine boundary layer as low as 200 - 300 m over cold water in the tropics,  Also the typical night time PBL are ~100 m over land.   The arctic stratosphere can be lower than 8 km.

As for the column, is there is a need to separate slant column vs. vertical column?

**Comment by RMaerz** [comment]
I can understand both meanings pro/con giving rough dimensions (all of course with ca./approximate). But to give colleagues of other disciplines a rough estimate of what it is about I would prefer to find ranges. We all know that exact values can only be determinded by live measurements depending on the current situation as i.e. performed in every vertical Profile of a TEMP sounding for the exact Tropopause.

**Comment by ejwelton** [comment]
Its ok with me to leave the ranges in the description. I don't want to hold up releasing the new code list just for this issue.

**Comment by joergklausen** [comment]
@gaochen-larc I am not sure your comment "As for the column, is there is a need to separate slant column vs. vertical column?" is pertinent in the context of this table.
@RMaerz Can you please confirm the branch?

**Comment by gaochen-larc** [comment]
confirm.  Thanks!

**Comment by RMaerz** [comment]
confirm, too!

**Comment by amilan17** [comment]
@fstuerzl @joergklausen 

please create proposed amendments again in this branch: 

[https://github.com/wmo-im/wmds/tree/issue185-FT](https://github.com/wmo-im/wmds/tree/issue185-FT)

**Comment by fstuerzl** [comment]
@amilan17 new code table was added to branch: https://github.com/wmo-im/wmds/blob/issue185-FT/tables_en/1-04-02.csv

**Comment by amilan17** [comment]
Need to define description and URL of new table

Description: Vertical extent of observation

URL: //codes.wmo.int/wmdr/VerticalExtent

**Comment by amilan17** [comment]
@joergklausen Please provide an improved description and URL.

**Comment by joergklausen** [comment]
The term 'extent' was a poor choice initially, mea culpa. What this code list allows one to describe are 'positions' or 'locations', in fact, 'layers' in the vertical to which observations or requirements for observations apply. In line with the existing use in OSCAR/Requirements, this appears to be best captured in the term 'layer': a 'layer' refers to a range of altitude or depth where a (physical) variable is measured and a requirement for this variable is applicable. 
Layers can have different extents, they can be thick, or thin to the point where they only describe a boundary or interface. The are stacked vertically but extend horizontally, like onion shells.

Description: 'Layer (of observation)'

URL: //codes.wmo.int/wmdr/ObservedLayer
