### ISSUE TITLE
2-02 Programs/networks: structure of GAW branch

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#187]
**Branch**
https://github.com/wmo-im/wmds/tree/Issue%23187

**Comment by Netcheva** [comment]
GAW Secretariat requests the following change which better represents its current Structure:
 
**GAW Programmes and Networks Structure**  

**GAW >** 
GAW Global
GAW Regional
GAW Local


**GAW Contributing >**
	TCCON
	EARLINET
	IMPROVE
	AD-Net
	LALINET
	NADP
	INDAAF
	MPLNET
	CASTNET
	IAGOS
	EANET
	ICOS


**GAW Other >**
		AEROCAN
		German AOD Network
		PHOTONS
		PolarAOD
		SKYNET
		SibRad
		CAPMoN
		CLN
		EMEP
		ESRLCCG
		NDACC
		SHADOZ
		Non-Affiliated

**Comment by joergklausen** [comment]
This issue is linked to #188 and #189.

**Comment by joergklausen** [comment]
Branch created at https://github.com/wmo-im/wmds/compare/master...Issue%23187. Note that other branches affect the same table.

**Comment by tomkralidis** [comment]
@joergklausen agree with your suggestions (we need to clarify what the strategy is around deprecating entries).

**Comment by fstuerzl** [comment]
Regarding the second programme on @joergklausen's list: In OSCAR/Surface the entry AERONET has a different path. Please confirm if the following proposal for this entry is correct.

![screenshot_aeronet](https://user-images.githubusercontent.com/72029328/102473168-6f62a400-4057-11eb-84aa-1347f840ddf7.PNG)

AERONET | \Non-affiliated\AERONET | AERONET | AErosol RObotic NETwork
-- | -- | -- | --

**Comment by fstuerzl** [comment]
Branch is updated, view differences: https://github.com/wmo-im/wmds/commit/e05670710f546d203d4efcea8a96d49848b63e7f#diff-a066c50c20373fc15bcd759e58529c31867ae12caecaa7d36ad762
This leads to the following structure:


GAW Global

GAW Regional

GAW Local

GAW Contributing
- TCCON
- EARLINET
- IMPROVE
- AD-Net
- LALINET
- NADP
- INDAAF
- MPLNET
- CASTNET
- IAGOS
- EANET
- ICOS

GAW Other
- AEROCAN
- German AOD Network
- PHOTONS
- PolarAOD
- SKYNET
- SibRad
- CAPMoN
- CLN
- EMEP
- ESRLCCG
- NDACC
- SHADOZ
- Non-Affiliated
- CIS-LiNet
- ACTRIS 
- AGAGE
- ABOS (retired) 
-MOZAIC (retired)
- AOD (retired)
- Aeronet

@Netcheva, Oksana, please review the branch.

**Comment by Netcheva** [comment]
on behalf of Stoyka Netcheva and Oksana Tarasova:
We request only one change with proposed structure namely taking out "Non-Affiliated" from proposed tree and leaving the rest as it shows right now. Please note that we will be requesting a name correction from ESRLCCG to ESRLCCGG as we expect this requires a new action request.

**Comment by tarasova-wmo** [comment]
Also, we discussed on 6 January the option of creating a label similar to "Centennial" to allow for additional affiliation for the GALION networks

**Comment by fstuerzl** [comment]
@Netcheva, @tarasova-wmo, thanks for your comments. I'll update the branch accordingly. The changes regarding GALION are made in the branch for the issue, that deals with this problem (https://github.com/wmo-im/wmds/commit/2268f3f82094c36b7f37be9c16c532057962.c190#diff-178d0ba48282279e1a03f1d2dc6739a7ff8999a4f14acc531aa8144af5383986)

**Comment by joergklausen** [comment]
@fstuerzl Can you post the link to the relevant branch again, please?

**Comment by fstuerzl** [comment]
@joergklausen  https://github.com/wmo-im/wmds/blob/Issue%23187/tables_en/2-02.csv

**Comment by joergklausen** [comment]
Branch validated

**Comment by amilan17** [comment]
@joergklausen @fstuerzl Which one is correct? 

1.  EANET,\\WIGOS\\GAW\\GAW Other elements\\EANET,EANET,EANET
2.  EANET,\\WIGOS\\GAW\\GAW Contributing networks\\EANET,EANET,EANET

**Comment by tarasova-wmo** [comment]
2 is correct, contributing network
