### ISSUE TITLE
2-02 Programs/networks: INDAAF instead of IDAF

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#188]
**Proposal**  
Deprecate entry http://codes.wmo.int/wmdr/ProgramAffiliation/IDAF.  
Add new entry:  
notation, name, description  
INDAAF, INDAAF, International Network to study Deposition and Atmospheric composition in Africa (https://indaaf.obs-mip.fr/)

**Reason**  
This is a correction of a typo / change of name at the source that we need to follow.

**Branch**  
[https://github.com/wmo-im/wmds/tree/Issue%23188](https://github.com/wmo-im/wmds/tree/Issue%23188)

**Decision**
IDAF is superseded by INDAAF

**Comment by joergklausen** [comment]
Branch created at https://github.com/wmo-im/wmds/tree/Issue%23188.
@Netcheva, @tomkralidis Please review and confirm or comment.

**Comment by tomkralidis** [comment]
+1 pending deprecation strategy.

**Comment by Netcheva** [comment]
INDAAF (International Network to study Deposition and Atmospheric composition in Africa) has been formed in result of the union of the previously labeled IDAF network (GAW Contributing Network under Agreement Ref. 15744-2015 RES/ARE ) and the “Sahelian Dust Transect” network. An amendment to the old Agreement had been circulated for approval and signatures for the depreciation of IDAF.

**Comment by fstuerzl** [comment]
According to the deprecation strategy established by @amilan17 in #199 this is an example for the use case "Code needs updates and the concept remains the same, but edits will change the 'notation' that becomes part of the URL ==> supersede with new code". 

@tomkralidis, @Netcheva, please review the updated branch: https://github.com/wmo-im/wmds/blob/Issue%23188/tables_en/2-02.csv

**Comment by joergklausen** [comment]
Both reviewers agree, branch is valid. @amilan17 To be clear, the entry IDAF should disappear and be included in your list of superseded elements. Do we need separate tables here on github to facilitate this workflow? In principle, the current branch should really just replace the existing entry IDAF with INDAAF ...

**Comment by amilan17** [comment]
The branch is not ready yet. 

@fstuerzl  -- Can you update this branch so that the superseded term is removed and only referred to in the superseded.txt file? Thanks!

**Comment by fstuerzl** [comment]
@amilan17 done!

**Comment by joergklausen** [comment]
Branch validated
