### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#194]
Please consult https://github.com/wmo-im/wmds/wiki/How-to-address-problems-and-suggest-changes-to-the-Codetables and use the following structure for new issues.

**Summary and Purpose**
[your arguments why the existing situation is not satisfying]

**Proposal**
[your specific proposal to resolve the issue]

**Reason**
[your reasoning why the proposal resolves the issue]

**Comment by joergklausen** [comment]
@amilan17 Please use above to generate an issue template, I can't do this myself. @tomkralidis had pointed out a similar template in use for the GRIB work, but upon reflection, it seemed again a bit too complex ... we can also discuss what's best, but *any* template would certainly help in future.

**Comment by amilan17** [comment]
Done. @joergklausen. Will you test?  I agree that we can improve as needed.

**Comment by amilan17** [comment]
Done!
