### ISSUE TITLE
4-01-07 Encoding of label "unknown"

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#195]
**Summary and Purpose**
Label for entry "unknown" in Table " SurfaceCoverGlob2009" is incorrectly encoded in Codes Registry (see [http://codes.wmo.int/wmdr/SurfaceCoverGlob2009/unknown](http://codes.wmo.int/wmdr/SurfaceCoverGlob2009/unknown)).

**Proposal**
Correct encoding of label for entry "unknown" in Table "Units", so that it reads “No data (burnt areas, clouds,…)” instead of “No data (burnt areas, clouds,â€¦)”.

**Reason**
Bug in encoding needs to be fixed.

**Comment by amilan17** [comment]
Displays as expected on test. 
http://testwmocodes.metarelate.net/wmdr/SurfaceCoverGlob2009/unknown

**Comment by amilan17** [comment]
fixed.
