### ISSUE TITLE
2-02 deprecate inapplicable

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#197]
**Summary and Purpose**
Deprecate element in code table for program affiliation.

**Proposal**
Deprecate element "inapplicable" from code table 2-02.csv (ProgramAffiliation).

**Reason**
The entry "inapplicable" is not meaningful in this case because the a program affiliation is either "unknown" or it must be included in the code register.

**Branch**
https://github.com/wmo-im/wmds/tree/issue197-FT

**Comment by joergklausen** [comment]
Branch at https://github.com/wmo-im/wmds/compare/master...Issue%23197.
@RMaerz @tomkralidis Please review proposal and confirm consent or comment.

**Comment by tomkralidis** [comment]
+1

**Comment by amilan17** [comment]
Decision dependent on #199.

**Comment by RMaerz** [comment]
I  fully agree !

**Comment by fstuerzl** [comment]
According to https://github.com/wmo-im/wmds/issues/199, the entry "inapplicable" is marked as "invalid".

**Comment by amilan17** [comment]
@joergklausen @fstuerzl 

Please modify this new branch. 

https://github.com/wmo-im/wmds/tree/issue197-FT

**Comment by fstuerzl** [comment]
@amilan17  branch updated, view difference: https://github.com/wmo-im/wmds/commit/2a12ad01f033c359c8d148a2512911fb8feefdad
