### ISSUE TITLE
11-03 Meaning of time stamp: fix definitions of 'beginning' and 'end'

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#204]
**Branch**
https://github.com/wmo-im/wmds/tree/issue204

https://github.com/wmo-im/wmds/blob/issue204/tables_en/11-03.csv

**Summary and Purpose**
The definition of beginning reads as end, and end is a duplicate of middle. The problem traces back to the approved text from [CBS-16](https://library.wmo.int/doc_num.php?explnum_id=3505) page 717.

**Stakeholder**
https://github.com/citterio
Reported by @iosifescu in [EnviDat/monitoring-backend#2 (comment)](https://github.com/EnviDat/monitoring-backend/issues/2#issuecomment-704560983)

**Proposal**
See details in pull request.
https://github.com/wmo-im/wmds/pull/192/files

**Comment by joergklausen** [comment]
@amilan17 Please create branch.
@gaochen_larc @RMaerz Please confirm branch

**Comment by amilan17** [comment]
created and edited branch -- ready for review

**Comment by gaochen-larc** [comment]
Thanks!  I got it.

**Comment by gaochen-larc** [comment]
Made one comment on "Beginning",  Please consider replacing "following" by "subsequent".  This is not critical.  All  changes look fine.  Thanks!

Just a note, the "Middle" time stamp can be critical when the sampling is uneven...  We run into an issue with a canister measurement.

**Comment by amilan17** [comment]
@fstuerzl - add subsequent

ask original requester to review final solution.

**Comment by fstuerzl** [comment]
Branch updated: https://github.com/wmo-im/wmds/blob/issue204/tables_en/11-03.csv
@citterio, @gaochen-larc, please confirm the branch.

**Comment by gaochen-larc** [comment]
confirm.  Thanks!

**Comment by joergklausen** [comment]
@citterio Can you please identify yourself and also confirm that you are in agreement with the solution to this issue?

**Comment by amilan17** [comment]
accept as is and notify @citterio in their original PR
