### ISSUE TITLE
Update entries on prod to correct poor encoding

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#205]
**Summary and Purpose**
There are a number of entries that don't display properly. 

Current testing on test shows that they can be fixed quickly. The values haven't changed in Git, somehow the codes registry is now able to render the display better. 
See Issues #183 and #195 as examples.  

**Proposal**
Update the following entries on prod asap. 
- [x] "/wmdr/DataPolicy/WMOAdditional.ttl", 
- [x] "/wmdr/DataPolicy/WMOOther.ttl", 
- [x] "/wmdr/ObservedVariableAtmosphere/314.ttl",:
- [x] "/wmdr/ObservedVariableAtmosphere/506.ttl",
- [x] "/wmdr/ObservedVariableAtmosphere/413.ttl", 
- [x] "/wmdr/ObservedVariableAtmosphere/414.ttl", 
- [x] "/wmdr/ObservedVariableAtmosphere/415.ttl", 
- [x] "/wmdr/ObservedVariableAtmosphere/416.ttl", 
- [x] "/wmdr/ObservedVariableAtmosphere/417.ttl", 
- [x] "/wmdr/ObservedVariableEarth/12.ttl",
- [x] "/wmdr/unit/E.ttl",
- [x] "/wmdr/ObservedVariableOcean/102.ttl",
- [x] "/wmdr/ObservedVariableOcean/95.ttl", 
- [x] "/wmdr/ObservingMethodAtmosphere/257.ttl",
- [x] "/wmdr/ProgramAffiliation/CANDHIS.ttl",
- [x] "/wmdr/SurfaceCoverGlob2009/unknown.ttl",
- [x] "/wmdr/SurfaceRoughnessDavenport/chaotic.ttl",
- [x] "/wmdr/TerritoryName/CIV.ttl",

**Comment by amilan17** [comment]
@efucile -- I don't think this needs to go through a Fast Track process. Please confirm.

**Comment by efucile** [comment]
No need for fast track for these

**Comment by amilan17** [comment]
All fixed.
