### ISSUE TITLE
Delete Stale Branches

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#207]
**Summary and Purpose**
There are a number of stale branches that may or may not still be relevant. 
https://github.com/wmo-im/wmds/branches/stale

**Proposal**
Review the stale branches and determine which ones can be deleted. 

**Reason**
Cleaning these up will minimise confusion.

**Comment by amilan17** [comment]
- [ ] https://github.com/wmo-im/wmds/tree/Development-backup-old-namings
- [ ] https://github.com/wmo-im/wmds/tree/Development-backup-all-columns
- [ ] https://github.com/wmo-im/wmds/tree/tables-from-OSCAR
- [ ] https://github.com/wmo-im/wmds/tree/issue90
- [ ] https://github.com/wmo-im/wmds/tree/joergklausen-patch-1
- [ ] https://github.com/wmo-im/wmds/tree/issue117
- [ ] https://github.com/wmo-im/wmds/tree/issue115 
- [ ] https://github.com/wmo-im/wmds/tree/issue111
- [ ] https://github.com/wmo-im/wmds/tree/issue112
- [ ] https://github.com/wmo-im/wmds/tree/issue123
- [ ] https://github.com/wmo-im/wmds/tree/revert-171-joergklausen-patch-3
- [ ] https://github.com/wmo-im/wmds/tree/FT-2021-1
- [ ] https://github.com/wmo-im/wmds/tree/issue-167
- [ ] https://github.com/wmo-im/wmds/tree/joergklausen-patch-4
- [ ] 
- [ ]

**Comment by joergklausen** [comment]
All fine, except I had created a mapping between the x-y-z code table notation from WMDS with the codes.wmo.int/wmdr names at one point, with hyperlinks. This has disappeared somehow. It would still be very useful IMHO. I believe this relates to the 171 issue.

**Comment by amilan17** [comment]
@joergklausen 
Is this the mapping you are referring to? 
https://github.com/wmo-im/wmds/blob/master/tables_en/wmdr-tables.csv

**Comment by amilan17** [comment]
@joergklausen I did not delete patch-1, but I think we can delete this one too, because this change is also in /tables_en/wmdr-tables.csv file on master. 
https://github.com/wmo-im/wmds/compare/joergklausen-patch-1

**Comment by joergklausen** [comment]
Indeed, that's the mapping. It should be kept up-to-date somehow. And I see in the readme.md a reflection of if, which could be included in the overall readme.md of the repo, don't you think?

**Comment by amilan17** [comment]
> Indeed, that's the mapping. It should be kept up-to-date somehow. 
I think it is up-to-date. Do you agree? 

> And I see in the readme.md a reflection of if, which could be included in the overall readme.md of the repo, don't you think?
I think it's more appropriate for this readme to live in the tables_en folder....

**Comment by joergklausen** [comment]
But then link to this at least from the top readme, please.

**Comment by amilan17** [comment]
> But then link to this at least from the top readme, please.
Done.
