### ISSUE TITLE
update table 2-02 multilingual

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#21]
The current master branch contains two commits done to 2-02en which change the WMO306CD codes of the entries galionGAW to galion and aroEqAustralia to argoEqAustralia. These commits are:
https://github.com/wmo-im/wmds/commit/870e57281ec5f4b1d089362e93e508b837beae68
https://github.com/wmo-im/wmds/commit/206d9dac44deb6a4248db4d05095b75b7cafa982

We need to align the multilingual version to that change.

**Comment by HoratN** [comment]
created a new branch: https://github.com/wmo-im/wmds/tree/issue21 
and made the update

**Comment by efucile** [comment]
Created pull request. I am going to merge to master.
