### ISSUE TITLE
1-01-01 Add variables for radionuclides

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#212]
# **Branch**

https://github.com/wmo-im/wmds/blob/Issue212/tables_en/1-01-01.csv

# **Summary and Purpose**
Compared to the Common Code Table C-14, the WIGOS table 1-01-01 has significantly less variables for radionuclides. Based on the recommendation from a radionuclide expert at DWD, a list of useful radionuclide variables was compiled, which should be added to the code table.

# **Stakeholder(s)**
WG ACV

# **Proposal**

Add the following variables:

|notation|name|description|
|--|--|--|
|new id|Tritium [H-3]|IUPAC: n/a, PubChem CID: 24824, CAS Number: 10028-17-8|
|new id|Carbon [C-14]|IUPAC: n/a, PubChem CID: 26873, CAS Number: 14762-75-5|
|new id|Sodium [Na-22]|IUPAC: sodium-22, PubChem CID: 6328543, CAS Number: 13966-32-0|
|new id|Sodium [Na-24]|IUPAC: sodium-24, PubChem CID: 6335498, CAS Number: 13982-04-2|
|new id|Chlorine [Cl-38]|IUPAC: n/a, PubChem CID: 167013, CAS Number: 14158-34-0|
|new id|Potassium [K-40]|IUPAC: potassium-40, PubChem CID: 6328542, CAS Number: 13966-00-2|
|new id|Potassium [K-42]|IUPAC: potassium-42, PubChem CID: 11607897, CAS Number: 14378-21-3|
|new id|Scandium [Sc-46]|IUPAC: scandium-46, PubChem CID: 107673, CAS Number: 13967-63-0|
|new id|Chromium [Cr-51]|IUPAC: chromium-51, PubChem CID: 104786, CAS Number: 14392-02-0|
|new id|Manganese [Mn-53]|IUPAC: manganese-53, PubChem CID: 167227, CAS Number: 14999-33-8|
|new id|Manganese [Mn-56]|IUPAC: manganese-56, PubChem CID: 114694, CAS Number: 14681-52-8|
|new id|Iron [Fe-59]|IUPAC: iron-59, PubChem CID: 104784, CAS Number: 14596-12-4|
|new id|Cobalt [Co-56]|IUPAC: cobalt-56, PubChem CID: 166998, CAS Number: 14093-03-9|
|new id|Cobalt [Co-57]|IUPAC: cobalt-57, PubChem CID: 104851, CAS Number: 13981-50-5|
|new id|Cobalt [Co-58]|IUPAC: cobalt-58, PubChem CID: 104844, CAS Number: 13981-38-9|
|new id|Cobalt [Co-60]|IUPAC: cobalt-60, PubChem CID: 61492, CAS Number: 10198-40-0|
|new id|Zinc [Zn-65]|IUPAC: zinc-65, PubChem CID: 91574, CAS Number: 13982-39-3|
|new id|Gallium [Ga-67]|IUPAC: gallium-67, PubChem CID: 5464084, CAS Number: 14119-09-6|
|new id|Selenium [Se-75]|IUPAC: selenium-75, PubChem CID: 6328176, CAS Number: 14265-71-5|
|new id|Strontium [Sr-85]|IUPAC: strontium-85, PubChem CID: 5464271, CAS Number: 13967-73-2|
|new id|Strontium [Sr-89]|IUPAC: strontium-89, PubChem CID: 5388880, CAS Number: 14158-27-1|
|new id|Strontium [Sr-90]|IUPAC: strontium-90, PubChem CID: 5486204, CAS Number: 10098-97-2|
|new id|Strontium [Sr-91]|IUPAC: strontium-91, PubChem CID: 6337043, CAS Number: 14331-91-0|
|new id|Yttrium [Y-88]|IUPAC: yttrium-88, PubChem CID: 105173, CAS Number: 13982-36-0|
|new id|Yttrium [Y-90m]|Metastable (excited) state of yttrium-90 isotope, IUPAC: yttrium-90, PubChem CID: 104760, CAS Number: 10098-91-6
|new id|Zirconium [Zr-95]|IUPAC: zirconium-95, PubChem CID: 91573, CAS Number: 13967-71-0|
|new id|Niobium [Nb-95]|IUPAC: niobium-95, PubChem CID: 104776, CAS Number: 13967-76-5|
|new id|Molybdenum [Mo-99]|IUPAC: molybdenum-99, PubChem CID: 104976, CAS Number: 14119-15-4|
|new id|Technetium  [Tc-99m]|Metastable (excited) state of technetium-99 isotope, IUPAC: technetium-99, PubChem CID: 26476, CAS Number: 14133-76-7
|new id|Ruthenium [Ru-103]|IUPAC: ruthenium-103, PubChem CID: 104749, CAS Number: 13968-53-1|
|new id|Ruthenium [Ru-106]|IUPAC: ruthenium-106, PubChem CID: 26359, CAS Number: 13967-48-1|
|new id|Silver [Ag-108m]|Metastable (excited) state of silver-108 isotope, IUPAC: silver-108, PubChem CID: 167088, CAS Number: 14391-65-2
|new id|Silver [Ag-110m]|Metastable (excited) state of silver-110 isotope, IUPAC: silver-110, PubChem CID: 104828, CAS Number: 14391-76-5
|new id|Indium [In-111]|IUPAC: indium-111, PubChem CID: 5462099, CAS Number: 15750-15-9|
|new id|Tin [Sn-113]|IUPAC: tin-113, PubChem CID: 6335514, CAS Number: 13966-06-8|
|new id|Antimony [Sb-122]|IUPAC: antimony-122, PubChem CID: 6335836, CAS Number: 14374-79-9|
|new id|Antimony [Sb-124]|IUPAC: antimony-124, PubChem CID: 6335510, CAS Number: 14683-10-4|
|new id|Antimony [Sb-125]|IUPAC: antimony-125, PubChem CID: 6335317, CAS Number: 14234-35-6|
|new id|Tellurium [Te-132]|IUPAC: tellurium-132, PubChem CID: 6336614, CAS Number: 14234-28-7|
|new id|Iodine [I-126], elementary|IUPAC: n/a, PubChem CID: 161029, CAS Number: 14158-32-8|
|new id|Iodine [I-131], elementary|IUPAC: n/a, PubChem CID: 24855, CAS Number: 10043-66-0|
|new id|Iodine [I-132], elementary|IUPAC: n/a, PubChem CID: 104966, CAS Number: 14683-16-0|
|new id|Iodine [I-133], elementary|IUPAC: n/a, PubChem CID: 167176, CAS Number: 14834-67-4|
|new id|Xenon [Xe-133]|IUPAC: xenon-133, PubChem CID: 66376, CAS Number: 14932-42-4|
|new id|Caesium [Cs-134]|IUPAC: cesium-134, PubChem CID: 6335485, CAS Number: 13967-70-9|
|new id|Caesium [Cs-136]|IUPAC: cesium-136, PubChem CID: 6335316, CAS Number: 14234-29-8|
|new id|Caesium [Cs-137]|IUPAC: cesium-137, PubChem CID: 5486527, CAS Number: 10045-97-3|
|new id|Barium [Ba-133]|IUPAC: barium-133, PubChem CID: 5491664, CAS Number: 13981-41-4|
|new id|Barium [Ba-140]|IUPAC: barium-140, PubChem CID: 6335490, CAS Number: 14798-08-4|
|new id|Cerium [Ce-139]|IUPAC: cerium-139, PubChem CID: 166969, CAS Number: 13982-30-4|
|new id|Cerium [Ce-141]|IUPAC: cerium-141, PubChem CID: 104814, CAS Number: 13967-74-3|
|new id|Cerium [Ce-144]|IUPAC: cerium-144, PubChem CID: 26874, CAS Number: 14762-78-8|
|new id|Lanthanum [La-140]|IUPAC: lanthanum-140, PubChem CID: 104882, CAS Number: 13981-28-7|
|new id|Neodymium [Nd-147]|IUPAC: neodymium-147, PubChem CID: 114848, CAS Number: 14269-74-0|
|new id|Europium [Eu-152]|IUPAC: europium-152, PubChem CID: 104907, CAS Number: 14683-23-9|
|new id|Tantalum [Ta-182]|IUPAC: tantalum-182, PubChem CID: 161013, CAS Number: 13982-00-8|
|new id|Iridium [Ir-192]|IUPAC: iridium-192, PubChem CID: 66373, CAS Number: 14694-69-0|
|new id|Mercury [Hg-203]|IUPAC: mercury-203, PubChem CID: 104771, CAS Number: 13982-78-0|
|new id|Bismuth [Bi-212]|IUPAC: bismuth-212, PubChem CID: 6335500, CAS Number: 14913-49-6|
|new id|Bismuth [Bi-213]|IUPAC: bismuth-213, PubChem CID: 6337093, CAS Number: 15776-20-2|
|new id|Lead [Pb-212]|IUPAC: lead-212, PubChem CID: 6335491, CAS Number: 15092-94-1|
|new id|Lead [Pb-214]|IUPAC: lead-214, PubChem CID: 6328551, CAS Number: 15067-28-4|
|new id|Radium [Ra-226]|IUPAC: radium-226, PubChem CID: 9877911, CAS Number: 13982-63-3|
|new id|Actinium [Ac-228]|IUPAC: actinium-228, PubChem CID: 105063, CAS Number: 14331-83-0|
|new id|Thorium [Th-232]|IUPAC: thorium-232, PubChem CID: 11817119, CAS Number: n/a|
|new id|Uranium [U-234]|IUPAC: uranium-234, PubChem CID: 61704, CAS Number: 13966-29-5|
|new id|Uranium [U-235]|IUPAC: uranium-235, PubChem CID: 61784, CAS Number: 15117-96-1|
|new id|Uranium [U-238]|IUPAC: uranium-238, PubChem CID: n/a, CAS Number: n/a|
|new id|Plutonium [Pu-238]|IUPAC: plutonium-238, PubChem CID: 61709, CAS Number: 13981-16-3|
|new id|Neptunium [Np-239]|IUPAC: neptunium-239, PubChem CID: 104958, CAS Number: 13968-59-7|
|new id|Americium [Am-241]|IUPAC: americium-241, PubChem CID: 104726, CAS Number: 14596-10-2|
|new id|Sum of Plutonium [Pu-239] and [Pu-240]|Sum of Plutonium isotopes: Pu-239 and Pu-240, IUPAC: plutonium-239, PubChem CID: 61782, CAS Number: 15117-48-3 and IUPAC: plutonium-239, PubChem CID: 61782, CAS Number: 15117-48-3
|new id|Gold [Au-198]|IUPAC: gold-198, PubChem CID: 66274, CAS Number: 10043-49-9|

Update definitions of existing radionuclide variables:

|notation|name|description (old)|description (new)
|--|--|--|--|
|219|Beryllium [Be-7]||IUPAC: beryllium-7, PubChem CID: 6335489, CAS Number: 13966-02-4
|221|Krypton [Kr-85]|Krypton (Kr-85 isotope)|IUPAC: krypton-85, PubChem CID: 104816, CAS Number: 13983-27-2
|222|Lead [Pb-210]|Lead (Pb-210 isotope)|IUPAC: lead-210, PubChem CID: 6328175, CAS Number: 14255-04-0
|223|Radon [Rn-222]|Radon (Rn-222 isotope)|IUPAC: radon-222, PubChem CID: 61773, CAS Number: 14859-67-7

# **Reason**
These additions would allow for a mapping between radionuclide variables provided by WIGOS and C-14.

---
Original comment:

**Branch**
* https://github.com/wmo-im/wmds/tree/Issue212
* https://github.com/wmo-im/wmds/compare/Issue212

**Summary and Purpose**
Compared to the Common Code Table C-14, the WIGOS table 1-01-01 lacks variables for radionuclides.

**Proposal**
Extend atmospheric composition vocabulary with path Atmosphere\Radionuclide to ensure interoperability with Common Code Table C-14.
New variables: [1-01-01 new radionuclide variables.xlsx](https://github.com/wmo-im/wmds/files/6516139/1-01-01.new.radionuclide.variables.xlsx)

**Reason**
These additions would allow for a mapping between radionuclide variables provided by WIGOS and C-14.

**Comment by joergklausen** [comment]
@fstuerzl Create branch
@ferrighi @amilan17 Please review branch

**Comment by gaochen-larc** [comment]
Wondering about the hierarchy of the branches:
Some have "gaseous", "aerosol", "organic". or "inorganic" terms within the parenthesis.  To me, the phase of the measurement is important, i.e., particulate or gas phase.   To ensure proper data use, maybe the phase description should be required.  

Also, some can be better organized:
'Atmosphere\Radionuclide\Iodine [I-133], gaseous
Atmosphere\Radionuclide\Iodine [I-133], organic
Atmosphere\Radionuclide\Iodine [I-133], gaseous, organic
Atmosphere\Radionuclide\Iodine [I-133], aerosol

Wondering if this can be simplified to just two branches:
'Atmosphere\Radionuclide\Iodine [I-133], gaseous
Atmosphere\Radionuclide\Iodine [I-133], aerosol

Finally, not sure if these variables can be used to describe isotopic ratio measurements...

**Comment by gaochen-larc** [comment]
Propose to add attributes to define the phase of radionuclides, i.e., gas and PM (particulate matter).  Any comments?
Looking for input on representations of isotopic ratios.  Should we add a new set of variables?

**Comment by joergklausen** [comment]
The problem here is that a property of the variable, namely its radioactivity, is included in the path as a grouping element, but that another property, namely the 'sub-domain' (gasesous, aerosol) are used in the organization of the tree as well ... and we can't have both. Yes, we could abandon the path structure altogether and uses entirely different approaches to organize variables, but I am not supportive of this at the moment. The organization of the variables in a tree with domains (atmosphere, terrestrial, etc) and sub-domains (atmosphere/gas, ./aerosol, ./.) has served users quite well in the past, even though it leads to certain ambiguities. A discussion could be had if the radioactivity is a decisive aspect here or not. If yes, then I see indeed 2 options:
1. add the phase to the variable name as is done now, e.g, Atmosphere\Radionuclide\Iodine [I-133], aerosol
2. add radionuclides as part of the path *under* the phase, e.g., Atmosphere\Aerosol\Radionuclide\Iodine [I-133], organic
If radioactivity is not something crucial, then option 2 without \Radionuclide would suffice. Traditionally, radionuclides were considered to be ancillary variables in GAW. As long as the codes.wmo.int registry only lists the endpoint as the name, option 2 could lead to duplicate names, although the notations and descriptions would remain unique.

The notion of 'organic' vs 'inorganic' may be important, I am inclined to not drop this, It paraphrases the nature of the chemical bond and hence its properties.

Isotopic ratios cannot be described in this way. Either, the individual isotopes need to be listed as separate observed variables, or specific ratios need to be defined explicitly as observed variables. Conventional wisdom would indicate that if you observe, e.g.,  C-14 in air, you can derive an isotopic ratio because you would either also observe the total C concentration in air or assume it is relatively constant (and known).

**Comment by markusfiebig** [comment]
Having "Radionuclide" as category directly under "Atmosphere" makes the variable tree ambigeous. I would therefore support @joergklausen option 2, i.e. have radionuclide as category below phase, or drop radionuclide altogether. In the latter case, we could also have "radionuclide" as attribute for clarification and search criterion.

**Comment by fstuerzl** [comment]
The radionuclide variables that are currently in the code list are categorised directly under "Atmosphere", e.g. \Atmosphere\Radionuclide\Radon [Rn-222], as @joergklausen described in option 1. I assumed, that these variables describe measurements of radionuclides "in air and aerosol"/"gas and particle phase". Can this be confirmed?
If this is true, it might make more sense to follow option 1 and treat this branch more like the POP branch.

 
Also, the attributes that were mentioned before by @gaochen-larc are not used throughout the whole table, but only appear in variables for iodine isotopes, as shown in the following list. 

Code table C-14 entry (meaning_en)
-- |
Iodine 129
Iodine 129 elementary gaseous
Iodine 129 organic bounded
Iodine 131
Iodine 131 elementary gaseous
Iodine 131 organic bounded
Iodine 131 gaseous elementary   and organic bounded
Iodine 131 aerosol
Iodine 132
Iodine 132 elementary gaseous
Iodine 132 organic bounded
Iodine 132 gaseous elementary   and organic bounded
Iodine 132 aerosol
Iodine 133
Iodine 133 elementary gaseous
Iodine 133 organic bounded
Iodine 133 gaseous elementary   and organic bounded
Iodine 133 aerosol
Iodine 134
Iodine 134 elementary gaseous
Iodine 134 organic bounded
Iodine 135
Iodine 135 elementary gaseous
Iodine 135 organic bounded
Iodine 135 gaseous elementary   and organic bounded
Iodine 135 aerosol

**Comment by fstuerzl** [comment]
Branch created: https://github.com/wmo-im/wmds/blob/Issue212/tables_en/1-01-01.csv
(provisionally for a better overview, does not include paths yet)

**Comment by gaochen-larc** [comment]
> The radionuclide variables that are currently in the code list are categorised directly under "Atmosphere", e.g. \Atmosphere\Radionuclide\Radon [Rn-222], as @joergklausen described in option 1. I assumed, that these variables describe measurements of radionuclides "in air and aerosol"/"gas and particle phase". Can this be confirmed?
> If this is true, it might make more sense to follow option 1 and treat this branch more like the POP branch.
> 
> Also, the attributes that were mentioned before by @gaochen-larc are not used throughout the whole table, but only appear in variables for iodine isotopes, as shown in the following list.
> 
> Code table C-14 entry (meaning_en)
> Iodine 129
> Iodine 129 elementary gaseous
> Iodine 129 organic bounded
> Iodine 131
> Iodine 131 elementary gaseous
> Iodine 131 organic bounded
> Iodine 131 gaseous elementary and organic bounded
> Iodine 131 aerosol
> Iodine 132
> Iodine 132 elementary gaseous
> Iodine 132 organic bounded
> Iodine 132 gaseous elementary and organic bounded
> Iodine 132 aerosol
> Iodine 133
> Iodine 133 elementary gaseous
> Iodine 133 organic bounded
> Iodine 133 gaseous elementary and organic bounded
> Iodine 133 aerosol
> Iodine 134
> Iodine 134 elementary gaseous
> Iodine 134 organic bounded
> Iodine 135
> Iodine 135 elementary gaseous
> Iodine 135 organic bounded
> Iodine 135 gaseous elementary and organic bounded
> Iodine 135 aerosol


Two more: 

Tritium [H-3],   organic
Tritium [H-3], inorganic

**Comment by gaochen-larc** [comment]
Considering the number of measurements and data sets, it may be reasonable to just list the isotope, not list the phase or chemical makeup (i.e., inorganic or organic).    Majority of the isotopes is "attached" to the particles.  A few, e.g., Radon, are only in gas phase.  Some others can exist both in gas phase or on particles.  Researchers often use Be-7 and Be-10 or Pb-210 as tracers to study transport processes and/or evaluate deposition rates.  Other studies focused on phase transformation, which would need both gas phase and particulate measurements.  I would assume one would discover both measurements if the data products are tagged by the isotope themselves, without further specifying gas phase or PM...  For radioactive safety point of view, the important measure is radioactivity, not exact phase of the measurement...  Hope this argument makes some sense.  Definitely need expert to join the discussion.

**Comment by gaochen-larc** [comment]
The term "m" or "metastable" is to describe the lifetime of the isotope, but not directly related to the measurement.  It should be dropped.  
Inconsistency identified: Atmosphere\Radionuclide\Lead[Pb-210], | Lead [Pb-211], Lead (Pb-211 isotope)
Additions: Be-7, Pb-211, and Rn-222

**Comment by amilan17** [comment]
Waiting for feedback from other experts (Sibylle K and Sebastien) and proceed in about a week.

**Comment by joergklausen** [comment]
@sebvi What is the status of this, please? Can it be moved forward?

**Comment by fstuerzl** [comment]
The issue can be moved forward, since Sibylle Krebber from DWD confirmed that all the variables listed above are used at DWD. 

> Regarding the radionuclides, I spoke to a colleague and he confirmed that all radionuclides are needed.
For the monitoring of the radioactivity in the atmosphere air samples are evaluated with the help of gamma-ray spectroscopy. And thereby each of the radionuclides could be detected theoretically.

**Comment by fstuerzl** [comment]
Table with recommendations from DWD experts: [1-01-01 new radionuclide variables_DWD.xlsx](https://github.com/wmo-im/wmds/files/6553658/1-01-01.new.radionuclide.variables_DWD.xlsx)

This reduces the list of radionuclide entries to circa 80 variables.

**Comment by gaochen-larc** [comment]
I think the total number is 76.  There are a few them having multiple decay pathways.  For example, Am-241 has both alpha and gamma radiations...

**Comment by fstuerzl** [comment]
Reduced list included in branch (see: https://github.com/wmo-im/wmds/compare/Issue212) without specifying a matrix

**Comment by fstuerzl** [comment]
Consolidated proposal:

---

# **Branch**

https://github.com/wmo-im/wmds/blob/Issue212/tables_en/1-01-01.csv

# **Summary and Purpose**
Compared to the Common Code Table C-14, the WIGOS table 1-01-01 has significantly less variables for radionuclides. Based on the recommendation from a radionuclide expert at DWD, a list of useful radionuclide variables was compiled, which should be added to the code table.

# **Stakeholder(s)**
WG ACV

# **Proposal**

Add the following variables:

|notation|name|description|
|--|--|--|
|new id|Tritium [H-3]|IUPAC: n/a, PubChem CID: 24824, CAS Number: 10028-17-8|
|new id|Carbon [C-14]|IUPAC: n/a, PubChem CID: 26873, CAS Number: 14762-75-5|
|new id|Sodium [Na-22]|IUPAC: sodium-22, PubChem CID: 6328543, CAS Number: 13966-32-0|
|new id|Sodium [Na-24]|IUPAC: sodium-24, PubChem CID: 6335498, CAS Number: 13982-04-2|
|new id|Chlorine [Cl-38]|IUPAC: n/a, PubChem CID: 167013, CAS Number: 14158-34-0|
|new id|Potassium [K-40]|IUPAC: potassium-40, PubChem CID: 6328542, CAS Number: 13966-00-2|
|new id|Potassium [K-42]|IUPAC: potassium-42, PubChem CID: 11607897, CAS Number: 14378-21-3|
|new id|Scandium [Sc-46]|IUPAC: scandium-46, PubChem CID: 107673, CAS Number: 13967-63-0|
|new id|Chromium [Cr-51]|IUPAC: chromium-51, PubChem CID: 104786, CAS Number: 14392-02-0|
|new id|Manganese [Mn-53]|IUPAC: manganese-53, PubChem CID: 167227, CAS Number: 14999-33-8|
|new id|Manganese [Mn-56]|IUPAC: manganese-56, PubChem CID: 114694, CAS Number: 14681-52-8|
|new id|Iron [Fe-59]|IUPAC: iron-59, PubChem CID: 104784, CAS Number: 14596-12-4|
|new id|Cobalt [Co-56]|IUPAC: cobalt-56, PubChem CID: 166998, CAS Number: 14093-03-9|
|new id|Cobalt [Co-57]|IUPAC: cobalt-57, PubChem CID: 104851, CAS Number: 13981-50-5|
|new id|Cobalt [Co-58]|IUPAC: cobalt-58, PubChem CID: 104844, CAS Number: 13981-38-9|
|new id|Cobalt [Co-60]|IUPAC: cobalt-60, PubChem CID: 61492, CAS Number: 10198-40-0|
|new id|Zinc [Zn-65]|IUPAC: zinc-65, PubChem CID: 91574, CAS Number: 13982-39-3|
|new id|Gallium [Ga-67]|IUPAC: gallium-67, PubChem CID: 5464084, CAS Number: 14119-09-6|
|new id|Selenium [Se-75]|IUPAC: selenium-75, PubChem CID: 6328176, CAS Number: 14265-71-5|
|new id|Strontium [Sr-85]|IUPAC: strontium-85, PubChem CID: 5464271, CAS Number: 13967-73-2|
|new id|Strontium [Sr-89]|IUPAC: strontium-89, PubChem CID: 5388880, CAS Number: 14158-27-1|
|new id|Strontium [Sr-90]|IUPAC: strontium-90, PubChem CID: 5486204, CAS Number: 10098-97-2|
|new id|Strontium [Sr-91]|IUPAC: strontium-91, PubChem CID: 6337043, CAS Number: 14331-91-0|
|new id|Yttrium [Y-88]|IUPAC: yttrium-88, PubChem CID: 105173, CAS Number: 13982-36-0|
|new id|Yttrium [Y-90m]||
|new id|Zirconium [Zr-95]|IUPAC: zirconium-95, PubChem CID: 91573, CAS Number: 13967-71-0|
|new id|Niobium [Nb-95]|IUPAC: niobium-95, PubChem CID: 104776, CAS Number: 13967-76-5|
|new id|Molybdenum [Mo-99]|IUPAC: molybdenum-99, PubChem CID: 104976, CAS Number: 14119-15-4|
|new id|Technetium  [Tc-99m]||
|new id|Ruthenium [Ru-103]|IUPAC: ruthenium-103, PubChem CID: 104749, CAS Number: 13968-53-1|
|new id|Ruthenium [Ru-106]|IUPAC: ruthenium-106, PubChem CID: 26359, CAS Number: 13967-48-1|
|new id|Silver [Ag-108m]||
|new id|Silver [Ag-110m]||
|new id|Indium [In-111]|IUPAC: indium-111, PubChem CID: 5462099, CAS Number: 15750-15-9|
|new id|Tin [Sn-113]|IUPAC: tin-113, PubChem CID: 6335514, CAS Number: 13966-06-8|
|new id|Antimony [Sb-122]|IUPAC: antimony-122, PubChem CID: 6335836, CAS Number: 14374-79-9|
|new id|Antimony [Sb-124]|IUPAC: antimony-124, PubChem CID: 6335510, CAS Number: 14683-10-4|
|new id|Antimony [Sb-125]|IUPAC: antimony-125, PubChem CID: 6335317, CAS Number: 14234-35-6|
|new id|Tellurium [Te-132]|IUPAC: tellurium-132, PubChem CID: 6336614, CAS Number: 14234-28-7|
|new id|Iodine [I-126], elementary|IUPAC: n/a, PubChem CID: 161029, CAS Number: 14158-32-8|
|new id|Iodine [I-131], elementary|IUPAC: n/a, PubChem CID: 24855, CAS Number: 10043-66-0|
|new id|Iodine [I-132], elementary|IUPAC: n/a, PubChem CID: 104966, CAS Number: 14683-16-0|
|new id|Iodine [I-133], elementary|IUPAC: n/a, PubChem CID: 167176, CAS Number: 14834-67-4|
|new id|Xenon [Xe-133]|IUPAC: xenon-133, PubChem CID: 66376, CAS Number: 14932-42-4|
|new id|Caesium [Cs-134]|IUPAC: cesium-134, PubChem CID: 6335485, CAS Number: 13967-70-9|
|new id|Caesium [Cs-136]|IUPAC: cesium-136, PubChem CID: 6335316, CAS Number: 14234-29-8|
|new id|Caesium [Cs-137]|IUPAC: cesium-137, PubChem CID: 5486527, CAS Number: 10045-97-3|
|new id|Barium [Ba-133]|IUPAC: barium-133, PubChem CID: 5491664, CAS Number: 13981-41-4|
|new id|Barium [Ba-140]|IUPAC: barium-140, PubChem CID: 6335490, CAS Number: 14798-08-4|
|new id|Cerium [Ce-139]|IUPAC: cerium-139, PubChem CID: 166969, CAS Number: 13982-30-4|
|new id|Cerium [Ce-141]|IUPAC: cerium-141, PubChem CID: 104814, CAS Number: 13967-74-3|
|new id|Cerium [Ce-144]|IUPAC: cerium-144, PubChem CID: 26874, CAS Number: 14762-78-8|
|new id|Lanthanum [La-140]|IUPAC: lanthanum-140, PubChem CID: 104882, CAS Number: 13981-28-7|
|new id|Neodymium [Nd-147]|IUPAC: neodymium-147, PubChem CID: 114848, CAS Number: 14269-74-0|
|new id|Europium [Eu-152]|IUPAC: europium-152, PubChem CID: 104907, CAS Number: 14683-23-9|
|new id|Tantalum [Ta-182]|IUPAC: tantalum-182, PubChem CID: 161013, CAS Number: 13982-00-8|
|new id|Iridium [Ir-192]|IUPAC: iridium-192, PubChem CID: 66373, CAS Number: 14694-69-0|
|new id|Mercury [Hg-203]|IUPAC: mercury-203, PubChem CID: 104771, CAS Number: 13982-78-0|
|new id|Bismuth [Bi-212]|IUPAC: bismuth-212, PubChem CID: 6335500, CAS Number: 14913-49-6|
|new id|Bismuth [Bi-213]|IUPAC: bismuth-213, PubChem CID: 6337093, CAS Number: 15776-20-2|
|new id|Lead [Pb-212]|IUPAC: lead-212, PubChem CID: 6335491, CAS Number: 15092-94-1|
|new id|Lead [Pb-214]|IUPAC: lead-214, PubChem CID: 6328551, CAS Number: 15067-28-4|
|new id|Radium [Ra-226]|IUPAC: radium-226, PubChem CID: 9877911, CAS Number: 13982-63-3|
|new id|Actinium [Ac-228]|IUPAC: actinium-228, PubChem CID: 105063, CAS Number: 14331-83-0|
|new id|Thorium [Th-232]|IUPAC: thorium-232, PubChem CID: 11817119, CAS Number: n/a|
|new id|Uranium [U-234]|IUPAC: uranium-234, PubChem CID: 61704, CAS Number: 13966-29-5|
|new id|Uranium [U-235]|IUPAC: uranium-235, PubChem CID: 61784, CAS Number: 15117-96-1|
|new id|Uranium [U-238]|IUPAC: uranium-238, PubChem CID: n/a, CAS Number: n/a|
|new id|Plutonium [Pu-238]|IUPAC: plutonium-238, PubChem CID: 61709, CAS Number: 13981-16-3|
|new id|Neptunium [Np-239]|IUPAC: neptunium-239, PubChem CID: 104958, CAS Number: 13968-59-7|
|new id|Americium [Am-241]|IUPAC: americium-241, PubChem CID: 104726, CAS Number: 14596-10-2|
|new id|Sum of Plutonium [Pu-239] and [Pu-240]||
|new id|Gold [Au-198]|IUPAC: gold-198, PubChem CID: 66274, CAS Number: 10043-49-9|


# **Reason**
These additions would allow for a mapping between radionuclide variables provided by WIGOS and C-14.

**Comment by ferrighi** [comment]
@fstuerzl just a question before validation. Metastable and sum do not have a definition, is that right?  Other than this, I am fine with the proposal.

**Comment by gaochen-larc** [comment]
Proposed description:

Yttrium [Y-90m]: A nuclear isomer of IUPAC: yttrium-90, PubChem CID: 104760 CAS Number: 10098-91-6 
Technetium [Tc-99m]: A nuclear isomer of IUPAC: technetium-99, PubChem CID: 26476, CAS Number: 14133-76-7 
Silver [Ag-108m]: A nuclear isomer of IUPAC: silver-108, PubChem CID: 167088, CAS Number: 14391-65-2 
Silver [Ag-110m]: A nuclear isomer of IUPAC: silver-110, PubChem CID: 104828, CAS Number: 14391-76-5

Sum of Plutonium [Pu-239] and [Pu-240]: Sum of Plutonium isotopes: Pu-239 and Pu-240.
Not sure if Pu-239 and Pu-240 are already in the code list.  If not,

Pu-239: IUPAC: plutonium-239, PubChem CID: 61782, CAS Number: 15117-48-3
Pu-240: IUPAC: plutonium-240, PubChem CID: 104728, CAS Number: 14119-33-6

These descriptions should be verified.

**Comment by gaochen-larc** [comment]
Probably not right now, it would be useful to have a tag for fusion products

**Comment by sebvi** [comment]
@gaochen-larc "isomer" is not the correct term, I suspect you probably mean "isotope"

**Comment by gaochen-larc** [comment]
> @gaochen-larc "isomer" is not the correct term, I suspect you probably mean "isotope"
> 
> I would change the descriptions to "A metastable isotope of ..."

It is the isomer of the nucleus: https://en.wikipedia.org/wiki/Nuclear_isomer.  It is the same isotope but some neutrons or protons are at higher energy state.   I used the term "nuclear isomer" was to avoid confusion with molecular isomers...

**Comment by sebvi** [comment]
Oh! I did not realized we were adding excited nuclear states! I thought metastable was referring to isotopes stability towards radioactive decays regardless of the nuclear energy state. Then your descriptions are correct.

(that said, using "isomer", which means "equal part", is a really really bad choice! )

**Comment by gaochen-larc** [comment]
> (that said, using "isomer", which means "equal part", is a really really bad choice! )

hahaha, it just says they have the same number of protons and neutrons...

**Comment by joergklausen** [comment]
The most appropriate expression we found is "Metastable (excited) state of yttrium-90 isotope with a specific half-life for de-excitation, IUPAC: yttrium-90, PubChem CID: 104760, CAS Number: 10098-91-6"

**Comment by gaochen-larc** [comment]
> The most appropriate expression we found is "Metastable (excited) state of yttrium-90 isotope with a specific half-life for de-excitation, IUPAC: yttrium-90, PubChem CID: 104760, CAS Number: 10098-91-6"

What about: "Metastable (excited) state of yttrium-90 isotope, IUPAC: yttrium-90, PubChem CID: 104760, CAS Number: 10098-91-6"?

**Comment by joergklausen** [comment]
I am okay with the slightly shorter version. @fstuerzl Please finalize.

**Comment by fstuerzl** [comment]
Descriptions added as proposed by @gaochen-larc and @joergklausen, see: https://github.com/wmo-im/wmds/commit/4ae6d9eb96c3269a2b72be082e009f17bbdf9c7d

**Comment by gaochen-larc** [comment]
I confirm the validity of this branch.

**Comment by amilan17** [comment]
@fstuerzl please update issue summary. Definitions for 219-223 are modified and I don't see this described in this issue.
