### ISSUE TITLE
1-01-01 Add variables for greenhouse gases

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#213]
**Branch**
https://github.com/wmo-im/wmds/tree/Issue213

**Summary and Purpose**
Variables for greenhouse gases are missing in table 1-01-01.

**Proposal**
Add the following variables to the WIGOS table for observed variables (atmosphere):

Path | Name | Description
-- | -- | --
Atmosphere\Gas\Greenhouse Gas\CFCs\Cl3CCF3   (1,1,1-trichloro-2,2,2-trifluoroethane, CFC-113a) | Cl3CCF3   (1,1,1-trichloro-2,2,2-trifluoroethane, CFC-113a) |  IUPAC: 1,1,1-trichloro-2,2,2-trifluoroethane, PubChem CID: 9635, CAS Number: 354-58-5
Atmosphere\Gas\Greenhouse Gas\Halon\CBr2F2 (dibromodifluoromethane, Halon 1202) | CBr2F2 (dibromodifluoromethane, Halon 1202) | IUPAC: dibromo(difluoro)methane, PubChem CID: 6382, CAS Number: 75-61-6
Atmosphere\Gas\Greenhouse Gas\Halon\C2Br2F4 (1,2-dibromo-1,1,2,2-tetrafluoroethane, Halon 2402) | C2Br2F4 (1,2-dibromo-1,1,2,2-tetrafluoroethane, Halon 2402) | IUPAC: 1,2-dibromo-1,1,2,2-tetrafluoroethane, PubChem CID: 31301, CAS Number: 124-73-2 (1,2-isomer), 25497-30-7 (1,1-isomer)
Atmosphere\Gas\Greenhouse Gas\HCFCs\C2H3Cl2F (1,1-dichloro-2-fluoroethane, HCFC-141a) | C2H3Cl2F (1,1-dichloro-2-fluoroethane, HCFC-141a) | IUPAC: 1,1-dichloro-2-fluoroethane, PubChem CID: 67936, CAS Number: 430-53-5, 25167-88-8

**Reason**
These variables are provided by the common code table C-14, but not included in the WIGOS vocabulary. They can easily be integrated into the table and the existing path structure as proposed above.

(EDIT: descriptions)

**Comment by joergklausen** [comment]
Include CAS and IUPAC numbers to the description. @gaochen_larc will support this.
@fstuerzl Create branch
@joergklausen @gaochen_larc confirm branch

**Comment by joergklausen** [comment]
Example for description
IUPAC: 1,1,1-trichloro-2,2,2-trifluoroethane, PubChem CID: 9635, CAS Number: 354-58-5

**Comment by fstuerzl** [comment]
Branch: https://github.com/wmo-im/wmds/tree/Issue213
View differences: https://github.com/wmo-im/wmds/commit/22075106b2d872b4f2286a8f0c765d55f655c3fb#diff-160fbee712206a9a655a755c35b0b78b

@joergklausen , @gaochen-larc, please confirm branch (and check descriptions)

**Comment by gaochen-larc** [comment]
Looks good!  Thanks!
One general question: do we really need the chemical formula before the parenthesis?  As shown in the table, one formula can represent multiple molecules.   The content in the parenthesis actually identifies the compound.  We may need to discuss this topic at little bit.   Also, should we just put one name in the name column and put the alias in the description or we can create another column for alias...

**Comment by joergklausen** [comment]
Chemical formulas are included to finding related chemicals in an ordered list. I would also recommend to stay with the current use of more than one name. These are common names that people relate to. It's all in an effort to provide assistance to users wanting to find a specific molecule.
Branch is valid.

**Comment by amilan17** [comment]
@joergklausen  @fstuerzl 

These additions don't have notation. Please add numbers and let me know so I can merge this branch with the validation branch

17b091a

**Comment by joergklausen** [comment]
@amilan17 @fstuerzl In principle I agree, of course, the notations should be there. These notations are produced by OSCAR/Surface, though, and there is a circular problem: For governance reasons, we can't add them yet, and for technical reasons, we have to add them to get the IDs. I think, Enrico was okay if we add them with a note ' (provisional)'.

**Comment by amilan17** [comment]
What were the steps in the previous workflow? 

1.  add 'provisional' notation values - to submit amendments for approval
2.  Update OSCAR/Surface with new codes and obtain new notation values - after amendment approval
3.  Modify table with notation values as assigned by OSCAR - before publication

**Comment by joergklausen** [comment]
similar ;-)

**Comment by fstuerzl** [comment]
@amilan17 Could you confirm that we can add the variables (provisionally) on OSCAR/Surface?

**Comment by amilan17** [comment]
yes, I find out. Is it possible to assign notations 'provisionally' in OSCAR/Surface instead?

**Comment by fstuerzl** [comment]
Since the notation from the code list serves as an ID in the database it is complicated to change them later.
