### ISSUE TITLE
2-02 Affiliation with programs/networks on "parent level"

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#214]
**Branch:** [https://github.com/wmo-im/wmds/tree/Issue214](https://github.com/wmo-im/wmds/tree/Issue214)

**Decision:** all parent terms are invalid if standalone

\*\*\*\*\*\*\*\*\*\*\*

_original_

The entries in table 2-02 (Programme/network affiliation) are structured with paths. As opposed to variables and methods, this table does not only contain the "endpoints" of the paths, but also every parent entry, even if it is only a collective term. Each of these table entries can theoretically be added to a station as a program or network affiliation.  
In the OSCAR application some of the terms are blocked. They are only useful for searching but cannot be added (at least not in the application), as shown in the following figure:  

![screenshot_program_affiliation1](https://user-images.githubusercontent.com/72029328/102218963-17a12d00-3edf-11eb-9450-4337de05d7e6.PNG)

Here, in the subcategory "GAW" only the path endpoints can be selected.  
This approach is not consistent, since other categories allow also the selection of parent entries, as seen below:  

![screenshot_program_affiliation2](https://user-images.githubusercontent.com/72029328/102219179-6949b780-3edf-11eb-81b7-6ce6d85c2047.PNG)

For networks this may be reasonable, whereas simple collective terms such as "GAW Contributing networks" or "GOS Other elements" should not be an option for a user to add as a program affiliation and therefore not be a part of the table.

**Summary and Purpose**  
The register "Programme/network affiliation" (table 2-02) contains all path elements not only the "endpoints", which means even unspecific terms can be added as a program affiliation. This is different from the approach in OSCAR.

**Proposal**  
A consistent approach needs to be decided. Possible options are:

1.  All entries on parent level are removed from the table (and blocked in OSCAR).
2.  Some entries on parent level, which should not be added as a program or network affiliation, are removed from the table (and blocked in OSCAR), while others remain.

**Comment by fstuerzl** [comment]
Solution, as discussed with WMO (@echarpent, @nunelf): Remove all node entries from code list.
Branch created: https://github.com/wmo-im/wmds/tree/Issue214
View differences: https://github.com/wmo-im/wmds/commit/5f47d73344a5b37ecdcc6d306f9303cd5748a01f#diff-a066c50c20373fc15bcd759e58529c31867ae12caecaa7d36ad7627f5e689622

@echarpent, @joergklausen, please review the branch.

**Comment by joergklausen** [comment]
Branch looks good.
@amilan17 Please make sure the GALION entry is included as an entry directly under GAW according to #189.

**Comment by amilan17** [comment]
@fstuerzl - as discussed earlier, please remove all "invalid" terms from the table.

**Comment by fstuerzl** [comment]
@amilan17 invalid terms are removed from this branch
