### ISSUE TITLE
2-02 Add programme /network affiliation ANTON(S)

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#217]
**Summary and Purpose**
In connection with issue #214, (removal of node entries from the code list), the branch for the Antarctic Observing Network ANTON needs to be divided into ANTON(S) for surface stations and ANTON(T). 

**Proposal**
Add an entry ANTON(S) to the code list for programme affiliations. 

**Branch**
https://github.com/wmo-im/wmds/tree/Issue217
View differences: https://github.com/wmo-im/wmds/commit/81638e6e61b8b8f6df30d80bdc86d3558bee8e85#diff-a066c50c20373fc15bcd759e58529c31867ae12caecaa7d36ad7627f5e689622

**Comment by fstuerzl** [comment]
@joergklausen, @echarpent, please review the proposal and the branch.

**Comment by rodicanitu** [comment]
I'm not clear about the introduction of ANTON(S) vs ANTON(T). Is it necessary? Who/what drives the need? There might be value in differentiating between stations which operate in the region under the Antarctic Treaty and those in the sub-Antarctic area.

**Comment by fstuerzl** [comment]
@rodicanitu, sorry for not being more precise in the proposal. Let me explain how this issue came up: In a discussion with @joergklausen, @echarpent, @nuneslf about the structure of the programme affiliation table (#214) it was recommended to deprecate node entries from this code list.
Therefore we came to the conclusion that in this case the current structure
\WIGOS\GOS\GOS Surface networks\ANTON
\WIGOS\GOS\GOS Surface networks\ANTON\ANTON(T)
should be changed to
\WIGOS\GOS\GOS Surface networks\ANTON\ANTON(S)
\WIGOS\GOS\GOS Surface networks\ANTON\ANTON(T),
So a new entry for ANTON(S) is needed.

**Comment by joergklausen** [comment]
Branch confirmed to contain changes as agreed with @echarpent and @nuneslf.

**Comment by rodicanitu** [comment]
Please see Etienne's comment on #214; change not needed

**Comment by rodicanitu** [comment]
I spoke with Etienne and agreed that this item should be closed as proposed. It may never be used, but there is no risk to creating ANTON(S).
item recommended to be closed.
