### ISSUE TITLE
2-02 Add programme affiliation NOAAGML to replace ESRLCCG 

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#218]
**Branch** 
https://github.com/wmo-im/wmds/tree/Issue218

**Summary and Purpose**
It was requested to add NOAAGML as a GAW Contributing network to the codelist for programme/network affiliation. This should replace the existing table entry ESRLCCG (GAW Other elements).

**Stakeholder(s)**
John Mund 

**Proposal**
Create a new entry NOAAGML and deprecate the entry ESRLCCG, which will be superseded by NOAAGML.

notation| path | name | description
-- | -- | -- | --
NOAAGML | \WIGOS\GAW\GAW Contributing networks\NOAAGML | NOAAGML | 
ESRLCCG |  \WIGOS\GAW\GAW Contributing networks\ESRLCCG (superseded by NOAAGML) | ESRLCCG (superseded by NOAAGML) | NOAA-ESRL (CCG)

**Comment by fstuerzl** [comment]
Branch created: https://github.com/wmo-im/wmds/blob/Issue218/tables_en/2-02.csv

@tarasova-wmo, John, please review the proposal (and add a description for the new entry NOAAGML).

**Comment by tarasova-wmo** [comment]
the proposal is fine with me

**Comment by amilan17** [comment]
need confirmation that NOAAGML is NOAA Global Monitoring Laboratory

**Comment by john-mund** [comment]
Yes, the proposal is fine with me too and NOAAGML is NOAA Global Monitoring Laboratory.

Perhaps change the name slightly to fit the naming convention of other entries

notation:NOAAGML
path:\WIGOS\GAW\GAW Contributing networks\NOAA-GML
name:NOAA-GML
description:NOAA Global Monitoring Laboratory

**Comment by fstuerzl** [comment]
Thank you, @john-mund. I updated the branch and included your changes: https://github.com/wmo-im/wmds/commit/90eb6ada9d9ed274025e1ab972d4e22e61016d09#diff-a066c50c20373fc15bcd759e58529c31867ae12caecaa7d36ad7627f5e689622

**Comment by joergklausen** [comment]
branch validated

**Comment by amilan17** [comment]
@fstuerzl @joergklausen 

This branch needs to be updated to be inline with how we handle superseded values.

**Comment by fstuerzl** [comment]
@amilan17, ESRLCCG is removed from the table, and added to the superseded.txt file:
https://github.com/wmo-im/wmds/commit/01826feba0c1dcf12505c332a326caedf21705fb#diff-ec03fddaf55470d16bf56e91110b15fce131c580f35d1ae2cc1c0c97055225eb

**Comment by fstuerzl** [comment]
As requested by @tarasova-wmo, the path of the entry NOAAGML was changed from GAW Contributing networks to GAW Other elements: https://github.com/wmo-im/wmds/commit/2654e19638f9d0965f4b76a632f0083701f5dac8#diff-a066c50c20373fc15bcd759e58529c31867ae12caecaa7d36ad7627f5e689622
@tarasova-wmo, @john-mund could you please review the update?

**Comment by tarasova-wmo** [comment]
this is fine and according to the agreed with NOAA strategy. John Mund is an approver of NOAA GML affiliation
