### ISSUE TITLE
1-01-01 Inclusion of aerosol typing from remote sensing 

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#258]
**Branch**
https://github.com/wmo-im/wmds/blob/issue258/tables_en/1-01-01.csv

**Summary and Purpose**
Existing remote sensing projects currently provide indications of aerosol type based on retrieved parameters. This is done for both passive and active remote sensing projects, thus the aerosol types are provided for the entire column and vertically resolved. Typical aerosol "types" include marine, pollution, smoke, dust, etc. The aerosol types have increasingly been used for verification of aerosol transport within regional and global models, and for ground based validation of satellite retrievals. The existing entries in the observed variable - measured atmosphere code list do not contain aerosol types or any similar categorization that would capture this information. One problem is the lack of a common definition/method for categorizing observations as a given type. But the definitions could use ranges of observed variables to describe each type, based on what has been done in published studies.

**Stakeholder(s)**
WG ACV, proposal developed by @ejwelton

**Proposal**
Create aerosol type variables for the code list as follows:
Aerosol Type Marine
Aerosol Type Polluted Marine
Aerosol Type Continental
Aerosol Type Polluted Continental
Aerosol Type Pollution
Aerosol Type Smoke Fresh
Aerosol Type Smoke Aged
Aerosol Type Smoke Unknown
Aerosol Type Dust Mixture
Aerosol Type Dust
These types match the majority of aerosol typing done to date. Note, if the term "aerosol" is replaced with "particle phase", then these would be renamed to match. These new variables could be included under /Aerosol/Optical Properties as they are derived from optical properties in remote sensing, or a new subdomain could be created for aerosol type. NOTE: here, continental is typically used to refer to a rural, background aerosol type.

**Reason**
Creation of the new aerosol type variables would provide a means of documenting which GAW stations can provide estimates of aerosol type.

**Comment by ejwelton** [comment]
Further Justification:  Aerosol Type is in the current OSCAR requirements: 
https://www.wmo-sat.info/oscar/variables/view/aerosol_type

**Comment by joergklausen** [comment]
Add a variable "aerosol type" under Atmosphere/Particle Phase.
Add description.

**Comment by fstuerzl** [comment]
Variable added with description from OSCAR Requirements: https://github.com/wmo-im/wmds/commit/881fa7581087653804e1fc0ba2e7ad78ecf875d1#diff-160fbee712206a9a655a755c35b0b78b48ab1514bf8937984c6069c5fdf6ba6d

**Comment by ejwelton** [comment]
I concur with the addition of "aerosol type" to the /Atmosphere/Particle Phase

**Comment by gaochen-larc** [comment]
I also concur.  Thanks!

**Comment by amilan17** [comment]
ready for FT validation

**Comment by amilan17** [comment]
@joergklausen @fstuerzl @ejwelton 

The proposal differs from the branch. Was there a decision to only add 'Aerosol Type'? If so, can you please add the final decision to the original comment? If not, then the branch is not ready.

**Comment by joergklausen** [comment]
> 
> 
> Add a variable "aerosol type" under Atmosphere/Particle Phase.
> Add description.

The variable is indeed 'Aerosol type', examples given by @ejwelton refer to possible results for such observations.

**Comment by fstuerzl** [comment]
> Add a variable "aerosol type" under Atmosphere/Particle Phase.
> Add description.

Decision in WG ACV meeting (See [meeting notes](https://github.com/wmo-im/wmds/wiki/Meeting-notes) from 31 March 2021): Add only "Aerosol Type" as an observed variable.

**Comment by gaochen-larc** [comment]
> > Add a variable "aerosol type" under Atmosphere/Particle Phase.
> > Add description.
> 
> Decision in WG ACV meeting (See [meeting notes](https://github.com/wmo-im/wmds/wiki/Meeting-notes) from 31 March 2021): Add only "Aerosol Type" as an observed variable.

Agree
