### ISSUE TITLE
Variables in GAWSIS to follow GAW Implementation plan

### ISSUE THREAD

**Issue by tarasova-wmo** [wmo-im/wmds#262]
# **Branch**

https://github.com/wmo-im/wmds/blob/issue262/tables_en/1-01-01.csv

# **Summary and Purpose**

O2/N2 ratio is not lincluded in table 1-01-01 though it is included in the list of variables in the GAW Implementation plan https://library.wmo.int/doc_num.php?explnum_id=3395, p.49

# **Stakeholder(s)**

@tarasova-wmo

# **Proposal**

Add the following variable:

|notation|name|description|
|---|---|---|
|new id| O2/N2 ratio | Atmospheric O2/N2 ratio |

matrix: gas phase
tags: -

# **Reason**

---
Original comment:

I discovered that O2/N2 ratio is not listed as a variable in GAWSIS though it is included in the list of variables in the GAW Implementation plan https://library.wmo.int/doc_num.php?explnum_id=3395, p.49

**Comment by amilan17** [comment]
@joergklausen @fstuerzl -- this looks a simple fix that can be easy to implement in the next day or two....

**Comment by fstuerzl** [comment]
|notation|name|description|
|---|---|---|
|new id| O2/N2 ratio | Atmospheric O2/N2 ratio |

matrix: gas phase
tags: -
