### ISSUE TITLE
Discussion on domains, matrices and tags

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#273]
**Branch**
[add when created]

**Summary and Purpose**
Platform for discussions about the new approach to introduce a system of tags and matrices replacing the current path structure. 

**Stakeholder(s)**
WG ACV

**Proposal**
Draft in wiki page [Tags for observed variables](https://github.com/wmo-im/wmds/wiki/Tags-for-observed-variables)

**Comment by joergklausen** [comment]
@sebvi Corrected!. Sorry, I thought I had caught all of them ...

**Comment by fstuerzl** [comment]
Obsolete
