### ISSUE TITLE
1-01-03 table updates/corrections

### ISSUE THREAD

**Issue by champikagallage** [wmo-im/wmds#279]
**Branch**
https://github.com/wmo-im/wmds/blob/issue279/tables_en/1-01-03.csv
View differences: https://github.com/wmo-im/wmds/compare/issue279

**Summary and Purpose**
Updating ocean variables path and description to aline with  ECV/EOV information.

**Stakeholder(s)**
Ocean community @champikagallage

**Proposal**
Update the path, variable names and descriptions.

Necessary edits for names and descriptions of existing variables:
|notation|name (old)|description (old) | name (new)| description (new)
|---|---|---|---|---|
|65|Ocean surface currents (vector)|Water flow on ocean surface, typically in upper 30 m of the ocean.|Surface Currents|Ocean Vector motion measured at or near the surface (at stated depth)|
|71|Chlorophyll concentration|Indicator of living phytoplankton biomass, extracted from ocean colour observation. Uncertainty is expressed in mg/m3 for a given concentration of 1 mg/m3 .|-|Concentration of chlorophyll-a pigment in the surface water [µg l-1]. Indicator of living phytoplankton biomass, extracted from ocean colour observation. Uncertainty is expressed in mg/m3 for a given concentration of 1 mg/m3.|
|76|Ocean surface heat flux|Sea surface heat flux|-|The  exchange of heat, per unit area, crossing the surface between the ocean and the atmosphere.  It consists of the turbulent (latent and sensible) and the radiative (short wave and long wave) components.
|91|Ocean salinity|3D field of salinity of the ocean|Subsurface salinity|Salinity of seawater with depth|
|94|Ocean temperature|3D field of temperature of the ocean Requested in upper and deep ocean|Subsurface temperature|Seawater temperature measured with depth (degrees celsius/kelvin)|

The following variables, which are not defined, a description should be added:
|notation|name|description (new)|
|---|---|---|
|68|Dissolved organic carbon|Concentration of dissolved organic carbon|
|69|Dissolved organic nitrogen|Concentration of dissolved organic nitrogen|
|82|SiO3= (metasilicate)|Concentration of dissolved metasilicate|
|85|O2-Ar ratio|Ratio of O2/Ar concentrations|
|87|Oxygen, dissolved|Concentration of dissolved oxygen (O₂) in the water column|
|90|C2H6S (dimethylsulfide, DMS)|Concentration of DMS|
|400|Total organic phosphorus|Concentration of dissolved organic phosphorous|
|549|pO2|partial pressure of O2|

New variables:
|notation|name|description|
|---|---|---|
|_new id_|N2, Ar|Concentration of dissolved N2 and Ar|
|_new id_|Zooplankton biomass and diversity|Diversity: amount of species per unit sample, biomass: weight by volume (mg/l)

The entry N2, Ar is related to the existing entrie 84 (N2, Ar, O2), but it is no exact substitute. Variable 84 is no longer relevant and should be retired.

Changes in paths (tags):
_in progress_

**Reason**
To reflect the GCOS ECVs for the ocean domain and GOOS EOVs.

**Comment by joergklausen** [comment]
@champikagallage Can you be more specific in this proposal, please? What are the exact changes you propose?

**Comment by fstuerzl** [comment]
@joergklausen, I have helped @champikagallage to set up this issue, so that she can work on the branch. We will include a list of all changes in the proposal later.

**Comment by fstuerzl** [comment]
Changes in path structure and related tags:
|notation|path (old)|path (new)|tags|
|---|---|---|---|
|13|\Ocean\Topography\Bathymetry|\Ocean\Topography\Bathymetry|Topography|
|18|\Ocean\Basic Physical Properties\Pressure|\Ocean\Physical\Pressure|Physical|
|62|\Ocean\Currents\Ocean Current - Direction|\Ocean\Currents\Ocean Current - Direction|Currents|
|63|\Ocean\Currents\Ocean Current - Speed|\Ocean\Currents\Ocean Current - Speed|Currents|
|64|\Ocean\Topography\Ocean dynamic topography (ODT)|\Ocean\Physical\Sea Surface height\Ocean dynamic topography (ODT)|Physical, Sea Surface height|
|65|\Ocean\Currents\Ocean surface currents (vector)|\Ocean\Physical\Surface Currents|Physical|
|67|\Ocean\Miscellaneous\Carbon species\Dissolved inorganic carbon (DIC)|\Ocean\Biogeochemistry\Inorganic Carbon\Dissolved Inorganic Carbon (DIC)|Biogeochemistry, Inorganic Carbon|
|68|\Ocean\Miscellaneous\Carbon species\Dissolved organic carbon|\Ocean\Biogeochemistry\Dissolved Organic Carbon|Biogeochemistry, Dissolved Organic Carbon|
|69|\Ocean\Miscellaneous\Nitrogen species\Dissolved organic nitrogen|\Ocean\Biogeochemistry\Nitrogen species\Dissolved organic nitrogen|Biogeochemistry, Nitrogen species|
|70|\Ocean\Miscellaneous\Diffuse attenuation coefficient (DAC), turbidity|\Ocean\Physical\Diffuse attenuation coefficient (DAC), turbidity|Physical|
|71|\Ocean\Biology\Chlorophyll concentration|\Ocean\Biogeochemistry\Inorganic Carbon\Chlorophyll a concentration|Biogeochemistry, Inorganic Carbon|
|72|\Ocean\Miscellaneous\Ocean suspended sediments concentration|\Ocean\Biogeochemistry\Particulate Matter\Ocean suspended sediments concentration|Biogeochemistry, Particulate Matter|
|73|\Ocean\Miscellaneous\Oil spill cover|\Ocean\Biogeochemistry\Oil spill cover|Biogeochemistry|
|74|\Ocean\Biology\Primary production|\Ocean\Biology\Primary Production|Biology, Primary Production|
|75|\Ocean\Miscellaneous\Sea surface Mass Flux|\Ocean\Physical\Sea surface Mass Flux|Physical|
|76|\Ocean\Miscellaneous\Sea surface heat flux|\Ocean\Physical\Ocean Surface Heat Flux|Physical, Ocean Surface Heat Flux|
|77|\Ocean\Topography\Sea surface height anomaly (SSHA)|\Ocean\Physical\Sea Surface height|Physical, Sea Surface height|
|78|\Ocean\Miscellaneous\Total alkalinity (TA)|\Ocean\Biogeochemistry\Inorganic Carbon\Total alkalinity (TA)|Biogeochemistry, Inorganic Carbon|
|79|\Ocean\Miscellaneous\pH|\Ocean\Biogeochemistry\Inorganic Carbon\pH|Biogeochemistry, Inorganic Carbon|
|82|\Ocean\Biology\SiO3= (metasilicate)|\Ocean\Biogeochemistry\SiO3= (metasilicate)|Biogeochemistry|
|84|\Ocean\Other Gas\N2, Ar, O2 |||
|85|\Ocean\Other Gas\O2-Ar ratio|\Ocean\Biogeochemistry\O2-Ar ratio|Biogeochemistry|
|86|\Ocean\Other Gas\Ocean subsurface dissolved oxygen concentration|\Ocean\Biogeochemistry\Oxygen\Ocean subsurface dissolved oxygen concentration|Biogeochemistry, Oxygen|
|87|\Ocean\Other Gas\Oxygen, dissolved|\Ocean\Biogeochemistry\Oxygen\Disolved Oxygen|Biogeochemistry, Oxygen|
|89|\Ocean\Radiation\Water-leaving spectral radiance|\Ocean\Physical\Radiation\Water-leaving spectral radiance|Physical, Radiation|
|90|\Ocean\Reactive Gas\C2H6S (dimethylsulfide, DMS)|\Ocean\Biogeochemistry\Volatile liquid\C2H6S (dimethylsulfide, DMS)|Biogeochemistry, Volatile liquid|
|91|\Ocean\Basic Physical Properties\Ocean salinity|\Ocean\Physical\Subsurface Salinity|Physical|
|92|\Ocean\Basic Physical Properties\Sea surface salinity|\Ocean\Physical\Sea surface salinity|Physical|
|94|\Ocean\Basic Physical Properties\Ocean temperature|\Ocean\Physical\Subsurface Temperature|Physical, Subsurface Temperature|
|95|\Ocean\Basic Physical Properties\Sea surface temperature|\Ocean\Physical\Sea Surface Temperature|Physical|
|96|\Ocean\Topography\Coastal sea level (tide)|\Ocean\Physical\Sea Surface height\Coastal sea level (tide)|Physical, Sea Surface height|
|98|\Ocean\Waves\Dominant wave direction|\Ocean\Physical\Sea State\Dominant wave direction|Physical, Sea State|
|99|\Ocean\Waves\Dominant wave period|\Ocean\Physical\Sea State\Dominant wave period|Physical, Sea State|
|100|\Ocean\Waves\Significant wave height|\Ocean\Physical\Sea State\Significant wave height|Physical, Sea State|
|101|\Ocean\Waves\Wave 1D energy frequency spectrum|\Ocean\Physical\Sea State\Wave 1D energy frequency spectrum|Physical, Sea State|
|102|\Ocean\Waves\Wave directional energy frequency spectrum|\Ocean\Physical\Sea State\Wave directional energy frequency spectrum|Physical, Sea State|
|103|\Ocean\Wind\Wind stress|\Ocean\Physical\Ocean Surface Stress\Wind Stress|Physical, Ocean Surface Stress|
|311|\Ocean\Biology\Nitrogen species\NO2- (nitrite)|\Ocean\Biogeochemistry\Nutrients\NO2- (nitrite)|Biogeochemistry, Nutrients|
|312|\Ocean\Biology\Nitrogen species\NO3- (nitrate)|\Ocean\Biogeochemistry\Nutrients\NO3- (nitrate)|Biogeochemistry, Nutrients|
|399|\Ocean\Biology\Phosporus species\PO4= (phosphate)|\Ocean\Biogeochemistry\Nutrients\PO4= (phosphate)|Biogeochemistry, Nutrients|
|400|\Ocean\Biology\Phosporus species\Total organic phosphorus|\Ocean\Biogeochemistry\Phosporus species\Total organic phosphorus|Biogeochemistry, Phosporus species|
|401|\Ocean\Cryosphere\Sea ice\Sea-ice cover|\Ocean\Cryosphere\Sea ice\Sea-ice cover|Cryosphere, Sea ice|
|402|\Ocean\Cryosphere\Sea ice\Sea-ice elevation|\Ocean\Cryosphere\Sea ice\Sea-ice elevation|Cryosphere, Sea ice|
|403|\Ocean\Cryosphere\Sea ice\Sea-ice motion|\Ocean\Cryosphere\Sea ice\Sea-ice motion|Cryosphere, Sea ice|
|404|\Ocean\Cryosphere\Sea ice\Sea-ice surface characteristics|\Ocean\Cryosphere\Sea ice\Sea-ice surface characteristics|Cryosphere, Sea ice|
|405|\Ocean\Cryosphere\Sea ice\Sea-ice surface temperature|\Ocean\Cryosphere\Sea ice\Sea-ice surface temperature|Cryosphere, Sea ice|
|406|\Ocean\Cryosphere\Sea ice\Sea-ice thickness|\Ocean\Cryosphere\Sea ice\Sea-ice thickness|Cryosphere, Sea ice|
|407|\Ocean\Cryosphere\Sea ice\Sea-ice type|\Ocean\Cryosphere\Sea ice\Sea-ice type|Cryosphere, Sea ice|
|408|\Ocean\Transmissivity\CTD\Transmissivity|\Ocean\Physical\CTD\Transmissivity|Physical, CTD|
|549|\Ocean\Other Gas\CTD\pO2|\Ocean\Biogeochemistry\CTD\pO2|Biogeochemistry, CTD|
|731|\Ocean\Basic Physical Properties\Conductivity|\Ocean\Physical\Conductivity|Physical|
|732|\Ocean\Basic Physical Properties\Density|\Ocean\Physical\Density|Physical|
|733|\Ocean\Biology\Zooplankton (size and-or development stage)|\Ocean\Biology\Zooplankton (size and-or development stage)|Biology|
|735|\Ocean\Greenhouse Gas\pCO2|\Ocean\Biogeochemistry\Inorganic Carbon\pCO2|Biogeochemistry, Inorganic Carbon|
|736|\Ocean\Greenhouse Gas\pCO2 air-sea flux|\Ocean\Biogeochemistry\Inorganic Carbon\pCO2 air-sea flux|Biogeochemistry, Inorganic Carbon|
|739|\Ocean\Miscellaneous\Fluorescence (DOM)|\Ocean\Physical\Fluorescence (DOM)|Physical|
|740|\Ocean\Topography\Mean dynamic topography (MDT)|\Ocean\Physical\Sea Surface height\Mean dynamic topography (MDT)|Physical, Sea Surface height|
|741|\Ocean\Topography\Mean sea surface (MSS)|\Ocean\Physical\Sea Surface height\Mean sea surface (MSS)|Physical, Sea Surface height|
|742|\Ocean\Topography\Sea surface height (SSH, OST)|\Ocean\Physical\Sea Surface height\Sea surface height (SSH, OST)|Physical, Sea Surface height|
|743|\Ocean\Waves\Wave height|\Ocean\Physical\Sea State\Wave height|Physical, Sea State|
|744|\Ocean\Waves\Wave period|\Ocean\Physical\Sea State\Wave period|Physical, Sea State|
|745|\Ocean\Waves\Directional waves|\Ocean\Physical\Sea State\Directional waves|Physical, Sea State|
|10080|\Ocean\Tides|\Ocean\Physical\Sea Surface height\Tides|Physical, Sea Surface height|
|new id||\Ocean\Biogeochemistry\Other Gas\N2, Ar|Biogeochemistry, Other Gas|
|new id||\Ocean\Biology\Plankton\Zooplankton biomass and diversity|Biology, Plankton|

**Comment by champikagallage** [comment]
Please add another tag "Biogeochemistry" for 739 - Fluorescence (DOM)

**Comment by fstuerzl** [comment]
> Please add another tag "Biogeochemistry" for 739 - Fluorescence (DOM)

added in table above

**Comment by fstuerzl** [comment]
I suggest to also include the OSCAR/Requirements variable "Ocean subsurface tracers" defined as "Concentration of trace molecules such as tritium and CFCs"  in the list.

**Comment by champikagallage** [comment]
Please add following missing descriptions,

notation | name | description
74 | Primary   production | production of   organic matter by "phytoplankton," microscopic plant-like   photosynthetic organisms that live in the water
408 | Transmissivity | Measure   of the light that passes through the water in relation to the light incident
740 | Mean   dynamic topography (MDT) | Time-mean   (over a prescribed time period) of the sea surface height above the geoid
741 | Mean   sea surface (MSS) | Time-average   height (over a prescribed time period) of the ocean surface with respect to   the reference ellipsoid)
742 | Sea   surface height (SSH, OST) | Height   of the sea surface with respect to the reference ellipsoid
10080 | Tides | Periodic   change of sea height caused by the gravitational forces exerted by the Moon and the Sun on the Earth

**Comment by fstuerzl** [comment]
Branch updated: https://github.com/wmo-im/wmds/blob/issue279/tables_en/1-01-03.csv

**Comment by joergklausen** [comment]
I have endeavored to streamline this and make spelling consistent. Differences at https://github.com/wmo-im/wmds/commit/2bced96924890da63d0fa05d0d18fcef4591316f.

Several remaining issues: 
- Notation 407: Description
- Notation 741: Name

@champikagallage Please review and confirm.

**Comment by champikagallage** [comment]
Notation 407: Description; All Cryosphere variables will be reviewed by GCW experts at a future date including the description of 407. Therefore the description of 407 will be provided later.
Notation 741: Name; Sorry, I am not sure what is required here, I would like to have further clarification.

**Comment by joergklausen** [comment]
@champikagallage 
re 741: my bad, I think this was not relevant.
But you write "All Cryosphere variables will be reviewed by GCW experts at a future date ". Are you then suggesting this issue is not concluded for this FT-2021-2 and is moved to FT-2022-1?

**Comment by rodicanitu** [comment]
@joergklausen @champikagallage - Thanks; items 401 to 407 - agree with the new paths and tags, and concur with moving them to FT-2022-1, to allow for the completion of consultations on names &descriptions.

**Comment by champikagallage** [comment]
All items in 1-01-03 except 401-407 (Cryosphere variables) are validated by experts and ready to be included in the FT-2021-2.
