### ISSUE TITLE
Cookbook/Cheatsheet for GitHub

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#28]
The task team members need instructions on how they can use GitHub to maintain the code tables.
This issue is to amend and improve these instructions.

**Comment by HoratN** [comment]
Section '2.5 How to work on a branch' should be amended with the workflow for GitHub Desktop. 
I explained more or less how it works with SVN.

**Comment by efucile** [comment]
We don't want to have a document on gitHub workflow in the repository. The repository is only for the tables and the scripts working on the tables. Can You use the wiki for the workflow please? 
General information of this type has to go in the wiki. Can you check with @LuisaIckes as well?
We are going to discuss gitHub at the IPET-DD meeting the 19th February. Are you available to make a presentation?

**Comment by LuisaIckes** [comment]
I started with the Wiki and we will move everything there and remove this branch then.

**Comment by HoratN** [comment]
Branch deleted, since everything was moved to the Wiki.
