### ISSUE TITLE
1-01-01 Remove particle size range from variable name

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#280]
**Branch**
https://github.com/wmo-im/wmds/blob/issue280/tables_en/1-01-01.csv

**Summary and Purpose**
Many variables in the current "Aerosol" and "POP" path have attributes describing the particle size range such as e.g. "PM1", "coarse" etc. in their name. Informations related to the sampling procedure should not be stored in a variable name. With the addition of a new code table "ParticleSizeRange" (see issue #270) providing such attributes both in the variable name and in another element is redundant. 

**Stakeholder(s)**
WG ACV

**Proposal**
The code list should be cleaned up, by superseding all variables, which contain such attributes in the name, with  new variables. The names of the new variables should only contain the chemical species or quantities.

_list of all changes in progress_

**Reason**
This solution is a more systematic approach for describing observed variables, which avoids overcrowding the code list. If all attributes and combinations of attributes were put into the variable, the code list would ultimately become less manageable. Moreover the [WIGOS metadata standard](https://library.wmo.int/doc_num.php?explnum_id=10109) clearly defines an observed variable as the "variable intended to be measured, observed or derived, including the biogeophysical context", which does not include sampling information.

**Comment by fstuerzl** [comment]
Particle composition variables:

notation|name (new)|description (new)|supersedes
--|--|--|--
_new id_|Acidity-Alkalinity||579
_new id_|C2O4= (oxalate, ethanedioate)|"IUPAC: oxalate, PubChem CID: 71081, CAS Number: 338-70-5"|664, 665, 666
_new id_|Ca++ (Calcium)|"IUPAC: calcium(2+), PubChem CID: 271, CAS Number: 14127-61-8"|632, 633, 634
_new id_|Cl- (Chloride)|"IUPAC: chloride, PubChem CID: 312, CAS Number: 16887-00-6"|614, 615, 616, 617
_new id_|Elemental carbon||623, 624, 625
_new id_|F- (Fluoride)|"IUPAC: fluoride, PubChem CID: 28179, CAS Number: 16984-48-8"|618
_new id_|K+ (Potassium)|"IUPAC: potassium(1+), PubChem CID: 813, CAS Number: 24203-36-9"|638, 639, 640
_new id_|Major inorganic components||658, 659, 657
_new id_|Mg++ (Magnesium)|"IUPAC: magnesium(2+), PubChem CID: 888, CAS Number: 22537-22-0"|635, 636, 637
_new id_|Na+ (Sodium)|"IUPAC: sodium(1+), PubChem CID: 923, CAS Number: 17341-25-2"|641, 642, 643
_new id_|NH3 (Ammonia)|"IUPAC: 1,2-dichloro-1,1,2,2-tetrafluoroethane, PubChem CID: 6429, CAS Number: 76-14-2"|644
_new id_|NH4+ (Ammonium)|"IUPAC: azanium, PubChem CID: 223, CAS Number: 14798-03-9"|645, 646, 647
_new id_|NH4NO3 (Ammonium nitrate)|"IUPAC: ammonium nitrate, PubChem CID: 22985, CAS Number: 6484-52-2"|649, 648
_new id_|NO2- (Nitrite)|"IUPAC: nitrite, PubChem CID: 946, CAS Number: 14797-65-0"|653
_new id_|NO3- (Nitrate)|"IUPAC: nitrate, PubChem CID: 943, CAS Number: 14797-55-8"|650, 651, 652
_new id_|Other chemical components||660, 661
_new id_|Total carbon||626
_new id_|CH3O3S- (methanesulphonate)|"IUPAC: methanesulfonate, PubChem CID: 85257, CAS Number: 16053-58-0"|667, 668
_new id_|Carbonaceous-organic material||670, 671
_new id_|Al (Aluminium)||673, 674
_new id_|Sb (Antimony)||675, 676
_new id_|As (Arsenic)||677, 678
_new id_|Ba (Barium)||679, 680
_new id_|Bi (Bismuth)||681, 682
_new id_|Cd (Cadmium)||683, 684, 685, 686, 687
_new id_|Ce (Cerium)||688, 689
_new id_|Cr (Chromium)||690
_new id_|Co (Cobalt)||691
_new id_|Cu (Copper)||692, 693
_new id_|Fe (Iron)||694
_new id_|La (Lanthanum)||695, 696
_new id_|Pb (Lead)||697, 698
_new id_|Li (Lithium)||699, 700
_new id_|Mn (Manganese)||701, 702
_new id_|Hg (Mercury)||703
_new id_|Ni (Nickel)||704, 705
_new id_|P (Phosphorous)||706, 707
_new id_|Rb (Rubidium)||708, 709
_new id_|Se (Selenium)||710
_new id_|Sr (Strontium)||711, 712
_new id_|Tl (Thallium)||713, 714
_new id_|Th (Thorium)||715, 716
_new id_|Sn (Tin)||717, 718
_new id_|Ti (Titanium)||672
_new id_|U (Uranium)||719, 720
_new id_|V (Vanadium)||721, 722
_new id_|Zn (Zinc)||723, 724

Aerosol/Particle phase, optical and physical properties:

notation|name (new)|description (new)|supersedes
--|--|--|--
_new id_|Light absorption coefficient||316, 317, 318
_new id_|Light backscattering coefficient||319, 320, 321
_new id_|Light scattering coefficient||322, 323, 324
_new id_|Multiwavelength optical depth||325
_new id_|Mass concentration||364, 365, 366
_new id_|Number size distribution||370, 371
_new id_|Hygroscopic growth factor||413, 414, 415, 416, 417, 418

-> The variable "Hygroscopic growth factor" can only replace the existing variables, if the attributes "110 μm equivalent", "165 μm equivalent", "35 μm equivalent", "50 μm equivalent", "75 μm equivalent" can be specified. This is not yet included in the proposal for a code table for the particle size range #270.

**Comment by joergklausen** [comment]
How useful is an observed variable "Other chemical components"? I would suggest to drop this.

**Comment by gaochen-larc** [comment]
Should add "Light extinction coefficient"  Also, should consider add "Single scattering albedo", "Angstrom exponent for light scattering", and "Angstrom exponent for light extinction".

**Comment by gaochen-larc** [comment]
> How useful is an observed variable "Other chemical components"? I would suggest to drop this.

I agree to drop "Other chemical components"

**Comment by joergklausen** [comment]
> Should add "Light extinction coefficient" Also, should consider add "Single scattering albedo", "Angstrom exponent for light scattering", and "Angstrom exponent for light extinction".

@markusfiebig @charlesabrock Please comment.

**Comment by gaochen-larc** [comment]
@markusfiebig I like the terms you proposed better.  Thanks!

**Comment by fstuerzl** [comment]
Proposals by @ejwelton in #263:

> 3. Variable: Light backscattering coefficient, total aerosol. This variable needs to be split into two separate variables to account for backscatter measurements at both 180 degrees and over the backwards hemisphere. These are fundamentally different variables and cannot share one name.
> 3a. Rename current variable to the following: Hemispheric Backscatter Coefficient, total aerosol. Definition: The fraction of incident radiative flux scattered into all backward angles, ie scattering_angle exceeding pi/2 radians, by total aerosol particles.
> 3b. Create new variable: Backscatter Coefficient, total aerosol. Definition: The fraction of incident radiative flux scattered backward at 180 degrees by total aerosol particles.

> 4. Variable: Multi-wavelength optical depth, total aerosol. This does not match the OSCAR requirements, which do not demand multi-wavelength observations. In addition, optical depth measurements are made for individual wavelengths (with defined bandpass), and the current name is illogical as no optical depth value is "multi-wavelength". Suggest renaming this variable to "aerosol optical depth" to match the requirements table. Also suggest new definition to avoid specifying column observations (instead use the observedLayer code list). New Definition: The AOD is the effective depth of the aerosol over a specified distance, from the viewpoint of radiation propagation: Vertical integral of spectral aerosol extinction coefficient AOD = exp(-K. Δz) where K is the extinction coefficient [km-1 ] and Δz the vertical path [km].

To summarise the discussion above:

New variables, which supersedes existing variables with size range in the variable name:
notation|name (new)|description (new)|supersedes
--|--|--|--
_new id_|Particle light absorption coefficient||316, 317, 318
_new id_|Light backscattering coefficient||319, 320, 321
_new id_|Particle light scattering coefficient||322, 323, 324
_new id_|Aerosol optical depth|The AOD is the effective depth of the aerosol over a specified distance, from the viewpoint of radiation propagation: Vertical integral of spectral aerosol extinction coefficient AOD = exp(-K. Δz) where K is the extinction coefficient [km-1 ] and Δz the vertical path [km]|325
_new id_|Mass concentration||364, 365, 366
_new id_|Number size distribution||370, 371
_new id_|Hygroscopic growth factor||413, 414, 415, 416, 417, 418

Set status of variables 319, 320, 321 (Light backscattering coefficient) to "retired" and add two new variables instead:
notation|name|description
--|--|--
_new id_|Hemispheric Backscatter Coefficient|The fraction of incident radiative flux scattered into all backward angles, ie scattering_angle exceeding pi/2 radians, by total aerosol particles.
_new id_|Backscatter Coefficient|The fraction of incident radiative flux scattered backward at 180 degrees by total aerosol particles.

New additions:
notation|name|description
--|--|--
_new id_|Particle light extinction coefficient|
_new id_|Particle single scattering albedo|
_new id_|Ångström exponent for particle light extinction|
_new id_|Ångström exponent for particle light scattering|
_new id_|Ångström exponent for particle light absorption|

To do:
- Add definitions if necessary
- Review branch

**Comment by gaochen-larc** [comment]
Are we going to combine "Hygroscopic size growth factor", "Hygroscopic scattering growth factor", and "Hygroscopic extinction growth factor" to just one "Hygroscopic growth factor"?

Also, I would like to suggest to add "Surface Area Size Distribution", "Volume Density Size Distribution", "Mass Size Distribution".  Comments?  @markusfiebig and @chuck

**Comment by charlesabrock** [comment]
Add new row to backscatter table: "Hemispheric forward scattering coefficient", defined as "Incident radiative flux scattered into all forward angles, ie scattering_angle from zero to pi/2 radians, by total aerosol particles."

Change backscattering entries from "The fraction of incident radiative flux. . ." to "Incident radiative flux. . . ."

**Comment by joergklausen** [comment]
@markusfiebig Please description for
- Hygroscopic particle size growth factor
- Hygroscopic particle light scattering growth factor
- Hygroscopic particle light extinction growth factor

**Comment by fstuerzl** [comment]
Since the specification of a particle size range is not yet included in the WMDR model, the removal of all references to particle sizes from the variable names is postponed. 
For the transition phase (until the model was changed and the changes were implemented in OSCAR/Surface) @joergklausen and I concluded that the size range needs to remain.

**Comment by markusfiebig** [comment]
For being consistent, be should re-phrase the terms to:
-Particle mass concentration
-Particle number size distribution
-Particle surface area size distribution
-Particle volume density size distribution
-Particle mass size distribution

**Comment by gaochen-larc** [comment]
> For being consistent, be should re-phrase the terms to:
> -Particle mass concentration
> -Particle number size distribution
> -Particle surface area size distribution
> -Particle volume density size distribution
> -Particle mass size distribution

like it!  Should we remove "density" from "Particle volume density size distribution" to be consistent with the others?

**Comment by fstuerzl** [comment]
> Since the specification of a particle size range is not yet included in the WMDR model, the removal of all references to particle sizes from the variable names is postponed.
> For the transition phase (until the model was changed and the changes were implemented in OSCAR/Surface) @joergklausen and I concluded that the size range needs to remain.
> 
> All proposed changes in this issue, which go beyond the removal of the size range, will be treated in another issue for FT-2021-2.

This issue should only be used for discussion on the removal of particle size attributes. All proposals for new variables or other amendments of names and definitions, that shoud go through FT-2021-2 are included here: https://github.com/wmo-im/wmds/issues/289

**Comment by joergklausen** [comment]
Further discussion depends on the evolution of the WMDR UML model, which is currently in progress.
