### ISSUE TITLE
Nilreason

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#29]
The used nilreasons need to be standardized. Only unknown and inapplicable should be used in future.
The taskteam and the oscar-team needs to think about in which tables both values can be inserted and for which tables this could cause problems in the application.

**Comment by HoratN** [comment]
Discussion 11.2.2019: All tables which are owned by the team should contain both 'unknown' and 'inapplicable'.

**Comment by LuisaIckes** [comment]
'notApplicable' instead of inapplicable.
For tables which are external/not owned by us: suggest changes to external team to include this two fields.

**Comment by joergklausen** [comment]
The correct terms to use are 'inapplicable' and 'unknown', both from http://www.datypic.com/sc/niem21/t-gml32_NilReasonType.html

**Comment by HoratN** [comment]
I propose to use **unknown** and **inapplicable** since this is the wording which is used in the common code table on nilreasons: https://codes.wmo.int/common/nil.

**Comment by LuisaIckes** [comment]
Good, I was just copying it from the table we discussed during the Telecon 4-03-03, there it said notApplicable so should probably be adjusted then.

**Comment by efucile** [comment]
I don't think that we discussed the use of nilReason. I think that we discussed the introduction of unknown and "not applicable" in the table. 
I absolutely agree on the use of nilReason from here https://codes.wmo.int/common/nil in a similar way as discussed here https://github.com/wmo-im/iwxxm/issues/19
I suggest that we keep this open and resolve at a later time.

**Comment by joergklausen** [comment]
Following tables have not been developed by TT-WMD, but adding nilReasons makes sense:
1-02 Units (COMMON CODE TABLE C–6: amendments to be submitted to IPET-CM)
2-01 Application Area
3-01
3-02
4-07
9-02
11-01, 11-02

Following tables are not owned by TT-WMD, and adding nilReason doesn't make sense:
4-01 (nilReasons can be added to 4-02)
8-03 (nilReason can be added to 8-04)

I recommend we add nilReasons only to the tables used in mandatory elements for now, and resolve this later.

**Comment by HoratN** [comment]
In the minutes of the discussion of 11 February 2019, the following was recorded:
- The inclusion of the entries “Unknown” and “Inapplicable” across all code tables, for harmonization, was again discussed and the conclusion was that the decision from TT-WMD-7 should be implemented, except for the code tables not owned by TT-WMD, e.g. the units table.

Thus I will create new entries in the tables listed below:
- 1-01 variables:
new: 100001,,,(unknown), The variable is unknown.
new: 100002,,,(inapplicable), None of the codes in the table are applicable in the context of this particular observation.
-1-05 Representativeness:
new: unknown,,,(unknown),The representativeness is unknown in the context of the observed quantity.
existing: rename unspecified into inapplicable
- 2-02 Programme/network affiliation
existing: nonAffiliated,,>Non-affiliated,Non-affiliated,Observing elements that are not affiliated with WIGOS or any of the co-sponsored programmes
new: unknown,,,(unknown),The affiliation/programme is unknown.
new: inapplicable,,,(inapplicable), None of the codes in the table are applicable.
- 3-04 Station/platform type
new: unknown,,,(unknown), The station/platform type is unknown.
new: inapplicable,,,(inapplicable),None of the codes in the table are applicable in the context of this particular station/platform.
- 3-08 Data communication method
new: unknown,,,(unknown),The data communication method is unknown for this particular observation.
new: inapplicable,,,(inapplicable), None of the codes in the table are applicable in the context of this particular observation.
- 3-09 Station/platform operating status
new: unknown,,,(unknown),The operating status of this particular station/platform type is unknown.
new: inapplicable,,,(inapplicable), None of the codes in the table are applicable in the context of this particular station/platform.
- ...(will follow soon)

**Comment by toakley76** [comment]
This latest suggestion is my preference. Add 'nil-reason' to all tables owned by WMD. The use of inapplicable is also OK for me.

**Comment by LuisaIckes** [comment]
If I understood Luis right here [issue71](https://github.com/wmo-im/wmds/issues/71) we have to check if some tables have the entry "not available" and remove this when having "unknown" and "inapplicable".

**Comment by HoratN** [comment]
I suggest that I merge the branch 'issue29' to the development branch. And then we can overwrite this branch 'issue29' with the development branch and add the missing nilreasons in the tables which aren't present in this branch so far.

**Comment by LuisaIckes** [comment]
Added issue 29 to the development branch, second round of changes for the new tables (Table 1-04, 2-01, 3-01, 3-02, 4-07, 5-02-01, 5-02-05, 9-02, 10-01) in branch [issue29b](https://github.com/wmo-im/wmds/tree/issue29b/), commit 04a1ba6 and 3bd41cd.
