### ISSUE TITLE
new table 4-01-08

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#33]
See commit 38b181640d9de13b3222f766db20f6ea5dda0c31.
The encoding issue in line 17 is fixed (commit 0c2fbb327678f23630fe7bf94b9c4cc935c8d8e1).

Can we publish this table as it is now?
@efucile Can we publish a new table via fast-track?

**Comment by joergklausen** [comment]
@efucile: I would say that TT-WMD can push an additional entry to 4-02 with the associated code table 4-01-x via fast-track.

However, in 4-02, there are only 6 entries at present, so there can only be 6 tables 4-01-x. How do I know which of the 4-01-x tables corresponds to a specific entry in the 4-02 table? I don't see the link between these tables anymore, which is a serious problem.

**Comment by joergklausen** [comment]
Correction: I could see 7 entries in 4-02, and 4-01-07 doesn't seem to exist ... so there are 7 tables 4-01-x, corresponding to 7 entries in 4-02 ... but which one belongs to which? That question remains.

**Comment by HoratN** [comment]
Could we rename 4-01-x into 4-01-\<short name of surface cover scheme\>?

i.e.
- 4-01-01: 4-01-IGBP
- 4-01-02: 4-01-UMD
- 4-01-03: 4-01-LAIFPAR
- 4-01-04: 4-01-NPP
- 4-01-05: 4-01-PFT
- 4-01-06: 4-01-LCCS
- 4-01-08: 4-01-GlobCover2019

The tables can found here (for example):
https://github.com/wmo-im/wmds/compare/tables-from-OSCAR

**Comment by HoratN** [comment]
Table 4-02 names: stick to WMDS version

**Comment by HoratN** [comment]
new table should be 4-01-07 and not 4-01-08.

**Comment by HoratN** [comment]
changed name of table 4-01-08 into 4-01-07 as discussed in commit
6a66d88 
on the branch https://github.com/wmo-im/wmds/tree/review_TT-WMD-7
