### ISSUE TITLE
Table 5-02-01: new methods of observation (for atmospheric variables)

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#336]
## Initial request

I think root items of the “add measurement program" tree and “methods” tree should be exactly the same. Because it is mandatory to defines the method of observation for any measurement program. My suggestion for the mentioned variables is as follows: 

\- Sunshine duration

*   Campbell-Stokes sunshine recorder (burn method)
*   Pyrheliometric method
*   Pyranometric method
*   Contrast-evaluating and scanning devices 

\- Visibility

*   Human observation
*   Scatterometer
*   Transmissometer

\- Present weather

*   Human observation
*   Automated observation

\- Past weather

*   Human observation
*   Automated observation

## Requestor(s)

NFP-OSCAR/Surface from Iran  (hesam.sajdeh@gmail.com)
and Alexander Scheid (AScheid@wmo.int)

## Amendment details
_updated 30 June 2023_

Add:

| notation | path | name | description |
| --- | --- | --- | --- |
| tbd | /Atmosphere/Radiation/In-Situ/ | Campbell-Stokes burn method | Sunshine duration is determined by evaluating the burnt areas imprinted by the sun in a strip of carton or aluminum foil placed behind a glass sphere. |
| tbd | /Atmosphere/Radiation/In-Situ/ | Contrast-evaluating and scanning devices | Sunshine duration is determined by combining multi-sensor detectors with electronic discriminator.  |

Deprecate:

| notation | path | name | description | reason |
| --- | --- | --- | --- | --- |
| 198 | /Atmosphere/Radiation/in-situ/ | sunshine duration | **missing** | _term refers to an observed quantity/variable, not a method, and is therefore useless_ |

### Expected impact of change
MEDIUM-HIGH

## Branch
[https://github.com/wmo-im/wmds/tree/issue336](https://github.com/wmo-im/wmds/tree/issue336)

**Comment by amilan17** [comment]
@anthoninlize @MKrieger29 -- have you had a chance to work on this issue? If we want this to be submitted in FT22-2, then the proposal should be ready before the end of the month.

**Comment by joergklausen** [comment]
The original proposal cannot be supported as is. It listed observed variables or groupings of observed variables, and then mostly instruments:

> *   Visibility
>     *   Human observation
>     *   Scatterometer
>     *   Transmissometer
> *   Present weather
>     *   Human observation
>     *   Automated observation\*
> *   Past weather
>     *   Human observation
>     *   Automated observation\*
> 
> \* Recognizable phenomena should be specified

I had commented previously that several of the proposed elements already exist, albeit under specific paths. In terms of the WIGOS code registry, these paths do not even exist, so they are not relevant for the specification of a method. In future, also this code table needs to be re-worked, making use of tags instead of paths.

I have updated the proposal, indicating in bold what I see is still missing. @anthoninlize @MKrieger29 Please review and reach out to stakeholders outside WMO/OceanOPS. Such stakeholders must also be listed explicitly, so that we can contact and refer to them.

**Comment by amilan17** [comment]
moving target milestone to FT2023-1

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2022.10.20-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2022.10.20-TT-WIGOSMD) notes: 

@RMaerz will reach out to colleagues and update the issue summary before next meeting

@amilan17 update issue summary to match new style

**Comment by amilan17** [comment]
*   Campbell-Stokes sunshine recorder (burn method)
*   Pyrheliometric method
*   Pyranometric method
*   Contrast-evaluating and scanning devices
*   [Human observation](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_24) (already exists)
*   [Scatterometer](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_190) (already exists)
*   [Transmissometer](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_207) (already exists)
*   Automated observation

**Comment by RMaerz** [comment]
I mostly agree but 'human observation' does not exist for visual range , only for clouds as far as I found. So it needs to be added like
[ tbd , 'Atmosphere/Visual Range/human observation' , determining visibility with help of objects in known distance from observing site ]

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.03-TT-WISOSMD notes:
* @RMaerz: don't add "contrast-evaluating and scanning devices" till we have more information. 'human observation' is currently limited by the path
* @meulenvd: recommends looking at WMO-No. 8 for sunshine variables
* * @amilan17: email requestor and cc' @RMaerz

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD) notes: 

(@RMaerz) reviewed CIMO guide and updated Amendment Details and will add reference to the guide and new definitions.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.12.08-TT-WIGOSMD notes: 
@RMaerz updated issue summary, will add reference to WMO-No. 8 when used, but not sure how to add definition for human observations for clouds. @gaochen-larc suggests finding a definition for how it used to be done from the Itl' Cloud Atlas.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.03.16-TT-WIGOSMD notes: 
Rainer will be ready to talk about at the next meeting

**Comment by joergklausen** [comment]
@RMaerz Please provide a description of 'human observation' (of clouds) in the description before the meeting on 2023-03-17.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023-03-17-TT-WIGOSMD notes: 
Joerg will work on this issue.

**Comment by joergklausen** [comment]
notation 24: human observation = "Determination of type and quantity of clouds by a trained human observer"

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.06-TT-WIGOSMD notes: 
(Jitze) usually don't talk about quantity of clouds (Joerg) changed to coverage; (Gao) double check with cloud atlas?
https://cloudatlas.wmo.int/en/observation-of-clouds-from-the-earths-surface.html (Anna) there is already a generic definition: http://codes.wmo.int/wmdr/SourceOfObservation/humanObservation;

**Comment by joergklausen** [comment]
24 | Human observation | *Observation of clouds from the Earth's surface by a human observer (ref: https://cloudatlas.wmo.int/en/observation-of-clouds-from-the-earths-surface.html)*

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.21-TT-WIGOSMD notes: 
team agrees to updated description.

**Comment by joergklausen** [comment]
Branch updated, ready for validation.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.01-TT-WIGOSMD notes: 
Anna create PR and validate

**Comment by joergklausen** [comment]
I believe @meulenvd may have mixed up the notations: 190 (instead of 170), 207 (instead of 209). 
More importantly, "by aerosols and other particles" is not an ideal wording. "Aerosol" is a combination of gas and particles, so 'other particles' is not necessary. Moreover, I am not convinced the adding more words here has provided more clarity, because scattering and extintion and absorption are now all convoluted. I am not very familiar with this kind of instruments, but a measurement of the scattering is different than a measurement of the extinction.

**Comment by amilan17** [comment]
I recommend setting status of  "sunshine duration" to Retired.

**Comment by amilan17** [comment]
created new issue #499

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD) notes:

valid, small update to text of "contrasting-evaluating and scanning..."
