### ISSUE TITLE
add notations for new values added during FT21-2 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#342]
Branch: https://github.com/wmo-im/wmds/tree/addNotations

* https://github.com/wmo-im/wmds/blob/master/tables_en/1-01-01.csv
* https://github.com/wmo-im/wmds/blob/master/tables_en/1-01-03.csv
* https://github.com/wmo-im/wmds/blob/master/tables_en/5-02-05.csv
* https://github.com/wmo-im/wmds/blob/master/tables_en/superseded.txt

**Comment by fstuerzl** [comment]
Notations are updated in this branch: https://github.com/wmo-im/wmds/tree/addNotations

**Comment by amilan17** [comment]
@fstuerzl please add notations to the superseded.txt file too. 

https://github.com/wmo-im/wmds/tree/addNotations2
