### ISSUE TITLE
Table 1-02: Add missing unit to supersede mg_m-3_25C

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#355]
# **Branch**

https://github.com/wmo-im/wmds/blob/issue355/tables_en/1-02.csv
https://github.com/wmo-im/wmds/blob/issue355/tables_en/superseded.csv

# **Summary and Purpose**

mg.m-3 is missing from the Units table in GitHub. Therefore, mg_m-3_25C could not be superseded on the registry as it was intended in FT 2021-2. 

# **Stakeholder(s)**

@gaochen-larc, @joergklausen 

# **Proposal**

Add unit:

|notation|name|description|
|--|--|--|
|mg.m-3| milligrams per cubic metre|SI derived unit of mass concentration, equal to 1E-6 kg/m3|

Supersede unit mg_m-3_25C by new unit mg.m-3.

# **Reason**

Improve consistency of reorganized Unit Table after FT 2021-2, the unit at hand mixes a physical quantity and a unit which is incompatible with SI principles.

# Expected Impact of Change

**HIGH**

The implementation of the revised unit table in OSCAR/Surface can be done with little effort, but since the notations (wmo306 code) of the units has changed, users of the XML upload need to be informed in advance, so that they can adapt their systems.

**Comment by joergklausen** [comment]
@amilan17 Please create branch. This was an oversight during the finalization of FT-2021-2 and is only a technicality. It does not require further consultation.

**Comment by gaochen-larc** [comment]
I confirm that this branch is correct.

**Comment by joergklausen** [comment]
I confirm that this branch is correct.
