### ISSUE TITLE
1-02: Align plurality of units with SI conventions

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#361]
# Summary and Purpose

# Branch
https://github.com/wmo-im/wmds/blob/issue361/tables_en/1-02.csv

# Stakeholders

@meulenvd 

# Proposal

Remove the "s" from unit name.  

<table><tbody><tr><td>degC</td><td>degree Celsius (°C)</td><td>SI derived unit of temperature, SI base unit equivalent: K</td></tr></tbody></table>

# Reason

The basic reference for the naming convention associated to SI is the SI brochure, authorized by the int. sci. associations (currently, version 9), to be found on the official BIPM website for SI, https://www.bipm.org/en/publications/si-brochure. In this document it is clearly stated that: "one must **neither use the plural** nor mix unit symbols and unit names within one expression" (par 5.2). For the Celsius temperature (the thermodynamic temperature is also called kelvin temperature) the unit is defined as follows (par. 2.3.1 and table 4): "The unit of Celsius temperature is the **degree** Celsius, symbol °C, which is by definition equal in magnitude to the unit kelvin. A difference or interval of temperature may be expressed in kelvin or in degrees Celsius"  
So the unit is **not degrees Celsius, but degree Celsius** (not plural). But when you express values then the word degree _as such_ has to be expressed with an 's', so 20 degree**s** Celsius. If, like with the kelvin temperatuur, you refer to the defined unit you will express values as 20 kelvin (not plural, and with lower case). Degree Celsius / degrees celsius is still a kind of a black sheep within the SI units vocabulary, largely because the (derived) Celsius temperature is still more popular than the (basic) thermodynamic temperature (with base unit K).

_Originally posted by @meulenvd in https://github.com/wmo-im/wmds/issues/337#issuecomment-973090103_

# Expected Impact of Change

**LOW**

**Comment by amilan17** [comment]
Other units to consider

<table><tbody><tr><td><a href="http://codes.wmo.int/wmdr/unit/_degC.hm-1">degrees Celsius per 100 metres</a></td><td>degC.hm-1</td><td>Unit of spatial gradient of temperature per 100 metres</td></tr><tr><td><a href="http://codes.wmo.int/wmdr/unit/_degC.m-1">degrees Celsius per metre</a></td><td>degC.m-1</td><td>Unit of spatial gradient of temperature per metre</td></tr></tbody></table>

**Comment by gaochen-larc** [comment]
There are many cases that the plural was used.   We need to go through the entire list systematically.  Also, We will need to make changes  or replace the names with plural from the original unit code list.  Should we proceed? @amilan17 @joergklausen

**Comment by joergklausen** [comment]
For reference and history: WMDR initially used the table https://codes.wmo.int/common/_unit as a baseline. You will see there are already a number of plurals in that list. We didn't pay much attention to that aspect at the time. My suggestion to evolve that list and refer to it or the purpose of WMD was not taken up. So, we now have our own code list on units ... with the liberty to at least align it better to SI conventions.

@gaochen-larc Please proceed and remove all plural forms, also all references to SI where those are not appropriate. 

@meulenvd (former WMO/CIMO) and @semmerson (US/NIST) Please help us and confirm the branch once ready.

**Comment by amilan17** [comment]
@gaochen-larc @joergklausen @fstuerzl is this ready for FT? 

[https://github.com/wmo-im/wmds/compare/issue361](https://github.com/wmo-im/wmds/compare/issue361)

**Comment by joergklausen** [comment]
Line 69: space missing
Line 157: for consistency, 1E-3 should be 0.001
Except for these non-material changes I spotted, this is ready for FT.

**Comment by fstuerzl** [comment]
> Line 69: space missing Line 157: for consistency, 1E-3 should be 0.001 Except for these non-material changes I spotted, this is ready for FT.

Branch is updated: https://github.com/wmo-im/wmds/commit/8e463e9bd2d8547cfae7920e6044fba8f0335b58

**Comment by gaochen-larc** [comment]
One last question, should we use "a" for year or "yr" for year?   I vaguely recall someone raised this issue before.  Other than this, it is ready for FT.

**Comment by amilan17** [comment]
> One last question, should we use "a" for year or "yr" for year? I vaguely recall someone raised this issue before. Other than this, it is ready for FT.

This question is unrelated to the plurality in definitions.

**Comment by amilan17** [comment]
@joergklausen @gaochen-larc Is this ready for FT? 

Please review tables\_en/1-02.csv in the diff (https://github.com/wmo-im/wmds/pull/378/files) of the PR.

**Comment by joergklausen** [comment]
I think it is. Can @meulenvd also go through this one last time?

**Comment by amilan17** [comment]
We need to review the feedback recieved from Charles Fierz and determine fix for FT22-1 or defer to FT22-2.

**Comment by amilan17** [comment]
[ttWMD-202202\_FT2022-1-vI.3-CF-am.pdf](https://wmoomm-my.sharepoint.com/:b:/g/personal/amilan_wmo_int/ER8P5-r7__xEl4tkYO05jA8Bh5skpekQKpwzxIoEei4K9A?e=znOJyL)

**Comment by joergklausen** [comment]
@amilan17 Please see my e-mail to you from 15 March (RE: Amendment proposals for WIGOS Metadata Codes (respond by 4-March-2022)). Attached to it, I had sent my comments and corrections. I don't find those in any way reflected in the pdf you have linked above. Is this an oversight or a conscious decision?

**Comment by fierz** [comment]
@amilan17 @gaochen-larc @joergklausen 
Thanks to all of you for considering and going through my comments.

- I fully support the use of derived SI unit and dropping '_prefixed_'
- Fully agree SI does not recommend numerical values. My comment on, for example week, was on the way large numbers are written, that is _604 800_ and not _604800_. This is a SI recommendation but would require quite a few changes in the table that are not worth going through.
- Regarding _kilocalory per square centimetre_, I could not find it in either [https://codes.wmo.int/common/_unit](https://codes.wmo.int/common/_unit) or [https://codes.wmo.int/wmdr/unit](https://codes.wmo.int/wmdr/unit). I think it was proposed by Dr Bianchi last year, thus there would be no need to deprecate it.
