### ISSUE TITLE
1-01-01 addition of greenhouse gas variables from WDCGG

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#368]
# Proposal Summary
## **Branch**

https://github.com/wmo-im/wmds/blob/issue368/tables_en/1-01-01.csv

## **Summary and Purpose**

New variables for greenhouse gases have been added to WDCGG recently and have no corresponding entry in the code list. Therefore they should be added.

## **Proposal**

|name|description|tags|
|--|--|--|
|C2H2Cl2F2 (1,2-dichloro-1,1-difluoroethane, HCFC-132b)|IUPAC: 1,2-dichloro-1,1-difluoroethane, PubChem CID: 15442, CAS Number: 1649-08-7, in gas phase| greenhouse gas, HCFC|
|C2H2ClF3 (2-chloro-1,1,1-trifluoroethane, HCFC-133a)|IUPAC: 2-chloro-1,1,1-trifluoroethane, PubChem CID: 6408, CAS Number: 75-88-7, in gas phase| greenhouse gas, HCFC|
|C3H2F6 (1,1,1,3,3,3-hexafluoropropane, HFC-236fa)|IUPAC: 1,1,1,3,3,3-hexafluoropropane, PubChem CID: 12722, CAS Number: 690-39-1, in gas phase| greenhouse gas, HFC|

## **Reason**

Addition of missing variables.

## **Stakeholder(s)**

World Data Center for Greenhouse Gases (WDCGG)
https://gaw.kishou.go.jp/

## Consultations

Alex Vermeulen, chair SAG GG, @atverm

## Context

- https://pubchem.ncbi.nlm.nih.gov/compound/15442
- https://pubchem.ncbi.nlm.nih.gov/compound/6408
- https://pubchem.ncbi.nlm.nih.gov/compound/12722

## Expected Impact of Change

**LOW**
Addition of new variables in OSCAR is uncomplicated in this case.

**Comment by joergklausen** [comment]
@atverm Dear Alex, do you see any concerns from the point of view of SAG GG and/or ICOS?

**Comment by atverm** [comment]
No concerns, looks fine to me

**Comment by amilan17** [comment]
@fstuerzl Can you please spell out WDCGG?

**Comment by fstuerzl** [comment]
> @fstuerzl Can you please spell out WDCGG?

@amilan17, sure, sorry, I didn't think of it. It's the World Data Center for Greenhouse Gases.
