### ISSUE TITLE
2-02 Programme/network affiliation: Supersede CLIMAT(x) by RBON

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#382]
# Proposal Summary

## **Summary and Purpose**

Remove CLIMAT programmes from code table https://codes.wmo.int/wmdr/ProgramAffiliation. Their parent programme "RBCN" is already superseded by "RBON" (see metadata for https://codes.wmo.int/wmdr/ProgramAffiliation/_RBCN), so I suggest to also supersede CLIMAT(C), CLIMAT(CT) and CLIMAT(T) by RBON.  
This follows up on issue [#215](https://github.com/wmo-im/wmds/issues/215) from FT-2021-1, in which RBCN and RBSN were superseded by RBON. In this issue the "leaves" below RBCN were not changed - probably by mistake. The "leaves" under RBSN, such as e.g. RBSN(p) https://codes.wmo.int/wmdr/ProgramAffiliation/_RBSNp were also superseded by RBON.

This inconsistency should be corrected in the next FT.

## **Proposal**

Supersede CLIMAT(C), CLIMAT(CT) and CLIMAT(T) by RBON.

~9 June 2022

| **Notation** | **Name** | **Description** | **Supersede by** |
| --- | --- | --- | --- |
| ~CLIMATc~ | ~CLIMAT(C)~ | ~Station for which monthly climatological means of surface elements are transmitted~ | [RBON](http://codes.wmo.int/wmdr/ProgramAffiliation/RBON) |
| ~CLIMATct~ | ~CLIMAT(CT)~ | ~Station for which monthly climatological means of both surface and upper- air elements are transmitted~ |
| ~CLIMATt~ | ~CLIMAT(T)~ | ~Station for which monthly climatological means of upper-air elements are transmitted~ |

## **Reason**

Correction of a mistake or inconsistency

## **Stakeholder(s)**

@echarpent

## Context

#215

## Expected Impact of Change

**HIGH** (for deprecated and superseded codes)

The migration of RBCN affiliations to RBON in OSCAR is already in development, so the effort to deal with this issue in OSCAR is not HIGH...

**Comment by echarpent** [comment]
For consistency with what we did with RBSN and RBCN, I suggest to drop CLIMAT from the code list. We'll find a way to deal with this outside of the scope of TT-WIGOSMD

**Comment by joergklausen** [comment]
Thank you @fstuerzl, I am fine with these commits.

**Comment by gaochen-larc** [comment]
I reviewed the branch and agree with your changes @fstuerzl.  Thank you!!!

**Comment by fstuerzl** [comment]
@amilan17, the new branch is correct.
