### ISSUE TITLE
Add 'fog collection' to table 5-02-01 

### ISSUE THREAD

**Issue by SalomeKruger** [wmo-im/wmds#388]
# Proposal Summary

## **Summary and Purpose**

Fog collection as an observing method does not appear in the code list, and should therefore be added.

## Final Proposal 

~updated 3 June 2022

| **Notation** | **Name** | **Description** |
| --- | --- | --- |
| 343 | Fog collection | Collection of fog using a mesh or similar capturing device and subsequent determination of the equivalent volume or mass of water. |

## **Proposal**

Method name: Fog collection  
Description: Collection of fog using a mesh or similar capturing device and subsequent determination of the equivalent volume or mass of water .  
Domain: Atmosphere  
Tags: Precipitation, In situ, Vertical wire mesh cylinder

## **Reason**

The collection of fog as a type of precipitation is done with the aid of a Juvik fog collector. Fog collection as an observing method does not appear in the Codes list, and it will be a good idea to add it.

## **Stakeholder(s)**

Ministry of Agriculture, Water & Land Reform  
Salome.Kruger@mawlr.gov.na

## Context

Guide to Instruments & Methods of Observation, 2018. WMO. Vol. 1, - Measurement of meteorological variables, Chapter 6: Measurement of Precipitation, 6.6.3: Measurement of fog precipitation, pg 233.

# Expected Impact of Change

Low

**Comment by fstuerzl** [comment]
@SalomeKruger, below I attach the documents, you provided to us in the OSCAR support form. They are certainly interesting for the TT members, who will review the proposal.

 
[2005_Juvik_Delay_Tango.pdf](https://github.com/wmo-im/wmds/files/8582837/2005_Juvik_Delay_Tango.pdf)
[Decagon_Leaf Wetness Sensor.pdf](https://github.com/wmo-im/wmds/files/8582839/Decagon_Leaf.Wetness.Sensor.pdf)
[Gobabeb_Juvik_Picture.pdf](https://github.com/wmo-im/wmds/files/8582841/Gobabeb_Juvik_Picture.pdf)
[Technical Report Juvik_Ekern_Schema_Page6.pdf](https://github.com/wmo-im/wmds/files/8582843/Technical.Report.Juvik_Ekern_Schema_Page6.pdf)

**Comment by JohnEyre** [comment]
This seems to be a sound proposal - if "fog collection" is a recognised observing method and it is not currently in the database then  it should be added.

**Comment by SalomeKruger** [comment]
Good morning Franziska,

Thank you so much.

Have a great day,
Salome

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22](https://github.com/wmo-im/wmds/wiki/2022-05-19-TT-WIGOSMD-22) notes: 

*   team agrees to add method for 'fog collection'

**Comment by amilan17** [comment]
@JohnEyre are you comfortable updating a branch?

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23](https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23) notes: 

@amilan17 update branch

**Comment by amilan17** [comment]
@wmo-im/tt-wigosmd -- we need a definition of 'fog collection'.

**Comment by joergklausen** [comment]
Description added.
