### ISSUE TITLE
1-02 Measurement unit addition

### ISSUE THREAD

**Issue by MKrieger29** [wmo-im/wmds#396]
# Proposal Summary

## **Summary and Purpose**

New addition to the 1-02 code list for Measurement unit.

## **Proposal**

| **notation** | **name** | **description** |
| --- | --- | --- |
| mS.cm-1 | millisiemens per centimetre | SI derived unit of spatial gradient of electrical conductance; SI base equivalent: 0.1 S.m-1 |

## original request

Addition of a new unit:  
label = "millisiemens per centimetre"  
notation = "mS.cm-1"  
description = "SI derived unit of spatial gradient of electrical conductance, equal to 1E-1 S.m-1"

## **Reason**

Used as a reference unit by oceanographic measuring instruments (for XCTDs in the context of this request)

## **Stakeholder(s)**

Rebecca Cowley (Rebecca.Cowley@csiro.au) : XCTD operator for CSIRO.

## Expected Impact of Change

**MEDIUM**

**Comment by joergklausen** [comment]
@amilan17 Can this still be fitted in? Proposal is sound and very simple. If so, we just need a branch.

**Comment by amilan17** [comment]
I think so.

**Comment by amilan17** [comment]
@joergklausen @gaochen-larc 

For consistency with other units, is this slightly revised description correct? 

definition: SI derived unit of spatial gradient of electrical conductance**; SI base equivalent:** 1E-1 S.m-1

**Comment by joergklausen** [comment]
Yes, this is correct. Thanks!

**Comment by amilan17** [comment]
[https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23](https://github.com/wmo-im/wmds/wiki/2022-05-31-TT-WIGOSMD-23) notes: 

@amilan17 update branch and move to ready for FT
