### ISSUE TITLE
Table 5-02-01: Measurement/observing method (atmosphere) - new method for GHG observation

### ISSUE THREAD

**Issue by SakiOhkubo** [wmo-im/wmds#397]
# Proposal Summary

## **Summary and Purpose**

To add some new methods for GHG and other related gas observation listed in WDCGG.

## **Proposal**

Add the following methods:

*   GC-CVAFS
*   GC-TCD
*   Decay counting
*   Light absorption analysis (IR, except NDIR)
*   Tunable Infrared Laser Differential Absorption Spectroscopy (TILDAS)
*   Electrostatic collection method＋ alpha counting

_updated 3 June 2022_

| **Notation** | **Name** | **Description** |
| --- | --- | --- |
| 344 | GC-CVAFS | Gas chromatography and detection by cold vapour atomic fluorescence spectrometry. |
| 345 | GC-TCD | Gas chromatography and detection by a thermal conductivity detector. |
| 346 | Electrostatic collection + alpha counting | Alpha counting after electrostatic collection of measurand. |
| 347 | Tunable Infrared Laser Differential Absorption Spectroscopy (TILDAS) | Tunable Infrared Laser Differential Absorption Spectroscopy (TILDAS). |
| 348 | Radionuclide decay counting \[general\] | Determination of the counts measured per unit time as a result of radionuclide decay. |
| 349 | IR-GFC | Infrared absorption measurement based on the gas-filter correlation technique, a specifique variant of NDIR. |

## **Reason**

These methods are used as metadata for some observation in WDCGG.  
https://gaw.kishou.go.jp/documents/db_list/measurement_method

## **Consultation**

@SakiOhkubo (WDCGG), @gaochen-larc

**Comment by joergklausen** [comment]
Of the originally proposed additions
- Light absorption analysis (IR, except NDIR) >> exists already 
    - [IR spectrometry-radiometry [general]](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_314)
- Decay counting >> three more specific methods exist, namely 
    - [Adsorption - scintillation counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_62)
    - [Alpha counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_64)
    - [Beta counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_75)
@SakiOhkubo: Please provide arguments/specification why the existing elements are insufficient.

- GC-CVAFS >> added
- GC-TCD >> added
- Tunable Infrared Laser Differential Absorption Spectroscopy (TILDAS) >> added
- Electrostatic collection method＋ alpha counting >> added

@SakiOhkubo @gaochen-larc Please review updated proposal and confirm branch.

**Comment by gaochen-larc** [comment]
minor suggestions:

Change "Gas chromatography coupled to cold vapour atomic fluorescence spectrometry" to "Gas chromatography and detection by cold vapour atomic fluorescence spectrometry"

Change "Gas chromatopgraphy coupled to a thermal conductivity detector" to "Gas chromatography and detection by thermal conductivity detector"

Change "Alpha counting after electrostatic collection of measurand" to "Alpha-particle counting after electrostatic collection of measurand" or  "Alpha-particle spectroscopy after electrostatic collection of measurand"

either way is fine with me.   Thanks!

**Comment by SakiOhkubo** [comment]
Thank you for your comments.

> Light absorption analysis (IR, except NDIR) >> exists already
> [IR spectrometry-radiometry [general]](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_314)

I understand. I will use this.

> Decay counting >> three more specific methods exist, namely
> [Adsorption - scintillation counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_62)
> [Alpha counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_64)
> [Beta counting](http://codes.wmo.int/wmdr/ObservingMethodAtmosphere/_75)
> @SakiOhkubo: Please provide arguments/specification why the existing elements are insufficient.

In WDCGG, there are some old datasets whose method can no longer be specified in more detail than the decay counting method. So we would like to set the decay counting method for general use.

Sorry to bother you again, but we would like to add one more method.

- IR-GFC (Infrared gas filter correlation)

Although this is one of the NDIR methods, we usually use by specifying it.

Thank you again for your understanding and cooperation.

**Comment by joergklausen** [comment]
Issue updated as well as branch. Two more methods added. Branch validated.

@gaochen-larc Please confirm branch.

**Comment by gaochen-larc** [comment]
I confirm the validity of this branch.  Thank you!
