### ISSUE TITLE
Propose splitting of category

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#4]
One possible approach to make table 1-01 is to split the category.

**Comment by efucile** [comment]
Created a new branch for this https://github.com/wmo-im/wmds/tree/first-release-of-table-1-01

**Comment by HoratN** [comment]
Uploaded table 1-01, splitted into 
- 1-01-01: Atmosphere
- 1-01-02: Earth
- 1-01-03: Ocean
- 1-01-04: OuterSpace
- 1-01-05: Terrestrial

The table coming from CBS-16 contains a column # with an Id. This Id is used as WMO306_CD in OSCAR Surface and OSCAR Requirements. In the WMDS the WMO306_CD consists of alphabetic characters, but for the majority of the entries the WMO306_CD is missing. 
I suggest to use the numbers coming from CBS-16 and OSCAR for the future WMO306_CD.

**Comment by efucile** [comment]
If I open 1-01-01 I see 5 headers, and 4 values 
WMO306CD_efrs,QualityFlagSysURL_efrs,Path_e,Name_e,Definition_e
37,,\Atmosphere\Aerological soundings,Aerological soundings,
39,,\Atmosphere\Atmospheric density,Atmospheric density,3D field of density of the atmosphere.

I think that we don't need QualityFlagSysURL_efrs

**Comment by efucile** [comment]
To decide if the code figure (number) can be used as identifier we need to make an example of identifier (URI) and see if this is unique. 
We have to remember that this is the root URI for table 1-01
http://codes.wmo.int/common/wmdrObservedVariable

It was decided and approved that Observed Variable is in common area, but with a wmdr prefix. 
Are we going to have the following second level as result of the split?
http://codes.wmo.int/common/wmdrObservedVariable/Atmosphere 
http://codes.wmo.int/common/wmdrObservedVariable/Earth
http://codes.wmo.int/common/wmdrObservedVariable/Ocean
http://codes.wmo.int/common/wmdrObservedVariable/OuterSpace
http://codes.wmo.int/common/wmdrObservedVariable/Terrestrial

What is the difference between Terrestrial and Earth. Is Ocean part of the Earth? 
This looks like a medium classification. What about lakes. Temperature of a lake is in Ocean or Earth?

**Comment by efucile** [comment]
By the way what is a lake? We should perhaps talk of internal waters.

**Comment by HoratN** [comment]
I thought that that the structure of all tables would be the same,  that is to say, "WMO306CD_efrs,QualityFlagSysURL_efrs,Path_e,Name_e,Definition_e".
So now, I conclude that we can choose whatever structure we want? e.g. WMO306CD_efrs,Path_e,Name_e,Definition_e

**Comment by efucile** [comment]
If there is a column that is not used is better to delete it. However we also have to be consistent with the number of headers/columns. Is the definition missing? If the definition is missing we need an extra comma.

**Comment by efucile** [comment]
This is the classification in GRIB2. Please look at code table 4.2
http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/WMO306_vI2_GRIB2_CodeFlag_en.pdf

**Comment by joergklausen** [comment]
Earth is everything to do with geology, seismic stuff, etc. Lakes are part of Terrestrial, as you can see in the code table. This categorization has long been agreed by TT-WMD.

**Comment by joergklausen** [comment]
There are 5 values, but the second is empty, therefore 2 commas in series.

**Comment by efucile** [comment]
We need clear descriptions because this is know to the team but is isn't obvious.

**Comment by joergklausen** [comment]
Definition: Inland body of surface water of significant extent.  (International Glossary of Hydrology, WMO/UNESCO, 2011, Meteoterm 41024)

**Comment by efucile** [comment]
I meant a description of the classification.

**Comment by nuneslf** [comment]
Is this issue still needed?
