### ISSUE TITLE
8-03-01: comparison with OSCAR and Google

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#40]
table on 'Quality Flag'

affected entries:
- changed: (name)
WMDS: Has been changed
OSCAR: changed

- erroneous: (name)
WMDS: Wrong
OSCAR: erroneous

- estimate: (name)
WMDS: Estimated
OSCAR: estimate

- suspect: (name)
WMDS: Doubtful
OSCAR: suspect

- unchecked: (name)
WMDS: Not checked
OSCAR: unchecked

- new entry according to what I found on Google Docs. This entry also exists in table 8-03-02.
poor,Poor,The data should be considered as low quality and may have been rejected.

Which version does the TT prefer? 
E.g. we could choose the OSCAR version, but with a capital letter at the beginning.

**Comment by joergklausen** [comment]
Table 8-04 is linked to this! 8-03-01 and -02 should be referenced to 2 of the entries in 8-04. Please check. If they are, we cannot simply change 8-03-01 and -02. What’s the difference between ‘poor’ and ‘suspect’?

**Comment by HoratN** [comment]
8-03-01 is related to bufr033020,http://codes.wmo.int/bufr4/codeflag/0-33-020.
BUFR uses the same names as WMDS does, but provides no definitions.

**Comment by HoratN** [comment]
Table 8-03-02 is related to waterML2.0 http://www.opengis.net/def/waterml/2.0/quality/.
- entry 'unchecked': 
waterML2.0: The data has not been checked by any qualitative method.
OSCAR and WMDS: The data has not been checked by any qualitative or quantitative method.
- entry 'estimate':
waterML2.0: The data is an estimate only, not a direct measurement.
OSCAR and WMDS: The value has been estimated rather than measured.
- all other entries match

I suggest for table 8-03-02 to keep what we have for the entry 'unchecked' and to adopt the definition from waterML2.0 for the entry 'estimate'.

**Comment by HoratN** [comment]
We could re-establish the link between 8-03-x and 8-04 by:
8-03-01--> 8-03-BUFR
8-03-02--> 8-03-waterML2.0

@efucile is this possible (technically)?

**Comment by HoratN** [comment]
8-03-01: keep WMDS to maintain link to BUFR table

**Comment by HoratN** [comment]
8-03-02: do as suggested above
