### ISSUE TITLE
11-01 new entry for GLONASS

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#41]
TT needs to provide a definition.

**Comment by joergklausen** [comment]
GLONASS (Globalnaya Navigazionnaya Sputnikovaya Sistema) is Russia's version of a Global Navigation Satellite System.

**Comment by nuneslf** [comment]
@HoratN I support this new entry, so I suggest accepting/closing the issue and adding it to the table.

**Comment by LuisaIckes** [comment]
So it is:
WMO306CD_efrs: glonass
Name_e: GLONASS
Definition_e: Location determined using the Russian GLONASS global navigation satellite system. https://www.glonass-iac.ru/en/
?

**Comment by LuisaIckes** [comment]
Solved here: https://github.com/wmo-im/wmds/tree/issue41

**Comment by LuisaIckes** [comment]
is now merged into the development branch, close this issue
