### ISSUE TITLE
FT2022-2 Amendment Document for FT Procedure

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#415]
## [FT2022-2 Amendment Document for FT Procedure ](https://wmoomm.sharepoint.com/:b:/s/wmocpdb/ESKlpwv79BFJukJY6vV218UB1hxXd-gc1KBZGVKn1fc-sA?e=7Qu2OC)

The purpose of this issue is to keep track of the status of these proposed amendments during the fast-track approval procedure.

**Comment by amilan17** [comment]
**NFP recommendation** 
_from email on 11 August 2022_
"The Domain names Terrestrial and Hydrology are listed as separate entries in Table 1-01-06. Terrestrial is described as “Spatial extent comprised of land masses, normally not covered by the ocean or other water bodies and excluding cryosphere” while Hydrology is described as “Non-saline, non-atmosphere, non-cryosphere part of the hydrosphere, including lakes, rivers, groundwater.”
 
Elsewhere in the document (Tables 1-01-05 & 5-02-05) the two Domains co-exist in Tables where only terrestrial appears in the Table’s title but the Tables themselves also contain Descriptions for hydrology.
 
This use of the two Domains in the same table appears to be conflicted.
It is suggested that either: ‘hydrology’ be added in the titles for Tables 1-01-05 & 5-02-05, or the items for the hydrology domain be split into a separate table."

**Comment by amilan17** [comment]
NFP feedback. 
****
From: Emmanuel Roulin <roulin@meteo.be> 
Sent: Thursday, September 1, 2022 9:44 AM
To: WMO Information System (WIS) <wis@wmo.int>
Cc: Francoise Meulenberghs <fgm@meteo.be>; FELTZ Nicolas <nicolas.feltz@spw.wallonie.be>
Subject: FT2022-2 Vol. I.3 - WMDR

Bonjour,
J'ai reçu ce commentaire de Nicolas FELZ du Service Public de Wallonie, Direction des Cours d'Eau non navigables:

"Après un très rapide survol de ce document, je n’ai qu’une seule remarque (outre que le travail me semble assez bien fait) :
Dans la catégorie des ‘current meters’ (notation 364-369 page 17), il manque à mon sens le courantomètre électro-magnétique (Electro-magnetic current meter ?)."

Cordialement,

Emmanuel Roulin
**

**Comment by joergklausen** [comment]
I found a reference to this type of instrument at https://water.usgs.gov/osw/pubs/CompCM.pdf:
"Electromagnetic current meters measure velocity using Faraday's Law, which states that a conductor (water) moving in a magnetic field (generated by the probe) produces a voltage that varies linearly with the flow velocity. Electrodes in the probe detect the voltages generated by the flowing water. Performance for electromagnetic current meters depends on the probe 
shape, location of the electrodes on the probe, and the construction of the meter electronics."
(There are undoubtedly newer references, but this one explains the idea ...)
Colleague from hydrology should follow up and decide if this entry should be added.

**Comment by jbianchi81** [comment]
It is also described in the Guide to Hydrological practices (https://library.wmo.int/doc_num.php?explnum_id=10473) under 5.3.7.4 electromagnetic method

**Comment by amilan17** [comment]
@wmo-im/tt-wigosmd and @wmo-im/tt-wigosmd-collab 
We received some feedback from USGS on the hydrological codes. At first glance, the recommendations seem reasonable and might be able to incorporate some or all of these recommendations in this release. 
[FT2022-2-vI.3-wmdsJMF2(ppr).pdf](https://github.com/wmo-im/wmds/files/9777192/FT2022-2-vI.3-wmdsJMF2.ppr.pdf)

**Comment by amilan17** [comment]
[Response to USGS feedback on FT2022.docx](https://github.com/wmo-im/wmds/files/9930242/Response.to.USGS.feedback.on.FT2022.docx)
