### ISSUE TITLE
Table 1-01-01, Deprecate observed variable (atmosphere) "Aerological soundings"

### ISSUE THREAD

**Issue by nuneslf** [wmo-im/wmds#416]
# Initial Request
The following entry exists in the list of observed variables (atmosphere) [http://codes.wmo.int/wmdr/ObservedVariableAtmosphere/_37]: 
- "Aerological soundings", which is not a physical variable, I think.
Therefore, I suggest to removed it (deprecate it) in the next review cycle, noting that the actual variables, available from the Codes Registry, pressure, temperature, water vapor and upper wind should be used for vertical soundings.
In OSCAR/Surface 36 stations are using such "variable", 30 of these declared as "operational", and around 20 of those are exclusively using "Aerological soundings" and not any of the variables, pressure, temperature, etc.
The following people have been initially contacted about this: @amilan17, @fstuerzl.

# Amendment Details
Deprecate 
|notation|path                             |name                 |description|
|--------|---------------------------------|---------------------|-----------|
|37      |\Atmosphere\Aerological soundings|Aerological soundings|           |

# Requestor
Luis Nunes (WMO Secretariat), @nuneslf 

# Expected Impact
HIGH

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/Meeting-2022.09.22](https://github.com/wmo-im/tt-wigosmd/wiki/Meeting-2022.09.22) notes: 

*   team agrees to deprecate and communicate with OSCAR

**Comment by ferrighi** [comment]
As for the branch provided, I can confirm the correct removal of the variable.
