### ISSUE TITLE
Revision of winds variables

### ISSUE THREAD

**Issue by JohnEyre** [wmo-im/wmds#418]
# Proposal Summary

The wind variables in WMDR - 12005, 12006, 310, 307 - are inconsistent and incomplete.  They should be revised to include:
- wind specified in speed and direction or in components,
- wind at a single level or a vector of levels,
- wind at  specified heights or pressures, or at specified distances from reference levels,
- more complete definition of wind direction - an angle measured clockwise from North.

## **Summary and Purpose**

_\[add brief overview\]_

## **Proposal**

_\[your specific proposal to resolve the issue - update when decision on proposal is finalised\]_

## **Reason**

_\[your reasoning why the proposal resolves the issue\]_

## **Stakeholder(s)**

_\[include names and emails or handles of individuals or groups that introduced the proposal\]_

## Consultations

_\[include names and emails or handles of individuals or groups that reviewed the proposal\]_

## Context

_\[include references to manuals or guides that are reviewed to ensure alignment, if proposal differs then document how and why\]_

## Expected Impact of Change

_\[enter **LOW** (for editorial changes to existing codes), **MEDIUM** (for new codes) or **HIGH** (for deprecated and superseded codes\]_

**Comment by amilan17** [comment]
duplicate issue with #417
