### ISSUE TITLE
3-04: Comparison with OSCAR

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#42]
Table on 'Station/platform type'

- entry on ' underwaterMobile'
WMDS: "Station/platform under water, moving around"
OSCAR: "Observing facility under water, moving around also horizontally"

- all entries: 
WMDS uses the terminology 'Station/platform' but OSCAR uses the terminology 'Observing facility'.

Which version does the TT prefer?

**Comment by joergklausen** [comment]
We should use ‘observing facility’ here, which is more generic. Marine folks don’t use stations, and the term platform has different usage in different communities.

**Comment by HoratN** [comment]
Luis: TT agreed that the Schema will use 'observing facility', but the code tables nevertheless can use 'station/platform type'.
Moreover all other tables use the term station/platform type.
--> keep station/platform type
