### ISSUE TITLE
Table 5-02-05, add electromagnetic current meter

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#425]
### Initial request

    Missing Electromagnetic Current  Meter (ECM).
An ECM uses the Faraday principle of electromagnetic induction, which states that the water moving in a magnetic field will produce a voltage that is proportional to the velocity of the water.   Insert an item with ECM in notations 364-369. It might be relevant to define sub-groups for mechanic, electromagnetic and acoustic devices.                                                                                          

### Amendment details

| notation | path | name | description |
| --- | ---| --- | --- |
| new | | electromagnetic current meter | Determination of water current based on the principle that a conductor (water) moving through a magnetic field will produce an electrical current directly proportional to the speed of movement (Faraday’s law). By measuring this current and the resultant distortion in the magnetic field the instrument can be calibrated to determine point velocities of flowing water. [Based on Manual on Stream Gauging (WMO-No. 1044), Volume I. 2010] |

### Requestor(s)

* Nicolas FELTZ, Service Public de Wallonie, Direction des Cours d'Eau non navigables, Belgium
* Emmanuel ROULIN, Institut Royal Météorologique de Belgique.                                                                                                                               

### Stakeholder(s)

National Hydrological Services, WHOS

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 5-02-05, Measurement/observing method (terrestrial), http://codes.wmo.int/wmdr/ObservingMethodTerrestrial

### Expected impact of change

MEDIUM

### Collaborators

@amilan17, @jbianchi81, @disiiwash, @jkorhonen, José Valles, Paolo Leoni, Joao Carlos Carvalho (JET-HYDMON)

### References

E.g., MacVicar, B.J., Beaulieu, E., Champagne, V. and Roy, A.G. (2007), Measuring water velocity in highly turbulent flows: field tests of an electromagnetic current meter (ECM) and an acoustic Doppler velocimeter (ADV). Earth Surf. Process. Landforms, 32: 1412-1432. https://doi.org/10.1002/esp.1497

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.03-TT-WISOSMD notes: 
* need to create a "method" definition.

**Comment by jbianchi81** [comment]
From Paolo Leoni of WHOS experts group:

Into the "MANUAL ON STREAM GAUGING VOLUME  I – FIELDWORK I" of WMO at page 84 there is a description of current meters of electromagnetic type.
https://library.wmo.int/doc_num.php?explnum_id=219

 

I would suggest you follow the definition of this method:

 

The Electromagnetic current meter method is based on the principle that a conductor (in this case, water) moving through a magnetic field will produce an electric current. 

The velocity of the moving water can be related to the electric current produced and the distortion created in the magnetic field.

**Comment by jbianchi81** [comment]
And from the same source, page 78:

    An electromagnetic current meter is based on the
    principle that a conductor (water) moving through
    a magnetic field will produce an electrical current
    directly proportional to the speed of movement
    (Faraday’s law). by measuring this current and the
    resultant distortion in the magnetic field the
    instrument can be calibrated to determine point
    velocities of flowing water.

**Comment by jbianchi81** [comment]
updated proposal based on comments

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2022.12.08-TT-WIGOSMD notes: 
@gaochen-larc suggests shortening the definition.

**Comment by jbianchi81** [comment]
Thanks @amilan17 and @gaochen-larc . Could you please suggest which part of the definition to remove or shorten?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes: 
the team has agreed to definition as is
