### ISSUE TITLE
update EC-69: 1-01

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#43]
@efucile In the master, the first column with the Ids is missing because it was agreed that this first column will be removed. Unfortunately the column with the WMO306_CD is mostly empty. So we will probably use the Ids as the future WMO306_CD and thus we will need this column to match the entries.

How can we deal with this?

I suggest that I upload the EC version again but with the Ids in the column with the WMO306_CD. And probably this should go into a patch release of EC-69. What do you think?

**Comment by LuisaIckes** [comment]
@efucile @HoratN Is that issue still active?

**Comment by HoratN** [comment]
I openend this issue since I thought that we maybe would get some problems when it comes to the multilingual tables. We can close this issue and reopen it if we see that we need it.
