### ISSUE TITLE
Table 1-01-05 new code for Index velocity

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#431]
### Initial request

**Index velocity**
* Current definition: “Velocity measured along a direction across the stream (acoustic principles) or over the water surface (radar, image velocimetry). [Based on 'velocity index method' in Manual on Stream Gauging (WMO-No. 1044), Volume II. 2010.]”
* Proposed definition change “A measured velocity that is representative of the stream velocity; often measured in a profile or across the stream (acoustic principles) or over the water surface (radar, image velocimetry) but in theory could use any velocity instrument.”

### Amendment details

| notation | path | name | description |
| --- | --- | --- | --- |
| new | hydrological, liquidPhase, surface water, stream, river | stream index velocity | A velocity that is representative of the average stream velocity; often measured in a profile or across the stream or over the water surface [Based on 'velocity index method' in Manual on Stream Gauging (WMO-No. 1044), Volume II. 2010.]|

### Comments

This code was proposed during FT2022-2 and received feedback. Therefore, it should be discussed again.

### Requestor(s)

- Fulford, Janice M (USGS)
- William Bolhofer (NOAA)

### Stakeholder(s)

National Hydrological Services, WHOS
### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 1-01-05

### Expected impact of change

LOW

### Collaborators

@amilan17, @jbianchi81, @disiiwash, @jkorhonen, José Valles, Paolo Leoni, Joao Carlos Carvalho (JET-HYDMON)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD) notes: 

Hydrological editiing team will be working on this

**Comment by jbianchi81** [comment]
I agree with the proposed change. It would be good to have add the bibliographical source.  

I think we should also create a new method for the determination of discharge using an index velocity rating.  See for example Manual on Stream Gauging Vol II, 2.4 https://library.wmo.int/doc_num.php?explnum_id=7705.

Also I noticed we are missing method Acoustic Doppler Velocity Meter (ADVM) (we have Acoustic Velocity Meter AVM and Acoustic Doppler Current Profiler ACDP).

**Comment by jbianchi81** [comment]
Updated base on comments

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes:
(Juan) coordinated with hydro experts; @jbianchi81 update proposal summary with stakeholders and reviewers and update branch

**Comment by amilan17** [comment]
@jbianchi81 when the branch is ready for my review, please open a PR to merge into the **FT2023-1** branch

**Comment by joergklausen** [comment]
@jbianchi81 I have updated the proposal and added the original reference. Please confirm and update the branch ASAP. I will then validate and create a PR.
