### ISSUE TITLE
Table 1-01-05 Revise definition of Runoff

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#434]
### Initial request

This code was developed during the FT2022-2 procedure, however, before publication there were some comments received, they should be discussed, and the team should consider revising the current definition.
```
notation: 12274 
Name: Runoff 
Definition: That part of the precipitation which flows towards a river on the ground surface (surface 
runoff) or within the soil (subsurface runoff or interflow). [International Glossary of Hydrology (WMO-No. 385). 2012 _edition.]
```
Comments: 
1. Add “and generally expressed in mass or volume per unit of time”
1. Remove "That part of..." before precipitation 
1. a river does not need to be present for runoff to occur. suggest removal  

### Amendment details

| notation | path | name | description |
| --- | --- | --- | --- |
| 12274 | hydrological, liquidPhase, surface water | Runoff | That part of the precipitation which flows on the ground surface (surface runoff) or within the soil  (subsurface runoff or interflow) and generally expressed in mass or volume per unit of time, its equivalent in linear units (as the height of a water layer covering a given area) or as a fraction of precipitation. [Based on International Glossary of Hydrology  (WMO-No. 385). 2012 edition.] |

### Requestor(s)

- Fulford, Janice M (USGS)
- William Bolhofer (NOAA)

### Stakeholder(s)

Hydrological community, WHOS

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 1-01-05

### Expected impact of change

LOW

### Collaborators

@amilan17, @jbianchi81,  @disiiwash, @jkorhonen, José Valles, Paolo Leoni, Joao Carlos Carvalho (JET-HYDMON)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2022.11.22-TT-WIGOSMD) notes: 

Hydrological editiing team will be working on this

**Comment by jbianchi81** [comment]
Agree on removing 'towards a river'

**Comment by jbianchi81** [comment]
Updated proposal based on comments.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes: 
@jbianchi81 update issue summary with stakeholders and reviewers

**Comment by amilan17** [comment]
[@jbianchi81](https://github.com/jbianchi81) if/when the branch is ready for my review, please open a PR to merge into the **FT2023-1** branch
