### ISSUE TITLE
table 5-02-05 add: Stream Index-Velocity Rating, Acoustic Doppler Velocity Meter (ADVM)

### ISSUE THREAD

**Issue by jbianchi81** [wmo-im/wmds#437]
### Initial request

This complements the proposal for the new variable [**stream index velocity**](https://github.com/wmo-im/wmds/issues/431). 

### Amendment details

| notation | path | name | description |
| --- | --- | --- | --- |
| new | hydrological, discharge, equation | stream index-velocity rating |  Computation of stream discharge based on a relation between stream index velocity and average velocity (index-velocity rating) and a relation between stage and cross-sectional area (stage-area rating). Given these ratings and concurrent observations of stream index velocity and stage, average velocity and area are computed and finally discharge as their product. [Based on Manual on Stream Gauging (WMO No. 1044), volume I]|
| new | hydrological, velocity, acoustic, doppler | acoustic doppler velocity meter (ADVM) | Determination of water velocity by using the Doppler principle applied to sound transmitted under water, in which the instrument is mounted in a fixed position under the water, giving an index velocity for a significant part of the flowing stream. [Based on Manual on Stream Gauging (WMO No. 1044), volume I]|

### Requestor(s)

JET-HYDMON

### Stakeholder(s)

The hydrological community

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 5-02-05, Measurement/observing method (terrestrial and hydrological). http://codes.wmo.int/wmdr/_ObservingMethodTerrestrial

### Expected impact of change

LOW

### Collaborators

@amilan17, @jbianchi81, @disiiwash, @jkorhonen, José Valles, Paolo Leoni, Joao Carlos Carvalho (JET-HYDMON)

### References

https://library.wmo.int/doc_num.php?explnum_id=219

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.01.12-TT-WIGOSMD notes: 
@jbianchi81 update branch

**Comment by amilan17** [comment]
[@jbianchi81](https://github.com/jbianchi81) if/when the branch is ready for my review, please open a PR to merge into the **FT2023-1** branch
