### ISSUE TITLE
1-01-03: change in content; Deadline 18.4.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#46]
#### amendments to the definitions
- 64,,>Ocean>Topography>Ocean dynamic topography (ODT),Ocean dynamic topography (ODT),Deviation of sea level from the geoid caused by ocean currents (after corrections for tides and atmospheric pressure effects).
into
64,,\Ocean\Topography\Ocean dynamic topography (ODT),**Ocean dynamic topography (ODT)**,Deviation of sea level from the geoid caused by ocean currents (after corrections for tides and atmospheric pressure effects) **- Physical unit: [ cm ] - Accuracy unit: [ cm ].**
-65,,>Ocean>Currents>Ocean surface currents (vector),Ocean surface currents (vector),Water flow on ocean surface.
into
65,,\Ocean\Currents\Ocean surface currents (vector),**Ocean surface currents (vector)**,"Water flow on ocean surface **- Physical unit: [ cm/s ] - Accuracy unit: [ cm/s ] intended as vector error, i.e. the module of the vector difference between the observed vector and the true vector."**
- 71,,>Ocean>Biology>Chlorophyll concentration,Chlorophyll concentration,"Indicator of living phytoplankton biomass, extracted from ocean colour observation."
into
71,,\Ocean\Biology\Chlorophyll concentration ,**Chlorophyll concentration** ,"Indicator of living phytoplankton biomass, extracted from ocean colour observation. **Uncertainty is expressed in mg/m3 for a given concentration of 1 mg/m3 ."**
- 72,,>Ocean>Miscellaneous>Ocean suspended sediments concentration,Ocean suspended sediments concentration,"Variable extracted from ocean colour observation. Indicative of river outflow, re-suspension or pollution of other-than-biological origin."
into
72,,\Ocean\Miscellaneous\Ocean suspended sediments concentration,**Ocean suspended sediments concentration**,"Variable extracted from ocean colour observation. Indicative of river outflow, re-suspension or pollution of other-than-biological origin. **Uncertainty expressed in g/m3 at a specific concentration (e.g., 2 g/m3 ). "**
- 91,,>Ocean>Basic Physical Properties>Ocean salinity,Ocean salinity,3D field of salinity of the ocean Requested in upper and deep ocean.
into
91,,\Ocean\Basic Physical Properties\Ocean salinity,**Ocean salinity**,"3D field of salinity of the ocean Requested in upper and deep ocean **- Physical unit: [ psu ], Practical Salinity Unit, close to 1, determined by CTD"**
- 92,,>Ocean>Basic Physical Properties>Sea surface salinity,Sea surface salinity,Salinity of sea water in the surface layer. In the open ocean the correct term should be “halinity” with reference of the diversity of salts involved.
into
92,,\Ocean\Basic Physical Properties\Sea surface salinity,**Sea surface salinity**,Salinity of sea water in the surface layer **(upper ~ 1 m if observed in MW)**. In the open ocean the correct term should be “halinity” with reference of the diversity of salts involved.
- 95,,>Ocean>Basic Physical Properties>Sea surface temperature,Sea surface temperature,"Temperature of the sea water at surface. **This includes both or either of the** “bulk” temperature refers to the depth of typically 2 m, **and** the “skin” temperature refers to within the upper 1 mm. "
into
95,,\Ocean\Basic Physical Properties\Sea surface temperature,**Sea surface temperature**,"Temperature of the sea water at surface. The “bulk” temperature refers to the depth of typically 2 m, the “skin” temperature refers to within the upper 1 mm. "
- 98,,>Ocean>Waves>Dominant wave direction,**Dominant wave direction**,The direction of the most energetic wave in the spectrum.
into
98,,\Ocean\Waves\Dominant wave direction,Dominant wave direction,One feature of the ocean wave spectrum. It is the direction of the most energetic wave in the spectrum **- Physical unit: [ degrees ] - Accuracy unit: [ degrees ].**
- 101,,>Ocean>Waves>Wave 1D energy frequency spectrum,Wave 1D energy frequency spectrum,"The total wave energy in each frequency band (e.g. 25 frequency bands) regardless of the direction of propagation. Colloquially referred to as the ""1D wave spectrum""."
into
101,,\Ocean\Waves\Wave 1D energy frequency spectrum,**Wave 1D energy frequency spectrum**,1D variable colloquially referred to as "wave spectrum". Describes the wave energy in each frequency band (e.g. 25 frequency bands) regardless of the direction of propagation 
- 102,,>Ocean>Waves>Wave directional energy frequency spectrum,Wave directional energy frequency spectrum,"Describes The wave energy travelling in each direction and frequency band (e.g. 24 distinct azimuth sectors each 15° wide, and 25 frequency bands). Colloquially referred to as the ""2D wave spectrum""."
into
102,,\Ocean\Waves\Wave directional energy frequency spectrum,**Wave directional energy frequency spectrum**,"2D variable colloquially referred to as wave spectrum. Describes the wave energy travelling in each direction and frequency band (e.g., 24 distinct azimuth sectors each 15°deg; wide, and 25 frequency bands)"
- 406,,>Ocean>Snow / Ice / Glacier>Ice>Sea-ice thickness,Sea-ice thickness,Thickness of the ice sheet.
into
406,,\Ocean\Snow / Ice / Glacier\Ice\Sea-ice thickness,**Sea-ice thickness**,Thickness of the ice sheet. **It is related to sea-ice elevation and ice density**
- 407,,>Ocean>Snow / Ice / Glacier>Ice>Sea-ice type,Sea-ice type,Categorization of the type of sea ice.
into
407,,\Ocean\Snow / Ice / Glacier\Ice\Sea-ice type,**Sea-ice type**,"Variable convolving several factors (age, roughness, density, etc.) - Accuracy expressed as number of classes. Actually [ classes^-1 ] is used, so that smaller figure corresponds to better performance as usual."

#### small changes:
744

**Comment by HoratN** [comment]
one new entry:
10080,,\Ocean\Tides,Tides,

**Comment by nuneslf** [comment]
What is the rationale behind that new entry? I note that there is a path "\Ocean\Topography\" that is related to tide(?): #96 Coastal sea level (tide)=Deviation of sea level from local references in coastal zones, caused by local currents and tides (astronomical and wind-induced).
There is also another related(?) entry under the same path: 64,,\Ocean\Topography\Ocean dynamic topography (ODT),**Ocean dynamic topography (ODT)**,Deviation of sea level from the geoid caused by ocean currents (after corrections for tides and atmospheric pressure effects) **

**Comment by HoratN** [comment]
I don't now, it comes from OSCAR. We could also consider it as a parent node of #96, which would be a sensible approach in my opinion. This would mean that we don't have 10080 as a separate entry in this table. 
My suggestion is to reject this new entry for now and discuss about its proper place later.
@nuneslf What do you think?

**Comment by nuneslf** [comment]
I agree to reject this new entry for now.

**Comment by LuisaIckes** [comment]
@nuneslf @HoratN should we take this up again and set a deadline for the discussion?

**Comment by HoratN** [comment]
![image](https://user-images.githubusercontent.com/43061805/56122598-0f0e8b80-5f73-11e9-9ea3-83d088050d97.png)

**Comment by joergklausen** [comment]
As a general principle, I think units of observation should not be part of the variable definitions.

Re: "92,,\Ocean\Basic Physical Properties\Sea surface salinity,Sea surface salinity,Salinity of sea water in the surface layer (upper ~ 1 m if observed in MW). In the open ocean the correct term should be “halinity” with reference of the diversity of salts involved." 
- What is MW? 
- A statement such as "in the open ocean, the correct term should be ..." cannot be part of a definition!

Re: Tides, I don't have an opinion, this must come from the marine experts.

**Comment by HoratN** [comment]
discussion TT-WMD:
remove the units from definitions

**Comment by HoratN** [comment]
At the station Banjul Port https://oscar.wmo.int/surface//index.html#/search/station/stationReportDetails/32695 Tides seem to be measured: 
https://www.tide-forecast.com/locations/Banjul-Gambia/forecasts/latest/six_day
https://tides4fishing.com/af/gambia/banjul
I will include the entry 'Tides' in the WMDS.

**Comment by HoratN** [comment]
added the entry tides in commit a3a25d385385e3e11ea201009b39eba2af01ecc8 on branch [issue46](https://github.com/wmo-im/wmds/tree/issue46)

**Comment by nuneslf** [comment]
@wmo-im/tt-wmd 
The rationale for this path is not clear;
I suggest to re-open the issue and to invite JCOMM-OPS to comment.

**Comment by LuisaIckes** [comment]
I rather suggest to open a new issue instead/but we can also reopen? @nuneslf : Which path are you referring to? Not sure if I can follow what needs to be discussed of this issue and what is ok/done?

**Comment by nuneslf** [comment]
@LuisaIckes and @wmo-im/tt-wmd
I think the whole (sub)tree under Ocean should be reviewed with contributions from representatives of the marine community, for example, I don't think "Wind", "Radiation" and others, belong to this table 1-01-03, at least "Wind" belongs only to "Atmosphere" (1-01-01)?

**Comment by LuisaIckes** [comment]
@nuneslf : Ok, I will open a new issue for that, but I assume that is something for the next release then?

**Comment by joergklausen** [comment]
@nuneslf I have no issue with a review by the community (who would do this, by when?). IMHO, the variables listed presently are correct under Ocean. You have to look at them individually to see.

**Comment by LuisaIckes** [comment]
@nuneslf : It is just the category one layer above the variable that seems non-ocean related- if you click on it you can see that the variable under wind is: Wind stress. For radiation it is: Water-leaving spectral radiance. So it is indeed related to the Ocean and not Atmosphere. However, I opened a [new issue](https://github.com/wmo-im/wmds/issues/113), please move the discussion to there, so that this issue can stay closed.
