### ISSUE TITLE
Reintroduce paths

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#472]
### Details

The problem is that OSCAR/Surface is still using the paths to organize the filtering of codes and in some cases they are unable to map the tags to the paths and cannot introduce the new codes to the application. I think we can address this by adding a column for tags specifically and continue encoding of paths in the CSV tables. This will allow us to continue developing the tag approach, but it also continues the paradigm of having the same code twice for different paths. 

### Requestor

Anna Milan (WMO), @amilan17
 @fstuerzl @luciacap

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.06-TT-WIGOSMD notes: 
(Joerg) the paths are a legacy approach and are implemented in OSCAR/Surface; Tags provide a way to multiple applications for users to filter in a more meaning way. Moving from one-to-one relationship to one-to-many; e.g.. /oceans//temperature /atmosphere//temperature.  OSCAR NextGen will be deployed in 2025 (probably) and will be (hopefully) able to accommodate the tag filtering.

* Team agrees to modify the CSV tables to have three columns: paths, domains, tags;

**Comment by amilan17** [comment]
@fstuerzl @luciacap 

Does the path _need_ to include the parameter name? For example, can it just be 

<table><tbody><tr><td>\Atmosphere\Temperature</td></tr></tbody></table>

instead of 

<table><tbody><tr><td>\Atmosphere\Temperature\Air temperature (at specified distance from reference surface)</td></tr></tbody></table>

**Comment by amilan17** [comment]
@fstuerzl Are the paths used in OSCAR for ObservingMethods?

**Comment by fstuerzl** [comment]
@amilan17 yes, the paths are also used for methods in the same way as for the variables (and programs). In the internal reference table for methods, all entries have a parent method, so that a hierarchical structure can be build up:
![image](https://user-images.githubusercontent.com/72029328/232716007-a7af592f-e6d0-4edb-9d5a-ee33d5bddfda.png)

**Comment by amilan17** [comment]
questions/notes for discussion at meeting:
1. Does the path have to include the name? 
2. "Gas" vs "Gas Phase"
3.

**Comment by amilan17** [comment]
**1-01-03**
* need to review, paths and tags have diverged
notation | 2021-path | 2023-tags | name
-- | -- | -- | --
13 | \Ocean\Topography\Bathymetry | topography | Bathymetry
18 | \Ocean\Basic Physical Properties\Pressure | physical properties | Pressure
62 | \Ocean\Currents\Ocean Current - Direction | currents | Ocean current direction
63 | \Ocean\Currents\Ocean Current - Speed | currents | Ocean current speed
64 | \Ocean\Topography\Ocean dynamic topography (ODT) | physical properties | Ocean dynamic topography (ODT)
65 | \Ocean\Currents\Ocean surface currents (vector) | physical properties | Surface currents
67 | \Ocean\Miscellaneous\Carbon species\Dissolved inorganic carbon (DIC) | biogeochemistry, inorganic carbon | Dissolved inorganic carbon (DIC)
68 | \Ocean\Miscellaneous\Carbon species\Dissolved organic carbon | biogeochemistry, dissolved organic carbon | Dissolved organic carbon
69 | \Ocean\Miscellaneous\Nitrogen species\Dissolved organic nitrogen | biogeochemistry, nitrogen species | Dissolved organic nitrogen
70 | \Ocean\Miscellaneous\Diffuse attenuation coefficient (DAC), turbidity | physical properties | Diffuse attenuation coefficient (DAC), turbidity
71 | \Ocean\Biology\Chlorophyll concentration | biogeochemistry, inorganic carbon | Chlorophyll a concentration
72 | \Ocean\Miscellaneous\Ocean suspended sediments concentration | biogeochemistry, particulate matter | Ocean suspended sediments concentration
73 | \Ocean\Miscellaneous\Oil spill cover | biogeochemistry | Oil spill cover
74 | \Ocean\Biology\Primary production | biology | Primary production
75 | \Ocean\Miscellaneous\Sea surface Mass Flux | physical properties | Sea surface mass flux
76 | \Ocean\Miscellaneous\Sea surface heat flux | physical properties, ocean surface heat flux | Ocean Surface heat flux
77 | \Ocean\Topography\Sea surface height anomaly (SSHA) | physical properties, sea surface height | Sea surface height anomaly (SSHA)
78 | \Ocean\Miscellaneous\Total alkalinity (TA) | biogeochemistry, inorganic carbon | Total alkalinity (TA)
79 | \Ocean\Miscellaneous\pH | biogeochemistry, inorganic carbon | pH
82 | \Ocean\Biology\SiO3= (metasilicate) | biogeochemistry | SiO3= (metasilicate)
85 | \Ocean\Other Gas\O2-Ar ratio | biogeochemistry | O2-Ar ratio
86 | \Ocean\Other Gas\Ocean subsurface dissolved oxygen concentration | biogeochemistry, oxygen | Ocean subsurface dissolved oxygen concentration
87 | \Ocean\Other Gas\Oxygen, dissolved | biogeochemistry, oxygen | Dissolved oxygen
89 | \Ocean\Radiation\Water-leaving spectral radiance | physical properties, radiation | Water-leaving spectral radiance
90 | \Ocean\Reactive Gas\C2H6S (dimethylsulfide, DMS) | biogeochemistry, volatile organic compound | C2H6S (dimethylsulfide, DMS)
91 | \Ocean\Basic Physical Properties\Ocean salinity | physical properties | Subsurface salinity
92 | \Ocean\Basic Physical Properties\Sea surface salinity | physical properties | Sea surface salinity
94 | \Ocean\Basic Physical Properties\Ocean temperature | physical properties, subsurface temperature | Subsurface temperature
95 | \Ocean\Basic Physical Properties\Sea surface temperature | physical properties | Sea surface temperature
96 | \Ocean\Topography\Coastal sea level (tide) | physical properties, sea surface height | Coastal sea level (tide)
98 | \Ocean\Waves\Dominant wave direction | physical properties, sea state | Dominant wave direction
99 | \Ocean\Waves\Dominant wave period | physical properties, sea state | Dominant wave period
100 | \Ocean\Waves\Significant wave height | physical properties, sea state | Significant wave height
101 | \Ocean\Waves\Wave 1D energy frequency spectrum | physical properties, sea state | Wave 1D energy frequency spectrum
102 | \Ocean\Waves\Wave directional energy frequency spectrum | physical properties, sea state | Wave directional energy frequency spectrum
103 | \Ocean\Wind\Wind stress | physical properties, ocean surface stress | Wind stress
311 | \Ocean\Biology\Nitrogen species\NO2- (nitrite) | biogeochemistry, nutrients | NO2- (nitrite)
312 | \Ocean\Biology\Nitrogen species\NO3- (nitrate) | biogeochemistry, nutrients | NO3- (nitrate)
399 | \Ocean\Biology\Phosporus species\PO4= (phosphate) | biogeochemistry, nutrients | PO4= (phosphate)
400 | \Ocean\Biology\Phosporus species\Total organic phosphorus | biogeochemistry, phosporus species | Total organic phosphorus
401 | \Ocean\Cryosphere\Sea ice\Sea-ice cover | cryosphere, sea ice | Sea-ice cover
402 | \Ocean\Cryosphere\Sea ice\Sea-ice elevation | cryosphere, sea ice | Sea-ice elevation
403 | \Ocean\Cryosphere\Sea ice\Sea-ice motion | cryosphere, sea ice | Sea-ice motion
404 | \Ocean\Cryosphere\Sea ice\Sea-ice surface characteristics | cryosphere, sea ice | Sea-ice surface characteristics
405 | \Ocean\Cryosphere\Sea ice\Sea-ice surface temperature | cryosphere, sea ice | Sea-ice surface temperature
406 | \Ocean\Cryosphere\Sea ice\Sea-ice thickness | cryosphere, sea ice | Sea-ice thickness
407 | \Ocean\Cryosphere\Sea ice\Sea-ice type | cryosphere, sea ice | Sea-ice type
408 | \Ocean\Transmissivity\CTD\Transmissivity | physical properties, CTD | Transmissivity
549 | \Ocean\Other Gas\CTD\pO2 | biogeochemistry, CTD | pO2
731 | \Ocean\Basic Physical Properties\Conductivity | physical properties, CTD | Conductivity
732 | \Ocean\Basic Physical Properties\Density | physical properties, CTD | Density
733 | \Ocean\Biology\Zooplankton (size and-or development stage) | biology | Zooplankton (size and/or development stage)
735 | \Ocean\Greenhouse Gas\pCO2 | biogeochemistry, inorganic carbon | pCO2
736 | \Ocean\Greenhouse Gas\pCO2 air-sea flux | biogeochemistry, inorganic carbon | pCO2 air-sea flux
739 | \Ocean\Miscellaneous\Fluorescence (DOM) | physical properties | Fluorescence (DOM)
740 | \Ocean\Topography\Mean dynamic topography (MDT) | physical properties, sea surface height | Mean dynamic topography (MDT)
741 | \Ocean\Topography\Mean sea surface (MSS) | physical properties, sea surface height | Mean sea surface (MSS)
742 | \Ocean\Topography\Sea surface height (SSH, OST) | physical properties, sea surface height | Sea surface height (SSH, OST)
743 | \Ocean\Waves\Wave height | physical properties, sea state | Wave height
744 | \Ocean\Waves\Wave period | physical properties, sea state | Wave period
745 | \Ocean\Waves\Directional waves | physical properties, sea state | Directional waves
10080 | \Ocean\Tides | physical properties, sea surface height | Tides
12244 |   | biogeochemistry, other gas | N2, Ar
12245 |   | biology, plankton | Zooplankton biomass and diversity
12246 |   | biogeochemistry | Ocean subsurface tracers

**Comment by amilan17** [comment]
**1-01-05**

Need to determine how to organize paths with new labels associated with hydrological variables. The paths could be: 

*   Terrestrial
    *   Cryosphere
    *   Hydrological
        *   Groundwater (does well go here?)
        *   Surface water
            *   River
            *   Lake
    *   Land surface
    *   Soil (will need to determine the 6 terrestrial, 2 hydro variables)

<table><tbody><tr><td><strong>Terrestrial</strong></td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td><strong>Cryosphere</strong></td></tr><tr><td>&nbsp;</td><td><strong>Groundwater</strong></td></tr><tr><td>&nbsp;</td><td><strong>Lake</strong></td></tr><tr><td>&nbsp;</td><td><strong>Land surface</strong></td></tr><tr><td>&nbsp;</td><td><strong>River</strong></td></tr><tr><td>&nbsp;</td><td><strong>Soil</strong></td></tr><tr><td>&nbsp;</td><td><strong>Well</strong></td></tr><tr><td>new&nbsp;</td><td>Hydrological</td></tr><tr><td>new&nbsp;</td><td>Aquifer</td></tr><tr><td>new</td><td>liquidPhase</td></tr><tr><td>new</td><td>surface water</td></tr><tr><td>new</td><td>watershed</td></tr><tr><td>new</td><td>reservoir</td></tr><tr><td>new</td><td>stream</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>

**Comment by amilan17** [comment]
\*\*1-01-01\*\*  
\* "Gas" vs "Gas Phase"  
\* Need to determine paths for 12252-12262. Change "remote sensing" to something that is more independant of method?

**Comment by luciacap** [comment]
Hi Anna
Apologies for the late reply.
I checked also with Franziska and we both don’t see the need for the parameter name in the path.

**Comment by joergklausen** [comment]
+1 for listing everything except the variable name itself in the path. If handled in this way, we must assure that it is handled the same way throughout the repo. As paths are not included in the codes registry, I consider this a purely technical change that doesn't need to be listed in the FT amendment. Agreed?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.21-TT-WIGOSMD note: 
removal of the variable name from the path will not have an impact on the FT

**Comment by joergklausen** [comment]
> **1-01-01**
> 
> * "Gas" vs "Gas Phase"
> * Need to determine paths for 12252-12262. Change "remote sensing" to something that is more independant of method?

If I recall correctly, the previous ad-hoc team on ACV has concluded that 'aerosol' should be turned into 'particlce phase'; and to be consistent, 'gas' should turn into 'gas phase'.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.05.04-TT-WIGOSMD notes: 
@nuneslf recommends re-introducing paths without going to FT procedure.

**Comment by joergklausen** [comment]
Yes, that is correct.


___________________
Dr. Jörg Klausen

Federal Department of Home Affairs FDHA
Federal Office of Meteorology and Climatology MeteoSwiss

Operation Center 1 | P.O. Box 257 | CH-8058 Zurich-Airport
Phone: +41 58 460 92 23
***@***.******@***.***> | Mobile: +41 79 702 94 67 | https://orcid.org/0000-0003-2915-6028

All about weather and climate, please visit our website
www.meteoswiss.ch<https://www.meteoswiss.admin.ch/> and MeteoSwiss App<http://www.meteoswiss.admin.ch/home/services-and-publications/beratung-und-service/meteoswiss-app.html>

All about OSCAR/Surface at https://oscar.wmo.int/surface
All about GAWSIS at https://gawsis.meteoswiss.ch<https://gawsis.meteoswiss.ch/>

**Comment by amilan17** [comment]
<table><tbody><tr><td><strong>Table 1-01-01 paths</strong></td><td><strong>Count of path</strong></td></tr><tr><td>\Atmosphere</td><td>8</td></tr><tr><td>\Atmosphere\Aerosol</td><td>1</td></tr><tr><td>\Atmosphere\Aerosol\Composition</td><td>1</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Inorganic anions</td><td>9</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Inorganic carbonaceous</td><td>4</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Inorganic cations</td><td>12</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Inorganic nitrogen species</td><td>12</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Major inorganic components</td><td>6</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Organic anions</td><td>8</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Organic carbonaceous</td><td>2</td></tr><tr><td>\Atmosphere\Aerosol\Composition\Trace elements</td><td>53</td></tr><tr><td>\Atmosphere\Aerosol\Physical properties - primary</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Fungi\Capnodiales</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Fungi\Pleosporales</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Adoxaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Altingiaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Amaranthaceae</td><td>2</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Aquifoliaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Arecaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Asteraceae</td><td>4</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Betulaceae</td><td>6</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Brassicaceae</td><td>2</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Buxaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Cannabaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Caryophyllaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Cupressaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Cyperaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Elaeagnaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Ericaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Euphorbiaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Fagaceae</td><td>3</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Ginkgoaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Juglandaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Juncaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Malvaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Moraceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Oleaceae</td><td>4</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Pinaceae</td><td>6</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Plantaginaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Platanaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Poaceae</td><td>3</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Polygonaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Ranunculaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Rosaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Salicaceae</td><td>2</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Sapindaceae</td><td>2</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Taxaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Ulmaceae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Umbelliferae</td><td>1</td></tr><tr><td>\Atmosphere\Bioaerosol\Pollen\Urticaceae</td><td>2</td></tr><tr><td>\Atmosphere\Clouds</td><td>8</td></tr><tr><td>\Atmosphere\Clouds\Ice</td><td>4</td></tr><tr><td>\Atmosphere\Clouds\Liquid water</td><td>1</td></tr><tr><td>\Atmosphere\Clouds\Optical properties</td><td>4</td></tr><tr><td>\Atmosphere\Clouds\Position</td><td>3</td></tr><tr><td>\Atmosphere\Clouds\Type</td><td>4</td></tr><tr><td>\Atmosphere\Dynamics</td><td>3</td></tr><tr><td>\Atmosphere\Gas phase</td><td>5</td></tr><tr><td>\Atmosphere\Gas phase\Alcohol</td><td>2</td></tr><tr><td>\Atmosphere\Gas phase\Alkane</td><td>2</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas&nbsp;</td><td>1</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas</td><td>8</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\CFCs</td><td>5</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\Halocarbons</td><td>6</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\Halocarbons\CI Species</td><td>10</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\Halon</td><td>2</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\HCFCs</td><td>5</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\HFCs</td><td>11</td></tr><tr><td>\Atmosphere\Gas phase\Greenhouse gas\PFCs</td><td>3</td></tr><tr><td>\Atmosphere\Gas phase\Other gas</td><td>3</td></tr><tr><td>\Atmosphere\Gas phase\Reactive gas</td><td>17</td></tr><tr><td>\Atmosphere\Gas phase\Reactive gas\Nitrogen containing compounds</td><td>9</td></tr><tr><td>\Atmosphere\Gas phase\Reactive gas\Sulfur containing compounds</td><td>3</td></tr><tr><td>\Atmosphere\Gas phase\Reactive gas\VOC</td><td>72</td></tr><tr><td>\Atmosphere\Gas phase\Terpene</td><td>7</td></tr><tr><td>\Atmosphere\Humidity</td><td>7</td></tr><tr><td>\Atmosphere\Lightning</td><td>6</td></tr><tr><td>\Atmosphere\Lightning\Position</td><td>3</td></tr><tr><td>\Atmosphere\Particle Phase</td><td>1</td></tr><tr><td>\Atmosphere\Particle phase\Optical properties</td><td>21</td></tr><tr><td>\Atmosphere\Particle phase\Physical properties</td><td>27</td></tr><tr><td>\Atmosphere\POPs\PAH</td><td>18</td></tr><tr><td>\Atmosphere\POPs\POP</td><td>11</td></tr><tr><td>\Atmosphere\Precipitation</td><td>6</td></tr><tr><td>\Atmosphere\Pressure</td><td>3</td></tr><tr><td>\Atmosphere\Radiation</td><td>3</td></tr><tr><td>\Atmosphere\Radiation\IR</td><td>3</td></tr><tr><td>\Atmosphere\Radiation\Solar</td><td>4</td></tr><tr><td>\Atmosphere\Radiation\UV</td><td>5</td></tr><tr><td>\Atmosphere\Radionuclide</td><td>80</td></tr><tr><td>\Atmosphere\Remote sensing</td><td>4</td></tr><tr><td>\Atmosphere\Remote sensing\Optical properties</td><td>7</td></tr><tr><td>\Atmosphere\Temperature</td><td>4</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition</td><td>4</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Inorganic acid</td><td>1</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Inorganic anions</td><td>7</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Inorganic cations</td><td>4</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Inorganic nitrogen species</td><td>3</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Organic acid</td><td>3</td></tr><tr><td>\Atmosphere\Total Atmospheric Deposition\Trace elements</td><td>13</td></tr><tr><td>\Atmosphere\Visibility</td><td>2</td></tr><tr><td>\Atmosphere\Visibility\Obscurations</td><td>6</td></tr><tr><td>\Atmosphere\Wind</td><td>6</td></tr><tr><td>Atmosphere\Dynamics</td><td>1</td></tr><tr><td>Atmosphere\Gas phase\Greenhouse gas\CFCs</td><td>1</td></tr><tr><td>Atmosphere\Gas phase\Greenhouse gas\Halon</td><td>2</td></tr><tr><td>Atmosphere\Gas phase\Greenhouse gas\HCFCs</td><td>1</td></tr><tr><td>Atmosphere\Gas phase\Greenhouse gas\OVOC</td><td>18</td></tr><tr><td><strong>Grand Total</strong></td><td><strong>664</strong></td></tr></tbody></table>

**Comment by amilan17** [comment]
Table  1-01-03 paths | Count of path with names
-- | --
\Ocean\Biogeochemistry | 14
  | C2H6S (dimethylsulfide, DMS)
  | Chlorophyll a concentration
  | Dissolved organic nitrogen
  | Dissolved oxygen
  | Fluorescence (DOM)
  | N2, Ar
  | O2-Ar ratio
  | Ocean subsurface dissolved oxygen concentration
  | Ocean subsurface tracers
  | Ocean suspended sediments concentration
  | Oil spill cover
  | pH
  | SiO3= (metasilicate)
  | Total alkalinity (TA)
\Ocean\Biogeochemistry\Nitrogen   species | 2
  | NO2- (nitrite)
  | NO3- (nitrate)
\Ocean\Biogeochemistry\Phosporus   species | 2
  | PO4= (phosphate)
  | Total organic phosphorus
\Ocean\Biology | 3
  | Primary production
  | Zooplankton (size and/or development stage)
  | Zooplankton biomass and diversity
\Ocean\Cryosphere\Sea ice | 7
  | Sea-ice cover
  | Sea-ice elevation
  | Sea-ice motion
  | Sea-ice surface characteristics
  | Sea-ice surface temperature
  | Sea-ice thickness
  | Sea-ice type
\Ocean\Physical properties | 9
  | Diffuse attenuation coefficient (DAC), turbidity
  | Ocean Surface heat flux
  | Pressure
  | Sea surface mass flux
  | Sea surface salinity
  | Sea surface temperature
  | Subsurface salinity
  | Subsurface temperature
  | Tides
\Ocean\Physical properties\CTD | 2
  | Conductivity
  | Density
  | \Ocean\Physical properties\Currents
  | Ocean current direction
  | Ocean current speed
  | Surface currents
  | \Ocean\Physical properties\Radiation
  | Water-leaving spectral radiance
  | \Ocean\Topography
  | Bathymetry
  | Coastal sea level (tide)
  | Mean dynamic topography (MDT)
  | Mean sea surface (MSS)
  | Ocean dynamic topography (ODT)
  | Sea surface height (SSH, OST)
  | Sea surface height anomaly (SSHA)
  | Transmissivity
\Ocean\Waves | 8
  | Directional waves
  | Dominant wave direction
  | Dominant wave period
  | Significant wave height
  | Wave 1D energy frequency spectrum
  | Wave directional energy frequency spectrum
  | Wave height
  | Wave period
\Ocean\Wind | 1
  | Wind stress



</body>

</html>

**Comment by amilan17** [comment]
Table 1-01-05 paths | Count of path
-- | --
\Terrestrial\Cryosphere\Glacier | 7
\Terrestrial\Cryosphere\Ice sheet | 1
\Terrestrial\Cryosphere\Lake ice | 1
\Terrestrial\Cryosphere\Permafrost | 3
\Terrestrial\Cryosphere\River ice | 1
\Terrestrial\Cryosphere\Snow | 7
\Terrestrial\Groundwater | 1
\Terrestrial\Hydrological\Aquifer\Groundwater | 9
\Terrestrial\Hydrological\Aquifer\Groundwater\Well | 1
\Terrestrial\Hydrological\Groundwater | 3
\Terrestrial\Hydrological\Groundwater\Soil | 1
\Terrestrial\Hydrological\Liquid   phase\Groundwater | 1
\Terrestrial\Hydrological\Liquid   phase\Soil | 1
\Terrestrial\Hydrological\Liquid   phase\Surface water | 10
\Terrestrial\Hydrological\Liquid   phase\Surface water\Lake | 1
\Terrestrial\Hydrological\Liquid   phase\Surface water\Reservoir | 2
\Terrestrial\Hydrological\Liquid   phase\Surface water\Stream | 5
\Terrestrial\Hydrological\Liquid   phase\Surface water\Watershed | 1
\Terrestrial\Lake | 3
\Terrestrial\Land surface | 6
\Terrestrial\Land surface\Fire | 3
\Terrestrial\Land surface\Greenhouse gas | 1
\Terrestrial\Land surface\Humidity | 1
\Terrestrial\Land surface\Radiation | 2
\Terrestrial\Land surface\Temperature | 1
\Terrestrial\Land surface\Vegetation | 5
\Terrestrial\River | 2
\Terrestrial\Soil | 2
\Terrestrial\Soil\Humidity | 2
\Terrestrial\Soil\Temperature | 1
\Terrestrial\Well | 1
Grand Total | 86

**Comment by amilan17** [comment]
<table><tbody><tr><td>Table 5-02-01 paths</td><td>Count of path</td></tr><tr><td>\Atmosphere\Aerosol\In situ\Composition</td><td>8</td></tr><tr><td>\Atmosphere\Aerosol\In situ\Optical properties</td><td>6</td></tr><tr><td>\Atmosphere\Aerosol\In situ\Physical properties</td><td>12</td></tr><tr><td>\Atmosphere\Aerosol\Remote-sensing, active</td><td>2</td></tr><tr><td>\Atmosphere\Aerosol\Remote-sensing, active&nbsp;</td><td>2</td></tr><tr><td>\Atmosphere\Aerosol\Remote-sensing, passive\Optical properties</td><td>1</td></tr><tr><td>\Atmosphere\Clouds</td><td>1</td></tr><tr><td>\Atmosphere\Clouds\Remote-sensing, active\Laser-based methods</td><td>1</td></tr><tr><td>\Atmosphere\Dynamics\Numerical model</td><td>1</td></tr><tr><td>\Atmosphere\Dynamics\Numerical model\Dispersion</td><td>1</td></tr><tr><td>\Atmosphere\Dynamics\Numerical model\Trajectories</td><td>3</td></tr><tr><td>\Atmosphere\Evaporation\In situ</td><td>3</td></tr><tr><td>\Atmosphere\Greenhouse gas\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Humidity\In situ\Capacitive method</td><td>1</td></tr><tr><td>\Atmosphere\Humidity\In situ\Dewpoint determination</td><td>2</td></tr><tr><td>\Atmosphere\Humidity\In situ\Hygrometer</td><td>5</td></tr><tr><td>\Atmosphere\Humidity\In situ\Laser-based</td><td>1</td></tr><tr><td>\Atmosphere\Humidity\In situ\Psychrometer</td><td>3</td></tr><tr><td>\Atmosphere\Humidity\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Humidity\Remote-sensing, passive</td><td>3</td></tr><tr><td>\Atmosphere\Micrometeorology\In situ</td><td>11</td></tr><tr><td>\Atmosphere\Ozone\In situ</td><td>8</td></tr><tr><td>\Atmosphere\Ozone\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Ozone\Remote-sensing, passive</td><td>8</td></tr><tr><td>\Atmosphere\Precipitation\In situ</td><td>9</td></tr><tr><td>\Atmosphere\Precipitation\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Pressure\In situ</td><td>7</td></tr><tr><td>\Atmosphere\Radiation\In situ</td><td>4</td></tr><tr><td>\Atmosphere\Radiation\In situ\Direct solar</td><td>2</td></tr><tr><td>\Atmosphere\Radiation\In situ\Longwave</td><td>1</td></tr><tr><td>\Atmosphere\Radiation\In situ\Shortwave</td><td>3</td></tr><tr><td>\Atmosphere\Radiation\Remote-sensing, passive</td><td>1</td></tr><tr><td>\Atmosphere\Radioactivity\In situ</td><td>6</td></tr><tr><td>\Atmosphere\Radiosonde</td><td>4</td></tr><tr><td>\Atmosphere\Temperature\In situ</td><td>7</td></tr><tr><td>\Atmosphere\Temperature\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Temperature\Remote-sensing, passive</td><td>1</td></tr><tr><td>\Atmosphere\Total atmospheric deposition\In situ</td><td>39</td></tr><tr><td>\Atmosphere\Trace gas\In situ</td><td>11</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Chemiluminescence</td><td>5</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Fluorescence</td><td>3</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Gas chromatography</td><td>9</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Ion Chromatography (IC)</td><td>2</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Laser-based methods</td><td>8</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Mass spectrometry</td><td>8</td></tr><tr><td>\Atmosphere\Trace gas\In situ\Optical spectrometry</td><td>1</td></tr><tr><td>\Atmosphere\Trace gas\Remote-sensing, active</td><td>1</td></tr><tr><td>\Atmosphere\Trace gas\Remote-sensing, passive</td><td>3</td></tr><tr><td>\Atmosphere\Visual range\Remote-sensing, active</td><td>2</td></tr><tr><td>\Atmosphere\Wind</td><td>2</td></tr><tr><td>\Atmosphere\Wind\In situ</td><td>12</td></tr><tr><td>\Atmosphere\Wind\Remote-sensing, active</td><td>3</td></tr><tr><td>Grand Total</td><td>242</td></tr></tbody></table>

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.15-TT-WIGOSMD notes: 
team discussed options for removing 'domain' from the paths

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD](https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.30-TT-WIGOSMD) notes:

Anna mentioned that this does not need to be ready for FT2023-2 amendment document and will ask Joerg to review when ready for feedback;

**Comment by amilan17** [comment]
Paths are complete and integrated into the master branch.
