### ISSUE TITLE
Change duplicate notations in tables 1-01-* and 5-02-*

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#474]
### Initial request

OSCAR/Surface parser currently only looks at the last element of a URL and expects a notation that is unique across the entire “namespace” of the element. Thus, the artificial separation of ObservedVariable* and ObservingMethod* into several code tables is essentially ignored by OSCAR/surface. 

### Amendment details
_updated 15 Aug 2023_

supersede with new notations to avoid duplicates across similar tables

table | notation | name
-- | -- | --
5-02-01 | ~344~ 417 | GC-CVAFS
5-02-01 | ~345~ 418 | GC-TCD
5-02-05 | ~346~ 419 | Frequency domain reflectometry
5-02-05 | ~347~ 420| Gamma-ray attenuation
5-02-05 | ~348~ 421| Non-recording gauge
5-02-05 | ~349~ 422| Staff gauge

table | notation | name
-- | -- | --
1-01-01 | ~12245~ 12320| C3H2F6 (1,1,1,3,3,3-hexafluoropropane,   HFC-236fa)
1-01-01 | ~12246~ 12321| Tellurium [Te-131]
1-01-03 | ~12244~ 12319 | N2, Ar
1-01-05 | ~12247~ 12322| Stream velocity
1-01-05 | ~12248~ 12323| Stream mean velocity
1-01-05 | ~12249~ 12324| Stream surface velocity
1-01-05 | ~12251~ 12325| Water surface slope

### Comments

It might be useful to develop some best practices on how to assign numerical notations in such a way that will ensure no duplication, rather than querying all tables to find out what number is the highest. 

### Requestor(s)

@amilan17 @fstuerzl  @luciacap

### Stakeholder(s)

* OSCAR/Surface 
* WIGOS metadata providers and users

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code tables 1-01-01, 1-01-03, 1-01-05, 5-02-01 and 5-02-05

### Expected impact of change

MEDIUM

**Comment by joergklausen** [comment]
I accept some of the (shared) responsibility for not having scrutinized these tables sufficiently before the previous amendments went to FT. These duplicate notations - even though in different name spaces - create difficulties for OSCAR/Surface, but they may also lead to risk of confusion and errors of the users. We should keep the notations unique acroos these sub-tables. The odds are that the effect will be minimal if quickly reacted to, which means I would favor a correction of the codes registry using the 'experimental' flag, in combination with an announcement in the operational WMO letter, and followed of course with a regular CR as part of FT-2023-2.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.06-TT-WIGOSMD notes: 
* (Joerg) would like to make these changes NOW in the codes registry with 'experimental' status and then introduce it to FT for formal approval;  
* Team approves of this approach.

**Comment by amilan17** [comment]
_ObservedVariables_
rowID | proposal | notes | table | notation | in OSCAR (count)? | name
-- | -- | -- | -- | -- | -- | --
1 |   | FT2022-1 | 1-01-01 | 12016 | yes (0) | Cl3CCF3   (1,1,1-trichloro-2,2,2-trifluoroethane, CFC-113a)
2 | change notation | FT2022-1 | 1-01-05 | 12016 | no | Rock glacier velocity
3 |   |   |   |   |   |  
4 |   | FT2021-2 | 1-01-01 | 12244 | yes (0) | C2H2ClF3 (2-chloro-1,1,1-trifluoroethane,   HCFC-133a)
5 | change notation | FT2021-2 | 1-01-03 | 12244 | yes (0) | N2, Ar
6 |   |   |   |   |   |  
7 | change notation | FT2022-1 | 1-01-01 | 12245 | yes (0) | C3H2F6 (1,1,1,3,3,3-hexafluoropropane,   HFC-236fa)
8 |   | FT2021-2 | 1-01-03 | 12245 | yes (0) | Zooplankton biomass and diversity
9 |   |   |   |   |   |  
10 | change notation | FT2022-1 | 1-01-01 | 12246 | yes (0) | Tellurium [Te-131]
11 |   | FT2021-2 | 1-01-03 | 12246 | yes (0) | Ocean subsurface tracers
12 |   |   |   |   |   |  
13 |   | FT2022-1 | 1-01-01 | 12247 | yes (0) | Neodymium [Nd-137]
14 | change notation | FT2022-2 | 1-01-05 | 12247 | no | Stream velocity
15 |   |   |   |   |   |  
16 |   | FT2022-1 | 1-01-01 | 12248 | yes (84) | Attenuated backscatter
17 | change notation | FT2022-2 | 1-01-05 | 12248 | no | Stream mean velocity
18 |   |   |   |   |   |  
19 |   | FT2022-2 | 1-01-01 | 12249 | no | Relative humidity (with respect to water)
20 | change notation | FT2022-2 | 1-01-05 | 12249 | no | Stream surface velocity
21 |   |   |   |   |   |  
22 |   | FT2022-2 | 1-01-01 | 12251 | no | Relative attenuated backscatter
23 | change notation | FT2022-2 | 1-01-05 | 12251 | no | Water surface slope
24 |   |   |   |   |   |  

_ObservingMethods_
rowID | proposal | notes | table | notation | in OSCAR (count)? | name
-- | -- | -- | -- | -- | -- | --
25 |   | FT2022-1 | 5-02-01 | 343 | no | Polarized lidar
26 | change notation | FT2022-2 | 5-02-01 | ~343~ 414 | no | Fog collection
27 |   |   |   |   |   |  
28 | change notation | FT2022-2 | 5-02-01 | ~344~ 415 | no | GC-CVAFS
29 |   | FT2020-2 | 5-02-05 | 344 | yes (73) | Laser ranging
30 |   |   |   |   |   |  
31 |  change notation | FT2022-2 | 5-02-01 | ~345~ 416 | no | GC-TCD
32 |  | FT2022-2 | 5-02-05 | 345 | no | Echo sounding
33 |   |   |   |   |   |  
34 |   | FT2022-2 | 5-02-01 | 346 | no | Electrostatic collection + alpha counting
35 | change notation | FT2022-2 | 5-02-05 | 346 | no | Frequency domain reflectometry
36 |   |   |   |   |   |  
37 |   | FT2022-2 | 5-02-01 | 347 | no | Tunable Infrared Laser Differential   Absorption Spectroscopy (TILDAS)
38 | change notation | FT2022-2 | 5-02-05 | 347 | no | Gamma-ray attenuation
39 |   |   |   |   |   |  
40 |   | FT2022-2 | 5-02-01 | 348 | no | Radionuclide decay counting [general]
41 | change notation | FT2022-2 | 5-02-05 | 348 | no | Non-recording gauge
42 |   |   |   |   |   |  
43 |   | FT2022-2 | 5-02-01 | 349 | no | IR-GFC
44 | change notation | FT2022-2 | 5-02-05 | 349 | no | Staff gauge

**Comment by amilan17** [comment]
Branch is updated but I think this needs to go through the official fast-track procedure because the codes with the old notations will be superseded by the codes with the new notations. I can't simply change the notation in the registry and change the status to 'experimental'. I can only add new notations with the status of 'experimental' and change the status of the superseded codes to 'superseded'.

**Comment by amilan17** [comment]
The only value that I think I can fix now, is fog collection, because it used to be polarized lidar (same notation, same table).

**Comment by joergklausen** [comment]
> Branch is updated but I think this needs to go through the official fast-track procedure because the codes with the old notations will be superseded by the codes with the new notations. I can't simply change the notation in the registry and change the status to 'experimental'. I can only add new notations with the status of 'experimental' and change the status of the superseded codes to 'superseded'.

+1 on going through the FT ... but, technically, you can make the changes already know, and tag them with experimental. Am I missing something?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.05.04-TT-WIGOSMD notes: 
no updates from last meeting;

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.01-TT-WIGOSMD notes: 
no progress yet.

**Comment by amilan17** [comment]
@amilan17 to update branch

**Comment by amilan17** [comment]
@jbianchi81 -- I need to change the notations for some of the hydro methods that were recently added. They are not implemented in OSCAR/Surface yet and I'm hoping that the hydro community is not using them yet either. Can you confirm?

**Comment by jbianchi81** [comment]
> @jbianchi81 -- I need to change the notations for some of the hydro methods that were recently added. They are not implemented in OSCAR/Surface yet and I'm hoping that the hydro community is not using them yet either. Can you confirm?

Yes, you may proceed

**Comment by amilan17** [comment]
@jbianchi81 Thank you for your quick response. I have the same question for observed variables...

**Comment by jbianchi81** [comment]
> @jbianchi81 Thank you for your quick response. I have the same question for observed variables...

@amilan17 same answer...

**Comment by joergklausen** [comment]
@amilan17 Please update initial request to suggest what the request is. As it stands, it's just a problem statement.
