### ISSUE TITLE
Table 9-02 Data policy

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#475]
### Initial request

The new WMO Unified Data Policy was accepted by Cg-Ext-2021 as [Resolution 1](https://library.wmo.int/records/item/58009-wmo-unified-data-policy). It replaces WMO Resolutions 40, 25, 60 and 80. Similar to these depracated resolutions, the new Resolution 1 defines _data classes_ and the policies that apply to them with regards to international data exchange. It has 2 categories: **core data** and **recommended data**. This CR proposes definitions to these two new elements, and their relationship with the existing code list elements. The existing elements in the WMO codes registry for (DataPolicy)[https://codes.wmo.int/wmdr/DataPolicy] include

notation|label|definition
---|---|---
WMOEssental|WMOEssential|WMO Essential Data: free and unrestricted international exchange of basic data and products. 
WMOAdditional|WMOAdditional|WMO Additional Data: free and unrestricted access to data and products exchanged under the auspices of WMO to the research and education communities for non-commercial activities. A more precise definition of the data policy may be additionally supplied within the metadata. In all cases it shall be the responsibility of the data consumer to ensure that they understand the data policy specified by the data provider - which may necessitate dialogue with the data publisher for confirmation of terms and conditions. 
WMOOther|WMOOther|Data identified for global distribution via WMO infrastructure (GTS / WIS) that is not covered by WMO Resolution 25 neither WMO Resolution 40; e.g. aviation OPMET data. Data marked with ''WMOOther'' data policy shall be treated like ''WMOAdditional'' where a more precise definition of the data policy may be additionally supplied within the metadata. In all cases it shall be the responsibility of the data consumer to ensure that they understand the data policy specified by the data provider - which may necessitate dialogue with the data publisher for confirmation of terms and conditions.

#### ADD following elements
notation|label|definition
---|---|---
WMOCore|WMOCore|Earth system data that are necessary for the provision of services in support of the protection of life and property and for the well-being of all nations, at a minimum those data described in Annex 1 to WMO Resolution 1 (https://library.wmo.int/records/item/58009-wmo-unified-data-policy), which are required to monitor and predict seamlessly and accurately weather, climate, water and related environmental conditions. WMO Members shall provide core data on a free and unrestricted basis. The data policy for WMO core data is similar in scope to the previous one for WMO essential data.
WMORecommended|WMORecommended|Earth system data that are required to support Earth system monitoring and prediction activities at the global, regional and national levels and to further assist other WMO Members with the provision of weather, climate, water and related environmental services in their States and Territories. WMO Members should provide access to all recommended data exchanged under the auspices of WMO without charge to public research and education communities for their non-commercial activities, but may place conditions on their use otherwise. The data policy for WMO recommended data encompasses the scope of the previous ones for WMO additional data and WMO other data. Reference: WMO Resolution 1 (https://library.wmo.int/records/item/58009-wmo-unified-data-policy)

#### Make the following codes "invalid"
this was not part of the FT2024-2 proposal
~WMOEssential, WMOAdditional, WMOOther~

### Requestor(s)
@amilan17 

### Stakeholder(s)
WMO Secretariat.
Applications using the WIGOS Codes.
Members at large. 
OSCAR/Surface

### Publication(s)
WMO Unified Data Policy as [Resolution 1, Cg-Ext-2021](https://library.wmo.int/records/item/58009-wmo-unified-data-policy)
Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 9-02, http://codes.wmo.int/wmdr/DataPolicy

### Expected impact of change
MEDIUM (technically feasible, but requires an effort from existing metadata repositories). Applications like OSCAR/Surface and OSCAR/Space that document observations made by Members need to be aware that ongoing data series / observations can no longer be documented with data policies dating back to before Cg-Ext 2021. Thus, a change of data policy assignment needs to be made. For observations labeled as WMOEssential, the new term WMOCoreData may be applied. For observations labeled as either WMO Additional or WMOOther, the new term WMORecommendedData may be applied. For observations that were terminated before Resolution 1 became effective, no change is required.

**Comment by joergklausen** [comment]
At first glance, this requires changes as follows:

addition:
WMOCore, with updated definition
WMORecommended, with updated definition

Open questions, with consequences on further amendments:

1. Can the existing element WMOEssential and WMOAdditional be superseded by WMOCore and WMORecommended? 
2. Will there be a substitute for WMOOther, or should this remain?

Who decides? A priori, this is a high-level governance decision beyond the remit of TT-WIGOSMD.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.04.21-TT-WIGOSMD notes: 
(Joerg) - it's a high level decision to determine if old essential is now core. (John) It's definitely not our decision about what data is labeled core or recommended. We need to check with the authority (?) that the old values are definitely deprecated for legacy data. The definition of core observations will evolve. We should get feedback on the descriptions for old codes. This should go to the chairs of SC-ON.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.05.04-TT-WIGOSMD notes: 
@amilan17 will talk with Kruno first.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2023.06.01-TT-WIGOSMD/ notes: 
@amilan17 talking with Kruno next week; noting that WIS Metadata will also have a need to include data policy values in the WCMP2 metadata;

**Comment by amilan17** [comment]
@kpremic can you please let me know your thoughts on this question: 

1.  Should the existing code values **WMOEssential** and **WMOAdditional** be superseded by **WMOCore** and **WMORecommended**?
2.  Should **WMOOther** also be superseded by **WMORecommended**?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.03.21%E2%80%90TT%E2%80%90WIGOSMD notes: 
@joergklausen will work on this branch

**Comment by joergklausen** [comment]
Proposal updated and ready for review.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.04.09%E2%80%90TT%E2%80%90WIGOSMD notes:
Joerg updated the proposal; 
@amilan17 review the definitions; 
@joergklausen use this link for the UDP: https://library.wmo.int/idurl/4/46772.

**Comment by amilan17** [comment]
to do: add new terms, deprecate old terms in branch

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.05.16%E2%80%90TT%E2%80%90WIGOSMD notes:
Franziska agrees that the previous terms can be deprecated and/or blocked from new additions (TBD), but this does not prevent the proposal moving forward.

**Comment by amilan17** [comment]
@joergklausen I updated the branch. Will you please review it?

**Comment by amilan17** [comment]
2024-08-08 notes from ET-WOT: ok with adding new codes (core and recommended). Deprecation/retirement of the older values may need to go through a different approval process than fast-track.

**Comment by amilan17** [comment]
Add: 
|notation|name|description
|--|--|--
|WMOCore|WMOCore|"Earth system data that are necessary for the provision of services in support of the protection of life and property and for the well-being of all nations, at a minimum those data described in Annex 1 of the Unified Data Policy, which are required to monitor and predict seamlessly and accurately weather, climate, water and related environmental conditions. WMO Members shall provide core data on a free and unrestricted basis. The data policy for WMO core data is similar in scope to the previous one for WMO essential data. Reference: Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (World Meteorological Congress: Abridged Final Report of the Extraordinary Session (WMO-No. 1281))."
|WMORecommended|WMORecommended|"Earth system data that are required to support Earth system monitoring and prediction activities at the global, regional and national levels and to further assist other WMO Members with the provision of weather, climate, water and related environmental services in their States and Territories. WMO Members should provide access to all recommended data exchanged under the auspices of WMO without charge to public research and education communities for their non-commercial activities, but may place conditions on their use otherwise. The data policy for WMO recommended data encompasses the scope of the previous ones for WMO additional data and WMO other data. Reference: Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (World Meteorological Congress: Abridged Final Report of the Extraordinary Session (WMO-No. 1281))."

**Comment by amilan17** [comment]
Final proposal: 

1. don't deprecate **WMOEssential**, **WMOAdditional** and **WMOAdditional**
2. change **WMORecommended** to **recommended** and **WMOCore** to **core** to align with the WIS codes for the WMO data policy. (see http://codes.wmo.int/wis/topic-hierarchy/data-policy)

**Comment by amilan17** [comment]
feedback from ET-WTR for OSCAR/Surface: 
Option 3: Keep old entries (deprecated) but also add/migrate to new ones 
- definition of criteria for standard migration, consultation and migration needed; If this becomes a search criteria, old entries should be available as well in the search.

**Comment by amilan17** [comment]
https://github.com/wmo-im/wmds/issues/559

**Comment by amilan17** [comment]
The conclusion of this issue was to add 'core' and 'recommended' but did not address the legacy codes. Issue #559 has been opened to track the decisions on what to do with the legacy codes.
