### ISSUE TITLE
Add a readme 

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmds#5]
We need to add a readme describing the repository and the project

**Comment by HoratN** [comment]
An initial draft can be found in the branch https://github.com/wmo-im/wmds/tree/Cheatsheet_for_GitHub.

**Comment by nuneslf** [comment]
This is covered by the description in the Wiki: https://github.com/wmo-im/wmds/wiki, so suggest to close the issue.

**Comment by LuisaIckes** [comment]
@efucile Are there parts of the wiki that should be copied into a read-me and added to the repository?

**Comment by LuisaIckes** [comment]
@efucile Maybe it would help to have a readme listing all tables including table names and if possible links to the tables itself?

**Comment by nuneslf** [comment]
Yes, please!
Additionally, the code tables themselves should have their names visible somehow.

**Comment by LuisaIckes** [comment]
@nuneslf I am not sure how to make the names of the codetables visible without changing the name of the files themselves (which we don't want)?

**Comment by LuisaIckes** [comment]
I added the readme- you can find it here:
https://github.com/wmo-im/wmds/blob/Development/tables_en/readme.md
In case you want some addition e.g. information about whom contributed, credits, license etc. please let me know until Monday!

**Comment by nuneslf** [comment]
Just edited the name of table 9-02 to be consistent with EC-69, "Data policy/use constraints", also committed the change to the Development branch.

**Comment by LuisaIckes** [comment]
Good!
