### ISSUE TITLE
Table 1-01, 646, Wrong name (Ammonium instead of Ammonia)

### ISSUE THREAD

**Issue by sdanioth** [wmo-im/wmds#502]
### Initial request

Name of variable 646 is wrong (path is correct). Should be ammonium instead of ammonia. 

646 
 \Atmosphere\Aerosol\Composition\Inorganic nitrogen species\Ammonium (NH4+), PM2.5 
NH4+ (**ammonia**), PM2.5

### Amendment details

646 
 \Atmosphere\Aerosol\Composition\Inorganic nitrogen species\Ammonium (NH4+), PM2.5 
NH4+ (**ammonium**), PM2.5

instead of

646 
 \Atmosphere\Aerosol\Composition\Inorganic nitrogen species\Ammonium (NH4+), PM2.5 
NH4+ (**ammonia**), PM2.5

### Requestor(s)

Sarina Danioth (discussed with Franziska Stürzl)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.3, WMO Codes Registry, Code table 1-01, ObservedVariableAtmosphere, https://codes.wmo.int/wmdr/ObservedVariableAtmosphere),https://codes.wmo.int/wmdr/ObservedVariableAtmosphere/_646

### Expected impact of change

LOW

**Comment by joergklausen** [comment]
Non-controversial, please add branch for validation

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.01.18-TT-WIGOSMD notes: 
@joergklausen I created a branch for you to update
