### ISSUE TITLE
Table 1-01, Capitalisation of elements / variables

### ISSUE THREAD

**Issue by sdanioth** [wmo-im/wmds#506]
### Initial request

The capitalisation within the name of some elements of the table ObservedVariableAtmosphere is not consistent (examples below). 

### Amendment details

Some examples (incomplete list):

- 597: Al (**a**luminium)
- 673: Al (**A**luminium), PM2.5

or

- 602: Cu (**c**opper)
- 692: Cu (**C**opper), PM10

or

- 600: Cr (**c**hromium)
- 690: Cr (**C**hromium), TSP

Proposed changes: make capitalisation consistent. 

### Requestor(s)

- Sarina Danioth
- Jörg Klausen
_MeteoSwiss_

### Publication(s)

https://codes.wmo.int/wmdr/_ObservedVariableAtmosphere 

### Expected impact of change

None

**Comment by ferrighi** [comment]
Now names of elements and compounds in parenthesis are consistently lowercase. Branch is created and linked.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wigosmd/wiki/2024.01.18-TT-WIGOSMD notes: 
easy for next release, note that branch will need to be rebased
