### ISSUE TITLE
FT2023-2 Proposal for Amendments

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wmds#507]
### Details

Document: 
https://wmoomm.sharepoint.com/:b:/s/wmocpdb/EXx8OPTXgstBo5bpm9ty-ZUBZzEpc40i4YhNONtRPqKZHQ?e=0cmRCL

Issues: 
https://github.com/wmo-im/wmds/milestone/9

**Comment by amilan17** [comment]
**Subject: RE: [WMO - fp-oscar-surface] Fw: FT2023-2 Vol. I.3 -WMDR: Proposal for amendments to WIGOS codes** 

Please find below some comments on behalf of Switzerland being also the Operator of OSCAR/Surface - for your consideration:

**Feedback on behalf of Switzerland:**
-          Following program has been forgotten which needs to be integrated into OSCAR/Surface: 
Name 	Notation 	Description 
Copernicus C3S 	C3S 	The Copernicus Climate Change Service (C3S) operated by the European Centre for Medium Range Weather Forecasts (ECMWF), on behalf of the European Union 
 
 
**Feedback on behalf of Switzerland in its role as OSCAR/Surface operators:** 
-          Elimination of observing method  «Sunshine duration»: Since this method is being applied at 428 stations in 25 countries all the FPs need to be contacted and we need a migration plan. Therefore this needs to be considered when planning/implementing the change. 
-          Variable «Upper (X, Y components, horizontal)”:  here we do have the same problem as we do with  «Temperature profile», «Atmospheric pressure profile» etc., which have been already eliminated from the code list. Since we can’t search for a specific geometry in OSCAR/Surface we can’t implement this amendment in OSCAR/Surface and therefore also WDQMS won’t be able to use it. (Unfortunately Franziska was on leave when this was discussed in the TT and couldn’t address it there. The question is how to proceed here since “Temparture profile” and “Atmospheric pressure profile” already have been eliminated. 
-           
Best regards
Estelle

**Comment by amilan17** [comment]
@joergklausen please note the feedback.

**Comment by amilan17** [comment]
As a result of this feedback, Copernicus will be added, Sunshine duration will continue to become invalid and the changes to the wind variables will be reversed pending discussions on how to implement.

**Comment by joergklausen** [comment]
> **Subject: RE: [WMO - fp-oscar-surface] Fw: FT2023-2 Vol. I.3 -WMDR: Proposal for amendments to WIGOS codes**
> 
> Please find below some comments on behalf of Switzerland being also the Operator of OSCAR/Surface - for your consideration:
> 
> **Feedback on behalf of Switzerland:**
> 
>     * Following program has been forgotten which needs to be integrated into OSCAR/Surface:
>       Name:  Copernicus
>       Notation:  C3S
>       Description: The Copernicus Climate Change Service (C3S) operated by the European Centre for Medium Range Weather Forecasts (ECMWF), on behalf of the European Union
> 
> 
> **Feedback on behalf of Switzerland in its role as OSCAR/Surface operators:**
> 
>     * Elimination of observing method  «Sunshine duration»: Since this method is being applied at 428 stations in 25 countries all the FPs need to be contacted and we need a migration plan. Therefore this needs to be considered when planning/implementing the change.
> 
>     * Variable «Upper (X, Y components, horizontal)”: here we do have the same problem as we do with  «Temperature profile», «Atmospheric pressure profile» etc., which have been already eliminated from the code list. Since we can’t search for a specific geometry in OSCAR/Surface we can’t implement this amendment in OSCAR/Surface and therefore also WDQMS won’t be able to use it. (Unfortunately Franziska was on leave when this was discussed in the TT and couldn’t address it there. The question is how to proceed here since “Temparture profile” and “Atmospheric pressure profile” already have been eliminated.
> 
> 
> Best regards Estelle

As discussed with @amilan17 today:

- C3S is not an observing program, it is a data rescue project and a climate data service. I therefore question if Copernicus / C3S should be included in the program/network tree. I believe, the intent is to allow Copernicus / C3S to mint WSIs for (old) stations. In my mind, they could be listed as an organization in OSCAR/Surface and be given the rights / credentials to do that.

- As to wind, I agree to postpone this and keep it on hold. We should have a plan / Timeline for this change, though.
