### ISSUE TITLE
Improvements for Amendment Issue template

### ISSUE THREAD

**Issue by joergklausen** [wmo-im/wmds#524]
### Details

Please include a section on "Systems / applications potentially affected by change", as well as another as part of the work-flow "Proposal reviewed by systems / applications affected". This latter could be in the form of check boxes if this is possible.

### Requestor

Jörg Klausen @joergklausen and OSCAR Application Board

**Comment by amilan17** [comment]
The proposal template is updated, but I haven't added check boxes yet. What should they be: 
- [OSCAR/Surface](https://oscar.wmo.int/surface/#/)
- [OSCAR requirements](https://space.oscar.wmo.int/observingrequirements)
- [Radar DB](https://wrd.mgm.gov.tr/Home/Wrd)
- Other

**Comment by joergklausen** [comment]
Hi @amilan17 This looks very comprehensive. If you want to add checkboxes, then OceanOPS, WHOS, WDQMS, GBON Compliance Monitor should probably be on that list.

**Comment by amilan17** [comment]
done.
