### ISSUE TITLE
2-02 Programme/network affiliation DBCP

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#53]
The entry DBCP exists twice. One entry is the child of the other entry, but both have the same name. 
Why are both entries needed?

**Comment by toakley76** [comment]
Data Buoy Cooperative Programme (DBCP) [ I think] is just a programme so only one entry required.

**Comment by nuneslf** [comment]
I've just emailed Champika Gallage (cgallage@wmo.int) about this.

**Comment by LuisaIckes** [comment]
Changed to: "DBCP others" [here](https://github.com/wmo-im/wmds/tree/issue53b), commit 66616c2.

**Comment by HoratN** [comment]
I updated the path of the entry "DBCP others" in commit 66290985951d35b3af589f54018bb3af48a2b2a6 on the [development branch ](https://github.com/wmo-im/wmds/tree/Development) according to the change made in the name.
