### ISSUE TITLE
Name of column QualityFlagSysURL_efrs

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#54]
This column name was used in table 8-04 'Quality Flag System' but found its way into all tables.
This is confusing. I suggest that we rename this column into URL_efrs in all tables and use this column to state the URL of the source of the entry or the related table.

**Comment by LuisaIckes** [comment]
Luis: "on the structure of table, I don't think we should have the column "QualityFlagSysURL_efrs" for the coming FastTrack procedure; We need to discuss the structure of the code tables for the future evolution, i.e. we may need a "source URL" column but only for Github, not for the CodesRegistry."

**Comment by LuisaIckes** [comment]
So we remove this column for now/the feb fast track in all tables?

**Comment by HoratN** [comment]
I suggest that we remove this columns just before merging the development branch to the master. Since this change might mess up the compares and therefore make our current work a bit harder.

**Comment by LuisaIckes** [comment]
Ok, lets wait until everything else is done and then I can give it a go if there are no other opinions coming up on this.

**Comment by nuneslf** [comment]
Yes, I support removing this column just before merging the development branch to the master for the Feb2019 FastTrack. I suggest we just wait until Thu 21 Feb for any feedback from TT-WMD members.

On the other hand, I think I should create a separate issue and ask EVERYONE to comment on the need (for the future) of extra columns (besides WMO306CD, Name and Definition) across all tables.

**Comment by LuisaIckes** [comment]
@nuneslf  Ok, added a new issue for the discussion about extra columns, for later
