### ISSUE TITLE
wmds/tables_en/9-02.csv line 5 contains an extra double quote "

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wmds#68]
line 5 of 9-02.csv contains an extra double quote and it cannot be rendered as a table by github.
The double quote is before Data (ie "Data .....).
Can you please remove it.

**Comment by HoratN** [comment]
On the development branch it looks ok:
![image](https://user-images.githubusercontent.com/43061805/53005944-91c41000-3434-11e9-81bd-8b6ebe7a78f3.png)
@efucile Should we prepare a branch to correct that also in the master?

**Comment by LuisaIckes** [comment]
I corrected this on the development branch for all the tables where we had similar problems

**Comment by LuisaIckes** [comment]
@efucile so as soon as we merge the development branch into the master for the new release this should be fine?

**Comment by gaubert** [comment]
@LuisaIckes @HoratN @efucile Ok very good, I didn't look at the dev branch. Many thanks.
