### ISSUE TITLE
Code table #1-04 "Geometry" to be added

### ISSUE THREAD

**Issue by nuneslf** [wmo-im/wmds#69]
Code table #1-04 "Geometry" didn't exist by EC-69, it is proposed to added to the Fast Track, following discussions at TT-WMD and based on the corresponding table available in the Google drive. @LuisaIckes

**Comment by LuisaIckes** [comment]
Added it here (commit fe2af09): https://github.com/wmo-im/wmds/tree/issue69
and merged it into the development branch.

**Comment by HoratN** [comment]
This table is in line with the version used in OSCAR
