### ISSUE TITLE
Code table #4-05 "Direction of station pictures" to be added

### ISSUE THREAD

**Issue by nuneslf** [wmo-im/wmds#70]
Code table  #4-05 "Direction of station pictures" didn't exist by EC-69, it is proposed to add it to the Fast Track, following discussions at TT-WMD and based on the table available in the attached doc. @LuisaIckes
[CodeTables_Revision_TT-WDM-6_Zurich_Nov2017_Doc.5.4v4_withedits.docx](https://github.com/wmo-im/wmds/files/2880651/CodeTables_Revision_TT-WDM-6_Zurich_Nov2017_Doc.5.4v4_withedits.docx)

**Comment by LuisaIckes** [comment]
Added it here (commit 28493e7): https://github.com/wmo-im/wmds/tree/issue70
and merged it into the development branch.

**Comment by HoratN** [comment]
This has changed in OSCAR into 

POINTING_ID,DIRECTION_TX,WMO306_CD,DEFINITION_TX
1,N,pointingN,Pointing North
2,NE,pointingNE,Pointing Northeast
3,E,pointingE,Pointing East
4,SE,pointingSE,Pointing Southeast
5,S,pointingS,Pointing South
6,SW,pointingSW,Pointing Southwest
7,W,pointingW,Pointing West
8,NW,pointingNW,Pointing Northwest
9,DOWN,pointingDown,Pointing down
10,unknown,unknown,Unknown pointing direction

Which version do we prefer? Was there a discussion in the TT about this?

**Comment by nuneslf** [comment]
Yes, this code table was approved by TT-WMD-6, as follows:
WMO306_CD | Name | Definition
viewFromN | N | View   from North
viewFromNE | NE | View   from North east
viewFromE | E | View   from East
viewFromSE | SE | View from South east
viewFromS | S | View from South
viewFromSW | SW | View from South west
viewFromW | W | View from West
viewFromNW | NW | View from North west

So, the updates that I see are the new entries "Down" and "unknown";

Again, on the structure of the table I strongly support having the same structure, as a minimum similar to this one here (WMO306_CD, Name, Definition) across all code tables.

Last thing on this table 4-05, the entry "inapplicable" needs to be added.

**Comment by HoratN** [comment]
And whats about the change from 'view from...' to 'pointing to'?

**Comment by nuneslf** [comment]
I support changing from 'view from...' to 'pointing to'. Thanks

**Comment by HoratN** [comment]
ok. I updated the table accordingly in this commit c1a2191 on the branch issue70.
The entry inapplicable is still missing but this can be discussed in issue 29.  So in my opinion this issue can be closed.

**Comment by nuneslf** [comment]
The entry "inapplicable" is still missing

**Comment by HoratN** [comment]
ok. is added now: 
7907f5d

**Comment by LuisaIckes** [comment]
so then we can close this again?

**Comment by joergklausen** [comment]
Hi
Be careful to check what the application says, view from and pointing to are opposite.   If I remember correctly, TT-WMD agreed on pointing to. Also, the (few) existing entries in the DB need to be corrected. Is the column name consistent with pointing to at all?
Kind regards
Jörg

Sent from my iPhone

On 20 Feb 2019, at 16:40, HoratN <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #70<https://github.com/wmo-im/wmds/issues/70>.

**Comment by HoratN** [comment]
The DB currently contains the version with 'pointing to', so I think our decision is in line with Jörg's comment.
