### ISSUE TITLE
Code table #8-02 "Procedure used to estimate uncertainty" missing

### ISSUE THREAD

**Issue by nuneslf** [wmo-im/wmds#71]
Code table #8-02 "Procedure used to estimate uncertainty" is missing; It didn't exist by EC-69, but it is mentioned in latest draft edition of the WIGOS Metadata Standard.
Suggestion is to remove that reference in the WMDS if such table has not yet been developed; Otherwise, if OSCAR/Surface has a table for that purpose, it is suggested to review it, adopt it and to add it to Github for submission to the Fast Track. @LuisaIckes @HoratN

**Comment by joergklausen** [comment]
There ought to be a table, we had one a long time ago. Entries are at least
- GUM, Guide for the ... of uncertainty (ISO, BIPM)
- other

**Comment by HoratN** [comment]
Oscar has the following (in table T_GO_UNCERTAINTY_EVAL_PROC_REF):

UNCERTAINTY_EVAL_PROC_ID,DESCRIPTION_SHORT_TX,DESCRIPTION_LONG_TX,WMO306_CD
1,GUM,Guide for the Expression of Uncertainty in Measurement (JCGM 100:2008),gum
2,(other),Uncertainty estimates derived by other means,other
3,(not available),No uncertainty estimates available,notAvailable
4,(not applicable),Not applicable,notApplicable

**Comment by HoratN** [comment]
Added to branch https://github.com/wmo-im/wmds/tree/issue71 in commit dd7394b.
Updated format of table, changed 'not applicable' to 'inapplicable', added entry unknown in commit 64a62b1.

Now the table looks like this:

WMO306CD_efrs,QualityFlagSysURL_efrs,Path_e,Name_e,Definition_e
gum,,,GUM,Guide for the Expression of Uncertainty in Measurement (JCGM 100:2008)
other,,,(other),Uncertainty estimates derived by other means
notAvailable,,,(not available),No uncertainty estimates available
inapplicable,,,(inapplicable),Inapplicable
unknown,,,(unknown),Procedure used to estimate uncertainty is unknown.

Does this table need further improvements?

**Comment by nuneslf** [comment]
Two comments, that are generic, i.e. for all code tables:
 i- on the entry "notAvailable", I believe the TT-WMD agreed that "not available" is not needed, while having both "unknown" and "inapplicable";
 ii- on the structure of table, I don't think we should have the column "QualityFlagSysURL_efrs" for the coming FastTrack procedure; We need to discuss the structure of the code tables for the future evolution, i.e. we may need a "source URL" column but only for Github, not for the CodesRegistry. I'll make a more generic comment under issue #54.

**Comment by LuisaIckes** [comment]
I think otherwise (if the two above comments are accounted, but not necessarily needed here because they will be corrected through the other open issues anyway) the table is good and we can close this!

**Comment by HoratN** [comment]
I agree with Luisa. We can close this.

**Comment by LuisaIckes** [comment]
Issue71 is not merged into the development branch yet- @HoratN was there a reason for this?

**Comment by LuisaIckes** [comment]
Merged it!
