### ISSUE TITLE
Define roles in workflow

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#73]
Nothing to do with the codelists directly but at some point we should discuss/define the roles in the workflow- who is allowed to do merges to the development branch, master etc..

**Comment by joergklausen** [comment]
Dear all
AFAIK, the owner of this is TT-WMD. The co-chairs, with delegation to Luis, should be the only ones merging. Enrico should be the ones to cut releases.
Kind regards
Jörg


Sent from my iPhone

On 20 Feb 2019, at 11:31, LuisaIckes <notifications@github.com<mailto:notifications@github.com>> wrote:


Nothing to do with the codelists directly but at some point we should discuss/define the roles in the workflow- who is allowed to do merges to the development branch, master etc..

**Comment by nuneslf** [comment]
Jörg is right in terms of the generic governance. However, in more detail, we should agree that:
i- to open an issue and to provide comments = any TT-WMD member, plus Secretariat staff,
ii- to close an issue and to do merges = co-chairs, with delegation to Nina and to Secretariat/WIGOS-PO,
iii- to do the releases = Secretariat/WIS following consultation with co-Chairs and WIGOS-PO.

For the issues, I suggest that from now on we establish a (tentative) deadline each time a new issue is created, giving TT-WMD and Secretariat a finite time frame, whenever possible, for the discussion.

**Comment by LuisaIckes** [comment]
Having a deadline for every new issue is a very good idea! We have to agree how long this should be and maybe distinguish here between technical issues (correction of typos etc.) and changes in the content etc. (e.g. adding units etc.).

**Comment by LuisaIckes** [comment]
We have decided in the Teleconference 04.03.2019 that:
- issues should have a deadline of 30 days
- in case of technical issues (typos etc.) no deadline is needed
- the co-chairs, with delegation to Nina and to Secretariat/WIGOS-PO close the issues (after the deadline) and then the merge to the development branch can be done
- the releases is done by the Secretariat/WIS following consultation with co-Chairs and WIGOS-PO

@HoratN: Can you add this into the workflow?

**Comment by LuisaIckes** [comment]
Maybe we can say that issue with a deadline that need discussion always should get the label "discussion required" until the deadline is over. 
Technical/Typo issue should get a different label- suggestions? These issues only need to be looked at by the co-chairs and not the whole team (?).

**Comment by HoratN** [comment]
I will take care of the workflow.

Moreover I support Luisa's suggestion to use the label "discussion required" to indicate that the participation of the team is needed.
I suggest to create a label "Typo". But I guess that time will show what makes sense.

**Comment by HoratN** [comment]
Workflow and Cheatsheet updated. 
I suggest to close this issue now.

**Comment by LuisaIckes** [comment]
We should add to the workflow that issues can be closed before the deadline in case TT-WMDS finishes the discussion earlier.

**Comment by HoratN** [comment]
I think it would be useful to state something like ' TT-WMDS can close issues during a telecon or a meeting even though the deadline is not over'.
Nevertheless I hope that this will not happen often, because it might prevent members from contributing to an issue.
