### ISSUE TITLE
Need for extra columns

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#74]
For the February fast track release we will have three columns for each table:
WMO306CD
Name
Definition
Are there extra columns which we need in future?

**Comment by HoratN** [comment]
I suggest that we keep all columns which contain at least one entry. This implies that the minimum is:
WMO306CD
Name

And the maximum is 
- WMO306CD
Path
Name
Definition

or 
- WMO306CD
QualityFlagURL
Name
Definition

depending on the table

**Comment by nuneslf** [comment]
I'm OK with that.
@efucile Can we proceed as suggested, for the export of code tables (once we do the release)?

**Comment by LuisaIckes** [comment]
It would also be good if we agree on a consistent naming for the columns, or is there a reason that it is sometimes name and sometimes name_e etc.?

**Comment by LuisaIckes** [comment]
For the February fast track columns were removed following [Ninas comment](https://github.com/wmo-im/wmds/issues/74#issuecomment-465664356) in [this branch](https://github.com/wmo-im/wmds/tree/issue74/).

We should take up this discussion again for the next release: which columns do we want in the Codelists?

**Comment by LuisaIckes** [comment]
Close this issue, because discussion is moved to [issue 90](https://github.com/wmo-im/wmds/issues/90).
