### ISSUE TITLE
Correction of paths in Table 1-01-01, 1-01-02, 1-01-03, 1-01-04, 1-01-05, 2-02, 5-02-01, 5-02-05

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#80]
Some paths contain / or empty spaces in the path name. The space will be removed, / replaced by -. Additionally in Table 2.02 > will be replaced by \\.

**Comment by HoratN** [comment]
The meaning of \ and > in the path is the same. The WMDS used the symbol > and OSCAR uses \. 
Thus I fully support Luisa's suggestion.

**Comment by LuisaIckes** [comment]
What about ( )- can they be left or should they also the removed from the path? 

In case of removing the space between two words should the second one be capitalized to recognize the start of a new word?
