### ISSUE TITLE
7-07 Data format- changes in WMO306_CD

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#82]
The changes discussed [here](https://github.com/wmo-im/wmds/issues/19) are now in the master but they aren't in the development branch at the moment. Can that be solved in the merge onto the master?

**Comment by LuisaIckes** [comment]
That should happen automatically at the merge. The merge of the development into the master does not overwrite the changes done in the master.

**Comment by HoratN** [comment]
These changes got lost:
https://github.com/wmo-im/wmds/issues/19

**Comment by HoratN** [comment]
Added the changes again in commit baf4b33  on branch issue82. 
See [here](https://github.com/wmo-im/wmds/compare/issue82) the changes.

I propose to merge this [branch](https://github.com/wmo-im/wmds/tree/issue82) to the development branch and to close this issue.
