### ISSUE TITLE
Title of Table 4-01-07, Deadline 11.04.2019

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#85]
The Title of Table 4-01-07 is now: Surface cover types (?).
Instead it should be: Surface cover types (Globcover2009).
The file which needs to be changed is (only) the read-me.

**Comment by nuneslf** [comment]
I support the change/correction and I suggest to close the issue.

**Comment by LuisaIckes** [comment]
Corrected in branch [issue85](https://github.com/wmo-im/wmds/tree/Issue85) and commited (229e8d4) to development.
