### ISSUE TITLE
Station class; Deadline 18.4.2019

### ISSUE THREAD

**Issue by HoratN** [wmo-im/wmds#91]
Luisa, with the support from TT-OD (OSCAR development) proposed new station classes which should replace the outdated ones taken from Vol-A.

Thus I propose to amend the WMDS with the following table:
The format is: Name| Description| Notation

- Agricultural meteorological station | A station affiliated with the application area   “Agricultural meteorology”. | agriculturalStation | **new**
- Aircraft meteorological station | A station affiliated with the ABOS program. | aircraftStation | **new**
- Automatic station (AWS) | A station measuring one of the  following observation automatically: pressure, humidity, precipitation,   temperature and horizontal wind speed and direction. | automaticStation | **new**
- Climatological station | A station affiliated with the application area “Climate monitoring   (GCOS)”, “Climate science”, “Climate applications” or the programs “GCOS” or   “RBCN”. | climatologicalStation | **new**
- Cryosphere station | A station measuring a   cryosphere variable . | cryosphereStation | **new**
- Precipitation station | A station measuring amount or intensity of precipitation. | precipitationStation | **new**
- Radiation station | A station measuring a variable related to downwelling or upwelling   radiation. | radiationStation | **new**
- Sea profiling station | A station on sea (fixed, mobile or mobile underwater) measuring the   vertical profile of ocean temperature. | SeaProfilingStation | **new**
- Surface land meteorological station   (SYNOP) | A station on land measuring humidity, pressure, temperature and   horizontal wind speed and direction. | synopLand | **new**
- Surface marine meteorological station   (SYNOP) | A station on sea (fixed, mobile or on ice) measuring atmospheric   pressure. | synopSea | **new**
- Upper-air / PILOT station | A station measuring upper wind with a radiosonde without additional   observations. | upperAirPilot| **update**
- Upper-air / Radiosonde station | A station measuring vertical profiles of pressure and   humidity, temperature or upper wind with a radiosonde. | upperAirRadiosonde | **update**
- Weather radar | A station affiliated with the WRO program. | weatherRadar | present
- Radar wind profiler station | A station affiliated with the GOS program “Wind   Profilers”. | windProfiler | **update**

**Comment by LuisaIckes** [comment]
The description refers to the search criteria as used in OSCAR/Surface- I am not sure if that is useful to have in the WMDS, at least it should be mentioned that this is for/in OSCAR/Surface?

**Comment by nuneslf** [comment]
Luisa is right, the "Station class" is not a WMDS element, it is a list of  combinations of various WMDS elements to help OSCAR/Surface users to find groups of "similar stations", so I don't think it should be added to this repository, unless it is clearly mentioned that it is a OSCAR/Surface table/list.

**Comment by nuneslf** [comment]
And actually, this table is under the responsibility of the Task Team on OSCAR Development (TT-OD), not under responsibility of TT-WMD, so we can't have an approval process for such table using the branches and issues of this repository; On the other hand, TT-OD members are welcome to provide here their comments/suggestions on the WMDS code tables.

**Comment by joergklausen** [comment]
Automatic **weather** station (AWS) | A station **making** one **or several** of the following observation**s** automatically: pressure, humidity, precipitation, temperature and horizontal wind speed and direction. | automaticStation | new

**Comment by joergklausen** [comment]
Surface land meteorological station (SYNOP) | A station on land measuring humidity, pressure, temperature and horizontal wind speed and direction. | synopLand | new

What if only a sub-set of these variables are observed? Does it still qualify for this station class?

**Comment by joergklausen** [comment]
Surface marine meteorological station (SYNOP) | A station on sea (fixed, mobile or on ice) measuring atmospheric pressure. | synopSea | new

What if other variables are observed as well? Does it then no longer qualify for this station class?

**Comment by joergklausen** [comment]
Automatic weather station (AWS) | A station **making** one **or several** of the following observation**s** automatically: pressure, humidity, precipitation, temperature and horizontal wind speed and direction. | automatic**Weather**Station | new

There are other types of automatic stations, so the WMO306_CD should make reference to weather

**Comment by joergklausen** [comment]
We should include this in WMDS, it goes beyond OSCAR/Surface. These definitions are relevant and should be documented. A WMDS code table seems to be a good place for it. Where else?

The contribution of TT-OD here is to provide the guidance wrt to OSCAR/Surface, but it is still TT-WMD who is responsible for the code table.

**Comment by HoratN** [comment]
TT-WMD 17.4.2019

not create a new field for this code table. define Station classes in OSCAR/Surface but not in WMDS
